// 音频转录 / 摘要数据。
// 数据来源：用户放在 /DATA/Media/audio/ 的字幕文件（New recording 21.srt / .txt），
// 由 SRT 解析、按说话人切分并合并为段落而来 —— 智能章节、说话人分离、重点句高光都基于真实字幕内容。
// 设备上没有实时语音转写服务（无 whisper），所以这里是「预生成」的固定数据；
// 接入真实后端（NimoOS-AI + STT/分段/向量化）后，把 lookupTranscript 换成异步请求即可，UI 不用改。
// key = 文件名小写。

export interface TranscriptSegment {
  /** 起始时间，格式 m:ss，用于展示与点击跳转 */
  t: string
  text: string
  /** 说话人 id（说话人分离）——对应 AudioTranscript.speakers；缺省表示未分离 */
  speaker?: string
  /** 是否金句/重点句（重点高光）——后端标注；缺省 false */
  highlight?: boolean
}
/** 智能章节：把转录按主题切段，标题可点击跳转到 t。 */
export interface TranscriptChapter {
  /** 章节标题 */
  title: string
  /** 章节起点时间 m:ss（对齐某个分段的 t） */
  t: string
}
/** 说话人（说话人分离）：给 segment.speaker 提供显示名。 */
export interface TranscriptSpeaker {
  id: string
  name: string
}
export interface AudioTranscript {
  /** 一段话摘要 */
  summary: string
  /** 关键词标签 */
  keywords: string[]
  /** 分段转录（顺序即时间顺序） */
  segments: TranscriptSegment[]
  /** 智能章节（可选）——为空则不显示章节头 */
  chapters?: TranscriptChapter[]
  /** 说话人名单（可选）——为空则不显示说话人标签 */
  speakers?: TranscriptSpeaker[]
}

const TRANSCRIPTS: Record<string, AudioTranscript> = {
  'new recording 21.m4a': {
    summary:
      'A recorded audio-production class on how sound becomes digital. The instructor covers timbre, formants and harmonic vs. non-harmonic sound, then phase and phase cancellation, and traces recording history from wax cylinders and vinyl to magnetic tape and the move to digital. The core explains how computers represent sound — sampling and the Nyquist theorem, why 44.1 kHz became standard, sample rates for video, aliasing, and bit depth / quantization — and closes on file formats (uncompressed WAV/AIFF, lossless FLAC, lossy MP3/M4A/OGG) with a live listening demo comparing bit depths and MP3 bit rates on a Mahler excerpt. Students answer throughout, so it plays as a back-and-forth rather than a monologue.',
    keywords: ['timbre & formants', 'harmonics', 'phase cancellation', 'analog vs digital', 'Nyquist theorem', '44.1 kHz', 'aliasing', 'bit depth', 'WAV / AIFF', 'MP3 & lossy formats'],
    chapters: [
      { title: 'Timbre, formants & harmonics', t: '0:00' },
      { title: 'Phase & phase cancellation', t: '1:35' },
      { title: 'Recording history: wax, vinyl & tape', t: '4:13' },
      { title: 'The shift to digital audio', t: '12:18' },
      { title: 'How computers represent sound', t: '13:56' },
      { title: 'Sampling & the Nyquist theorem', t: '15:47' },
      { title: 'Sample rates & syncing to video', t: '18:53' },
      { title: 'Aliasing', t: '20:40' },
      { title: 'Bit depth & quantization', t: '23:37' },
      { title: 'Quantization noise', t: '26:55' },
      { title: 'File formats: uncompressed (WAV & AIFF)', t: '27:40' },
      { title: 'Compressed lossless (FLAC)', t: '30:14' },
      { title: 'Compressed lossy (MP3, M4A, OGG)', t: '32:31' },
      { title: 'Bit rate & the Mahler listening demo', t: '34:29' },
    ],
    speakers: [
      { id: 's1', name: 'Instructor' },
      { id: 's2', name: 'Student' },
    ],
    segments: [
      { t: '0:00', speaker: 's1', text: 'What\'s happening when I switch between vowels like that is that the shape of my mouth and then like what I\'m doing with my throat is actually changing those formants and changing the harmonic content to change the timbre now along with that we don\'t exclusively have sounds that have clear musical pitches right I mean obviously that\'s self-evident but those types of sounds kind of exist on a' },
      { t: '0:23', speaker: 's1', highlight: true, text: 'On a continuum and so we\'ll talk more about this when we get into frequency modulation synthesis but basically things that have this nice clear harmonic spectrum or things that we might refer to as like harmonic sounds we start with the fundamental frequency and then we just continue to add it to the fundamental whereas you might have things that are non-harmonic where you maybe' },
      { t: '0:43', speaker: 's1', text: 'Just have a bunch of frequencies that are all clustered around one another so white noise for example is an example of this if I just make it sound like is there a clear like fundamental frequency there no right it\'s just kind of a mess of frequencies and then along with that there are sounds that kind of exist in the liminal space so for example speech is maybe more on the non-harmonic side of it but that said like is there a general sense of' },
      { t: '1:09', speaker: 's1', text: 'How high or low my voice is for example yeah and likewise uh there are things like uh especially like church bells and gongs and things like that things that have like a very rich kind of sound to them where it\'s not you maybe do get a discernible center pitch or maybe get multiple center pitches but maybe you also get weird overtones that don\'t necessarily correspond' },
      { t: '1:30', speaker: 's1', text: 'To the fundamental so you might call these inharmonic sounds that just kind of exist between' },
      { t: '1:35', speaker: 's1', highlight: true, text: 'Harmonic and non-harmonic sounds overall right and then finally uh phase so this is something that comes up especially with recording but does have to do with also how we work with synthesizers and how we work with various audio effects so phase simply describes the position in a periodic waveforms cycle although this doesn\'t necessarily have to do with periodic waveforms it' },
      { t: '2:00', speaker: 's1', text: 'For example we have multiple copies of the same sound source so here these two waveforms in red and blue are the same basically right we by looking at them we can tell okay these are the same frequency right takes them just as long to complete their cycle but basically this red wave is starting sooner than the blue one so when you put these two waveforms together basically' },
      { t: '2:24', speaker: 's1', text: 'I would say r in their phase is going to be added or summed together and so at a point like here where they intersect this is going to be let\'s say if this is 0.5 then we have 0.5 plus 0.5 this is going to be one right so it\'s going to boost together now let\'s say we\'re over here where they intersect again so this is going to be you know maybe let\'s say negative 0.5 plus negative 0.5 is negative one right so in this' },
      { t: '2:57', speaker: 's1', text: 'Case again it\'s still going to be perceived as loud generally speaking when you\'re looking at an audio signal like the one we have at the audacity actually this is actually kind of showing you what is happening to the speaker cone itself so the speaker cone pushing the air out or is a speaker cone coming back in and sucking air towards it now imagine these two waveforms were completely out of sync with one another so let\'s say if instead of this' },
      { t: '3:26', speaker: 's1', text: 'Starting at negative half a radian this started at a negative radian so like let\'s say that this point in the blue wave was negative half a radian so let\'s say that this point in the blue wave was lined up exactly with this point in the red wave then you would have one plus negative one which equals zero which means they actually cancel out so particularly in recording this is something we' },
      { t: '3:45', speaker: 's1', text: 'Try to avoid or something we try to fix after the fact especially when you have multiple microphones on the same sound source they arrive at the microphones at different times it takes what is otherwise a more or less identical audio signal it makes them out of phase in one way or another so we want to fix this what we call phase cancellation now that\'s said there are some cases where we actually deliberately cause phase cancellation in order' },
      { t: '4:08', speaker: 's1', text: 'To get certain audio effects things like flanging coursing effects even vibrato effects so that\'s' },
      { t: '4:13', speaker: 's1', text: 'Worth noting all right now uh with that in mind let\'s talk a little bit about analog audio so like right now we\'re in like the most analog audio of all time right my mouth to your ears but uh the first cases of like analog audio recording in particular uh is going to be going back to thomas wax cylinder so i think did you bring that up last time yeah so this is like one of the first' },
      { t: '4:38', speaker: 's1', text: 'Actual recording formats so you can see it here we have this big bell looking thing basically and then it takes the incoming sound it etches it directly onto these wax cylinders and then you would just take that wax cylinder and then you have a little needle that would like read the grooves etched into the wax so that you can actually record and play things back so' },
      { t: '4:59', speaker: 's1', text: 'What do you guys imagine is like the downside to the wax cylinder in terms of the medium it\'s hard to like uh make a lot of or something like make a lot of them and sell them i mean yeah that actually is true as far as i know there wasn\'t a way to like really readily i mean i\'m sure there was a way to like re-record or re-etch onto additional wax cylinders but presumably this' },
      { t: '5:22', speaker: 's1', text: 'Was done in like real time right so imagine you had to like listen to a song every time to make a copy of it right so that\'s one aspect there\'s another aspect that\'s like way way more obvious' },
      { t: '5:34', speaker: 's2', text: 'Yeah wax is like super easy to change' },
      { t: '5:36', speaker: 's1', text: 'Yeah exactly it\'s you know it\'s made out of freaking wax it\'s designed to melt right and it was chosen because it was easy to etch onto right that\'s what made it a usable medium in the first place but this means like okay if you accidentally like grab the wax cylinder too hard with too sweaty of hands guess what you\'ve done damage to your wax cylinder then along with that' },
      { t: '5:54', speaker: 's1', text: 'They just don\'t hold up well over time so they were made basically completely obsolete not even necessarily just by the tape and vinyl but even by like wire recorders that came out later on listen to any wire recorder music recently by any chance no okay that means no one\'s touched the listening assignment yet all right so along with that so vinyl records uh actually were more' },
      { t: '6:19', speaker: 's1', text: 'Broadly available before magnetic tape there was actually used to be a process where you\'d have something very similar to the wax cylinder that you see here but it would just kind of etch directly onto the vinyl and so back in the day the way you would mix music is you\'d have some people stand closer to the recorder basically and so there was a degradation quality' },
      { t: '6:37', speaker: 's1', text: 'Now magnetic tape was invented sometime in like the late 30s or early 40s it was basically invented in nazi germany and for a while was used as a propaganda tool because they would like record hitler\'s voice and then play it all over the country and people are like oh my god hitler\'s everywhere he\'s crazy right in reality it\'s like nobody knew that there was this high quality' },
      { t: '6:58', speaker: 's1', text: 'Medium they just assumed it had to be a live broadcast and then once like all those areas were liberated then like people got old magnetic tape and they\'re like bro you\'re using it for this just gonna made like you know how many bomb ass records we could have made this whole time like if you weren\'t using it for this stupid nonsense right and so a magnetic tape was' },
      { t: '7:17', speaker: 's1', text: 'The go-to for many many years well into the 90s and even into the 2000s to an extent so uh with that in mind like the main advantage to magnetic tape is that now you get crystal clear quality you have a medium that you can re-record onto over and over again and then you can also edit a lot easier compared to like etching directly onto a vinyl record and so that\'s' },
      { t: '7:37', speaker: 's1', text: 'What you\'re going to be able to do with a vinyl or onto a wax cylinder so imagine trying to edit something like on vinyl are you going to get like a little chisel or something or a little scalpel and try to like scrape a groove no that doesn\'t make any sense whereas with magnetic tape you can actually record something to magnetic tape you know that one inch equals about one second' },
      { t: '7:55', speaker: 's1', text: 'Of sound so then from there you can cut things up you could also put things on a jig with a razor blade cut them diagonally to make a crossfade so on so forth you had a lot of options in terms of how you would deal with this medium uh and then along with that it was much easier to run multiple tapes at the same time than record them onto a master tape now that said there\'s a reason that we don\'t use analog tape for basically anything' },
      { t: '8:18', speaker: 's1', text: 'Uh in terms of audio generally speaking anymore so like when it comes to film like how many films are shot on digital cameras versus film cameras these days are there any films shot on film cameras anymore yeah actually there are right so in particular people like christopher nolan even like m. night shamblin is like really big about preserving film right because it\'s not as difficult as working with analog tape there\'s basically no' },
      { t: '8:43', speaker: 's1', text: 'Sound anywhere on any modern film that is done with analog tape anymore so what are the disadvantages that you can imagine with analog tape yep i mean the only one i can remember is like the cassette tape getting like jammed up and stuff like that well i mean yeah there is the issue of like it being all mechanical right so in terms of things that can go wrong you actually would have to have these' },
      { t: '9:13', speaker: 's1', text: 'Real-to-real tape machines and you know thing any minor imperfections with those would affect the playback and then also if they broke they could potentially damage your tape in and of itself but along with that okay giant reel real tape machines how do we feel about having to have something like this just to play a real magnetic tape is that space effect efficient is it cost' },
      { t: '9:36', speaker: 's1', text: 'Efficient no so also imagine this every time you want to report something you\'re spending money on magnetic tape yep like were those back in the day like how much were the tape reporters oh i mean something like that that would be adjusted for inflation that would probably be a few grand at least yeah i mean maybe they have some things down into like a couple hundred but it\'s you know it was not' },
      { t: '10:00', speaker: 's1', text: 'Nearly as affordable as buying like a laptop at a digital audio station there\'s some other uh potential issues with magnetic tape anyone want to guess some of those yeah if you put a magnet close to it doesn\'t like pretty much erase it yep i mean that\'s true of a hard drive as well right but yeah that\'s definitely part of it as well anything else yep the tape itself takes up a lot' },
      { t: '10:24', speaker: 's1', text: 'Of space yeah so imagine like storing everything on a hard drive versus storing things on analog tape and speaking of storing did anyone hear about the columbia records fire that happened a few years ago so basically at columbia records they had all these master tapes of people like jimmy hendrix and rolling stones things like that and basically it caught fire and guess what\'s' },
      { t: '10:43', speaker: 's1', text: 'Really flammable magnetic tape so they lost a bunch of master tapes so thank god there were digital copies of a lot of those somewhere right but now those original analog versions are basically lost to time because of that now along with that tape does degrade as well so there\'s an interesting interview where it\'s between like rick rubin so you know prolific uh producer rather someone\'s working a' },
      { t: '11:05', speaker: 's1', text: 'Lot of genres along with uh neil young so like notoriously like a obnoxious audiophile and both of them say like okay you record something and then you\'re like okay i\'m gonna record something in the afternoon you have to do a rough mix that night because by the time you come back in the morning guess what the tape sounds different than when you recorded it the day before' },
      { t: '11:22', speaker: 's1', text: 'So it\'s not nearly as stable as people have assumed along with that in terms of actually operating real real tape machines properly you have to manually calibrate them many cases sometimes every single time you start a session and then along with that um okay you want to make a copy of something that\'s on a magnetic tape how do you go about doing that again basically real-time recording right what if you make a mistake can you just undo things no right' },
      { t: '11:49', speaker: 's1', text: 'Or if you want to just copy and paste the same thing over and over again recording the same snippet over and over again and then along with that if you look at some of the other features of an analog studio here if you want to like apply audio effects to something like that you actually have to manually wire things in with like a patch bay using actual physical units' },
      { t: '12:07', speaker: 's1', text: 'So you know think about the amount of time people complain about spending money on plugins versus like a physical compressor right and then being able to use only one set of that compressor or' },
      { t: '12:18', speaker: 's1', text: 'Whatever audio effect that is all right so for this reason we basically made the switch over to digital audio uh more or less permanently so the first process for recording audio digitally was at it was in 1957 at bell laboratories this is about the same time as like the process for generating audio digitally was happening uh and of course this early version was not super' },
      { t: '12:43', speaker: 's1', text: 'Capable right it\'s not capable of supplanting magnetic tape at the time but this is just to say that this is really really old technology so that said of course now that computers are like small you know we have a you know you have a computer in your pocket that is more powerful than the one that like brought Neil Armstrong to the moon right uh so now that we have computers like this now' },
      { t: '13:04', speaker: 's1', text: 'It\'s very easy to work with digital audio and along with that you have a lot more options in terms of how precisely you edit right we can edit down to the sample level we can be very precise we paste things easily we can make copies send them wherever basically instantly right uh we can also uh you know make all like you can do lots of experimentation it takes a it\'s much faster' },
      { t: '13:27', speaker: 's1', text: 'Overall we can sequence things uh copy basically later computer generates sound so on so now that said there are certain limitations to digital audio so this is the reason why there are still people who are big on analog audio so there are certain limitations that can\'t necessarily be uh at least in a certain uh sense because of how digital audio works so those things have to be' },
      { t: '13:48', speaker: 's1', text: 'Taken into account as we\'re working in a digital audio so first let\'s talk a little bit about how' },
      { t: '13:56', speaker: 's1', text: 'Computers think about sound of course the main thing is like computers don\'t think right they\'re machines so and also for those of you who are computer science people feel free at any point to like raise your finger and go I\'m actually incorrect me at any point if you think I\'ve been explaining something incorrectly but to start so the way that we\'re going to do this is we\'re going' },
      { t: '14:13', speaker: 's1', text: 'To do this by using the same way computers think period is they work in binary right so in binary the most basic unit of information is a bit which is basically yes no one zero on off so on so forth right and so the issue here is that whereas magnetic tape is recording a continuous stream of an electrical signal onto a physical medium and for us hearing we\'re basically just getting' },
      { t: '14:38', speaker: 's1', text: 'The changes in the air pressure being you know directly vibrating our tympanic membrane right and so it\'s important to understand that when we measure physical data and then we take us out of the image and then we take it back out and compare it with what we have in the Qui-Gon which is how we measure emotional data so with physical data and so on and so forth it\'s not' },
      { t: '14:53', speaker: 's1', text: 'Just just going to do it with a several standard measures you know we\'re not just using the same thing and then we\'re going to use the same equipment we\'re going to use the same equipment in order to create what\'s actually more like a facsimile of that actual audio right so it\'s never quite the perfect amount of resolution compared to analog meetings so until we\'re able to' },
      { t: '15:12', speaker: 's1', text: 'Store sampling we\'re going to necessarily use the same way so the end of the spectrum here it\'s going to be a whole nother expression the big thing is that we have a lot of data and we\'re going to use stuff that are the equivalent of like recording at the speed of light, that will always be the case.' },
      { t: '15:17', speaker: 's1', text: 'And so, even though this means we can\'t ever technically have that same level of sound quality, it does also make it a lot easier to do like very complex editing and processing and like information retrieval of sound, right? Because we can look at every single sample, we can automate those processes, so on and so forth.' },
      { t: '15:35', speaker: 's1', text: 'So, with that in mind, now that we know that we are only getting samples in time of our sound, how do we determine exactly how many samples we need to accurately recreate a sound?' },
      { t: '15:47', speaker: 's1', text: 'So, let\'s say our original waveform is this nice sine wave, right? So, sine wave is just a pure tone with no overtones, it\'s just one pure frequency. So, like if you ever heard of test tone, that\'s generally going to be a sine tone.' },
      { t: '16:00', speaker: 's1', text: 'And so, it\'s original form, it\'s nice and smooth, has no points to it whatsoever. Now, imagine we sample the same sine wave at 10 points. So, is this still accurate? Is this still a nice smooth sine wave? I mean, how close is it to the original?' },
      { t: '16:17', speaker: 's1', text: 'Does it look like the original more or less?' },
      { t: '16:20', speaker: 's2', text: 'Yeah, I guess it seems close enough.' },
      { t: '16:23', speaker: 's1', text: 'But at the same time, we start to add these little pointy bits here and there. Like when we have those points, that does actually have an impact on the sound. So, it\'s not going to be the pure quality. So, clearly 10 points of sampling is not enough.' },
      { t: '16:34', speaker: 's1', text: 'Now, let\'s say we reduce this to 6 points of sampling. So, now does this still more or less have the same curvature of the sine wave? I mean, yeah, we still get like, oh, it goes up and it goes down. It\'s not perfectly straight, right?' },
      { t: '16:51', speaker: 's1', text: 'But along with that, is it still as symmetrical as like sampled at 10 points? No. So, that also is further impacting the resulting sound from our original waveform. Now, if we just sample it at these two points, this is no longer a sine wave.' },
      { t: '17:04', speaker: 's1', text: 'This is what we call a triangle wave. So, once we talk about synthesizers, like we\'ll know more about the difference between sine wave, triangle wave, square wave, so on and so forth. But needless to say, triangle waves sound very different from sine waves.' },
      { t: '17:15', speaker: 's1', highlight: true, text: 'So, now we have something that\'s completely different. So, the way that we determine how many samples we need to kind of more or less accurately represent the sound is determined by something called the Nyquist theorem. So, the Nyquist theorem says we need to be able to capture, we need twice the highest frequency that we are intending to capture.' },
      { t: '17:36', speaker: 's1', text: 'So, for human beings, if we\'re trying to capture a maximum of 20,000 hertz or 20 kilohertz, how many samples do we need every second? If we\'re trying to capture 20,000 cycles per second, how many samples a second do we need? Yeah, exactly.' },
      { t: '17:51', speaker: 's1', highlight: true, text: 'So, how many people have seen this number at some point, 44.1 kilohertz or 44,100 hertz? Yeah, exactly. So, this is what has been more or less the standard sampling rate for most applications. This is the standard sampling rate for a CD.' },
      { t: '18:07', speaker: 's1', text: 'Anyone seen a CD? I guess these days you guys are like collecting CDs. You\'re treating them like vinyl. Right. This is like my understanding of your generation of young people, right? In any case, so, 44.1, basically this was determined with the idea of being like, okay, we need at least 40,000 hertz.' },
      { t: '18:26', speaker: 's1', text: 'Presumably, a little bit of extra headroom would be good for the aliasing, which we\'ll talk about in a second. But in any case, then, okay, how much extra headroom? And so, supposedly, there was this instance back in the day where the CEO of Sony said like, oh, well, we should be able to have all of Beethoven\'s Ninth Symphony be able to fit on a CD.' },
      { t: '18:43', speaker: 's1', text: 'And so, that would be like the maximum that they could add and still fit Beethoven\'s Ninth Symphony onto a CD. I don\'t know how true that is. That\'s the story that I\'ve been told, so to speak.' },
      { t: '18:53', speaker: 's1', text: 'Now, there are other really common sampling rates. So, in particular, like 48k, 96k, 128k, 196k even, you\'ll see from time to time. And basically, these are used to mitigate aliasing and also for synchronizing with video. So, if you work in like film or television or something like that, you\'re more likely to see people working in at least a CD.' },
      { t: '19:12', speaker: 's1', text: 'Now, can anyone think of why 48k would be better for video than 44.1? Yeah. It\'s pretty easy to like pick up when there\'s a difference between what you\'re seeing the mouth do and what you\'re hearing. And so, like if there are any problems in the audio, which are really fast.' },
      { t: '19:34', speaker: 's1', text: 'I mean, that\'s part of it, but this also has to do with when you capture video. So, imagine like what\'s the sampling rate for video or what\'s the term for a sampling rate for video, let\'s say. Yeah.' },
      { t: '19:46', speaker: 's2', text: 'Like frame rate?' },
      { t: '19:47', speaker: 's1', text: 'Not even necessarily. So, how many people of you guys are like gamers, you play like CSGO or anything like that, right? Yeah, frame rate, right? So, how many people like to complain about how this game is only 30 frames per second, right?' },
      { t: '19:58', speaker: 's1', text: 'Things like that. Does anyone know what the historical frame rate for film has been, generally speaking? Yeah.' },
      { t: '20:04', speaker: 's2', text: 'Is it 24?' },
      { t: '20:05', speaker: 's1', text: 'Yeah, exactly. It\'s 24 frames per second. So, 24 frames per second, 48k, that starts to make a lot of sense, right? Now, your audio samples are lining up with your changes in frames, right? And then along with that, 96k, 128k, 196.' },
      { t: '20:20', speaker: 's1', text: 'These are all divisions of 48 or 24, more or less, right? And then for people on the audio side, do we care like that it\'s like a different ratio than 44.1? No, it doesn\'t really impact us in a material way. For people who work in film and television, this is actually a big thing that they\'re trying to do, is trying to make sure things line up with changes in frames.' },
      { t: '20:40', speaker: 's1', text: 'So, along with that, though, the other things that we were trying to mitigate, something called aliasing. So, imagine we have an insufficient sampling rate, or sometimes even a sufficient sampling rate. But let\'s say we have this waveform that\'s in this like black or kind of, I think it\'s actually like a dark, dark green.' },
      { t: '20:58', speaker: 's1', text: 'And so, this is presumably something that is above the sampling rate, above what the sampling rate can capture. The sampling rate is indicated by these red points and these red arrows. And so, the computer\'s capturing, okay, I\'ve got my sample here, here, here, here.' },
      { t: '21:12', speaker: 's1', text: 'And so, as it\'s capturing these samples, it\'s trying to play it back. Then it\'s kind of going like, oh, I think I know what\'s going on here. And you get something that looks like this blue waveform. Now, of course, this blue waveform is not actually what you\'re trying to capture, right?' },
      { t: '21:25', speaker: 's1', text: 'This is basically like, it\'s almost the same thing as like an AI mirage or something like that, right? It\'s something that, like something that\'s getting from the information that it has to the best of its ability. And this causes aliasing.' },
      { t: '21:37', speaker: 's1', text: 'This causes these unintended sounds that work their way into the recording. So, this is also something you can do. You\'ll see visually. So, have you ever noticed if you\'re like driving on the highway and you look to a car next to you and you can actually kind of see the spokes of the wheel look like they\'re turning slowly?' },
      { t: '21:54', speaker: 's1', text: 'Yeah. So, this is visual aliasing. And basically, it\'s because your mind cannot comprehend the wheel, the spokes of the wheel actually going at, you know, like 3,000 rotations per minute, right? But rather, it can still get just that instance of the wheel moving.' },
      { t: '22:08', speaker: 's1', text: 'And it\'s the same thing. It\'s just happening in terms of audio. So, generally speaking, this does not mean that you wind up with a bunch of like fake frequencies in your final recording. But what does happen is that you get a lot of high frequencies that kind of get aliased down and start to get muddled together.' },
      { t: '22:25', speaker: 's1', highlight: true, text: 'And once those all get muddled together, it kind of destroys the clarity. It kind of messes with the spectrum of all the sounds in your recording. And so, because it messes with the spectrum, it also kind of affects the clarity. And so, for that reason, generally speaking, higher sampling rates will sound better if you\'re recording at those sampling rates because it mitigates a lot of that aliasing.' },
      { t: '22:46', speaker: 's1', text: 'So, that said, does that mean you should always like use 196 kilobytes or 196 amps per second? No. So, you know, basically, for every time you increase the sampling rate, you\'re also increasing the amount of memory that you have. So, this is kind of up to your discretion in terms of what you\'re trying to do.' },
      { t: '23:04', speaker: 's1', text: 'Now, if you\'re trying to mix like a Sabrina Carpenter recording and there\'s like millions of dollars going into it, what sampling rate should you use? 196, right? If you\'re doing something where it\'s like a smaller project like, say, for class, does it matter if it\'s only 44.1?' },
      { t: '23:20', speaker: 's1', text: 'No, not so much, right? So, just something to be aware of, generally speaking. Now, another thing we need to talk about in terms of how computers think about sound and what the impact this has in terms of the audio quality and how we think about things.' },
      { t: '23:37', speaker: 's1', highlight: true, text: 'So, we are going to have something called the bit depth. So, the bit depth is basically the number of actual amplitude values that can be measured by the computer. So, think of it this way. If we have something that is one bit audio or one bit ability to record some bit of data, what are our two options for how many steps we can record?' },
      { t: '24:01', speaker: 's1', text: 'We can record on or off, basically, at one bit, right? And then with each additional bit, we\'re able to capture two to the power of that, right? So, now two bit, okay? So, we can have the first one be on or off. The next one can also be on or off.' },
      { t: '24:15', speaker: 's1', text: 'So, now we can have off-off, on-off, off-on, on-off, right? Four. And then, so, as we go up and up, we\'re able to better and more accurately represent and measure that particular parameter, in this case, the amplitude that we\'re capturing.' },
      { t: '24:33', speaker: 's1', text: 'And so, for digital audio, we\'re generally starting, starting at 16 bit. So, at 16 bit, we can measure 65,000 individual levels of quantization. So, 65,000 individual discrete steps of amplitude that can be made. So, in this case, this is enough to get us a pretty clear sound overall.' },
      { t: '24:55', speaker: 's1', text: 'At 24 bit, which is the minimum for most things these days, now we\'re looking at over 16 million individual steps of quantization, so we\'re able to be even more precise. And then, along with that, we\'re able to be very accurate. We\'re able to measure a much larger range in terms of amplitudes.' },
      { t: '25:13', speaker: 's1', text: 'So, in this case, we\'re going from 96 decibels up to 144 decibels. And then, at 32 bit, which is basically kind of the max for most things now, we can measure up to 192 decibels, and we have over 4.2 billion individual steps that we can measure, right?' },
      { t: '25:31', speaker: 's1', text: 'So, we\'re able to be very, very, very precise. So, along with that, you know, having more steps of quantization means we can get better sound quality overall, but having inadequate quantization steps means that we are not able to represent things properly.' },
      { t: '25:49', speaker: 's1', text: 'So, looking at this particular diagram, we have, okay, this nice red sine wave. Once again, in this case, 16 bit resolution. So, you know, we\'re measuring 65,000 individual steps of quantization. But if we look at it, does it more or less look like a sine wave?' },
      { t: '26:07', speaker: 's1', text: 'Yeah. Is it going to sound like a perfect sine wave? Like, it depends on your definition of perfect, right? It\'s going to be probably good enough for 99.999% of people. Now, 3 bit resolution. So, how many steps can we measure at 3 bits?' },
      { t: '26:21', speaker: 's1', text: 'So, 2 to the power of 3. So, 2 times 2 is 4 times 2 is 8. So, like, 8 steps of quantization. And so, when we do that, now we have, okay, 1, 2, 3, 4, 5, 6, 7, 8. And now we have things like kind of stair-step, like an old Mayan pyramid or something like that, right?' },
      { t: '26:46', speaker: 's1', text: 'So, is that going to sound like a sine wave? No, this is going to sound like something completely different. And we\'ll listen to examples of probably different bit depths in a little bit,' },
      { t: '26:55', speaker: 's1', text: 'But it\'s going to add something called quantization noise, which is this really kind of nasty, squishy digital sound. And, you know, with anything else, and, you know, with anything in audio and anything in the arts, like, you know, I say nasty is like a value judgment.' },
      { t: '27:08', speaker: 's1', text: 'It\'s like it\'s bad, right? Are there some cases where maybe you would willfully introduce quantization noise? Yeah, actually. So, for example, there\'s a film that came out a couple years ago called Leave the World Behind. Has anyone seen this on Netflix?' },
      { t: '27:22', speaker: 's1', text: 'Yeah. It\'s probably best you don\'t see it, honestly. It\'s not a great movie. But at one point, they\'re trying to indicate that all the satellites are down. So, they, like, have this quantization noise that they add to the signal to indicate that, uh-oh, there\'s something wrong with the satellites, right?' },
      { t: '27:35', speaker: 's1', text: 'And say, surely you can imagine cases where you\'re doing sound design or music. Maybe you want to add that sound.' },
      { t: '27:40', speaker: 's1', text: 'So, finally, let\'s talk a little bit about file formats, because I did mention that you\'re going to be submitting things as a lossless audio file, or you might also be referred to as, like, an uncompressed audio file. So, the main two formats for these are WAV and AIFF.' },
      { t: '27:57', speaker: 's1', highlight: true, text: 'And so, an uncompressed file is going to have no loss to the audio. There\'s no reduction in audio quality of its source material whatsoever, at least based on the parameters of the digital audio. So, maximum bit depth and the maximum sampling rate.' },
      { t: '28:11', speaker: 's1', text: 'No reduction in audio quality. So, naturally, why would I want you guys to submit uncompressed files without any? There\'s two reasons, really. So, one of them is, I want to hear the best version, right? I want to hear the best quality possible.' },
      { t: '28:29', speaker: 's1', text: 'But then there\'s another concern here. So, for long-term storage of, like, an artistic project that you\'re presumably planning on, like, distributing at other times in the future, you would want to have the highest quality version to go back to at any point, right?' },
      { t: '28:43', speaker: 's1', text: 'Even if you do eventually export two different file formats that\'s uncompressed, right? So, with that, WAV and AIFF. So, does anyone know the difference between these two file formats? Besides the actual extension? Just looking at the letters, is there any guesses that anyone wants to make?' },
      { t: '29:07', speaker: 's1', text: 'Yeah?' },
      { t: '29:08', speaker: 's2', text: 'Is WAV, like, Windows? And, like, AIFF is for Mac?' },
      { t: '29:12', speaker: 's1', text: 'That\'s exactly correct. Yeah. So, WAV is, like, Windows Audio Video. And AIFF is Apple Interleave File Format, basically. And so, there was a period in time where nary shall the two meet. So, like, if you had an iPod, all your stuff that was lost was AIFF.' },
      { t: '29:27', speaker: 's1', text: 'And if you were cool like me and you had a creative zen, right, then everything was .WAV. And, basically, you couldn\'t play WAV on Apple and you couldn\'t play AIFF on Windows. Now, these days, that\'s changed quite a bit. So, on a Mac, for sure, you can play anything.' },
      { t: '29:41', speaker: 's1', text: 'For sure, you can play any file format. On Windows, generally speaking, you can also play any file format. That said, my personal experience is that a lot of people who work with Windows who are not computer savvy generally don\'t update their computers very often.' },
      { t: '29:56', speaker: 's1', text: 'Which means that you will, like, sometimes have a colleague who\'s like, hey, I couldn\'t open up this file. And you\'re like, wait, what year is your computer from? Oh, 2007. Right? So, that\'s just something to be aware of. Generally, you shouldn\'t have to worry about that distinction.' },
      { t: '30:12', speaker: 's1', text: 'Until you do.' },
      { t: '30:14', speaker: 's1', text: 'In any case, then we have compressed file formats. So, the idea here being compressed file formats are going to reduce file size at the expense of storage space. And then, along with that, we have two subcategories. Lossless and lossy file formats.' },
      { t: '30:30', speaker: 's1', text: 'So, I don\'t like lossy. I think that sounds like something someone made up. Right? Even more than things are generally made up. But, in any case. So, compressed lossless formats basically differ in terms of how they compress a file format.' },
      { t: '30:43', speaker: 's1', text: 'So, for example. Something like a Microsoft Word document. Or even, let\'s say, like the original Keynote document for these slides. So, is the original Keynote document remembering every single pixel for every single letter in the word audio?' },
      { t: '31:00', speaker: 's1', text: 'As well as the RGBA values for just the letter A and just the letter U and every single pixel within it? No. It\'s absolutely not doing that. Because that would be crazy. That would be a very inefficient use of space. And what it is remembering, though, is it\'s remembering that it gets a chunk of code that says, Okay, this section contains this text within this bullet point.' },
      { t: '31:21', speaker: 's1', text: 'And we are using this font. So, reference this file somewhere on the computer that has this font. Reference this thing that has these RGBA values that we associate with these colors. And so on and so forth. Basically making a digital shorthand for all of this information.' },
      { t: '31:35', speaker: 's1', text: 'Right? That is on the slide. It\'s basically the same thing for FLAC. Is that it finds ways to take chunks of the audio and create a digital shorthand for it. And so, up until recently, you couldn\'t actually just play FLAC files outright.' },
      { t: '31:52', speaker: 's1', text: 'You would have to actually go through a conversion process to undo that digital shorthand. These days, at least on Mac, you can generally play FLAC files right away without having to convert them. So, that was the big disadvantage to those in the original.' },
      { t: '32:05', speaker: 's1', text: 'So, FLAC files, I will say, I don\'t see them very often outside of, like, Bandcamp, generally speaking. Or, I\'m sure none of you guys have ever pirated music in your lifetime. But, like, if you have a friend who\'s, like, a deviant, right, who does, like, you might notice they have lots of FLAC files.' },
      { t: '32:23', speaker: 's1', text: 'Right? Because surely no one spends that much money on Bandcamp. In any case, these are compressed lossless file formats.' },
      { t: '32:31', speaker: 's1', highlight: true, text: 'Now, next we have compressed lossy file formats. So, this means that not only is the storage space reduced, but it is being reduced permanently. So, basically, you cannot go back to the original full quality from that particular file format.' },
      { t: '32:47', speaker: 's1', text: 'So, how many people have heard of MP3? Yeah, surely all of you at some point, right? How many people have heard of an MP3 player? Yeah, you\'ve probably heard of that as, like, a thing that used to exist. There was, like, an iPhone that only played music?' },
      { t: '33:01', speaker: 's1', text: 'That\'s wild, right? So, in any case. Basically, this was the idea behind the MP3s was to make it small enough so that you could fit a lot of music on your computer or, better yet, on your iPod. And if you\'re listening to these tiny little earbud headphones, it generally doesn\'t matter how good the quality is overall, right?' },
      { t: '33:17', speaker: 's1', text: 'You just want to get the gist of it and be able to, like, listen to music while you\'re running or walking or plug it into your car or whatever that might be, right? Now, there are some other formats you might see. So, M4A is basically, like, Apple\'s proprietary, like, kind of format that\'s similar to MP3.' },
      { t: '33:32', speaker: 's1', text: 'Except it\'s... I don\'t know why you bought it with M4A, but just worth noting that that, along with AAC, which is kind of like an older version of M4A, are basically Apple-based compressed lossy formats. Now, along with that, how many people have seen OGG files at some point or another?' },
      { t: '33:50', speaker: 's1', text: 'Yeah, so where have you guys seen OGG files?' },
      { t: '33:53', speaker: 's2', text: 'I see a lot, like, relations with new games?' },
      { t: '33:56', speaker: 's1', text: 'Yeah, exactly. So, this is, like, a compression format that\'s used a lot for game development in particular is OGG, right? Yeah. So, but again, basically the idea here being that we are compressing these file formats and we\'re not able to retrieve them, but the result is we have something that\'s a smaller file format that we\'re able to listen to immediately,' },
      { t: '34:15', speaker: 's1', text: 'Whether that\'s because it\'s something that we\'re streaming off of Spotify or something that\'s, like, an asset in a game that we\'re trying to have the code reference for whenever you, like, I don\'t know, like, chop off someone\'s head in Elden Ring or something, right?' },
      { t: '34:29', speaker: 's1', text: 'So, along with that, though, there are differences. So, there are different bit rates for lossy file formats, particularly MP3, that are going to impact the sound quality. So, in this case, the bit rate is how much information is actually being sent per second in order to convey those particular sounds.' },
      { t: '34:47', speaker: 's1', text: 'So, just go ahead and get those, these sound examples. For whatever reason, my AirDrop has chosen today not to cooperate. For some reason, this computer seems to be running. All right, so what I have for you is a series of excerpts of Mahler.' },
      { t: '35:51', speaker: 's1', text: 'So, not necessarily my favorite composer. For those of you who are big classical music heads, might actually be your favorite composer. He\'s many, many people\'s favorite. But in any case, what we\'re going to do is we\'re going to listen to the same orchestral excerpt, but we\'re going to listen to different bit depths and then also MP3s at different bit rates.' },
      { t: '36:09', speaker: 's1', text: 'So, we\'re going to start with, this is an AIF file. And this is at 24-bit. All right, so how does that sound? Pretty good? Sound like an orchestra? Sounds like a pretty good orchestra? And a pretty good hall? Right? And so, now we\'re going to go from 24 bits to 16 bits.' },
      { t: '36:58', speaker: 's1', text: 'So, if we remember, this is going to be the difference between 16 million steps of quantization versus 65,000 steps of quantization. Dynamic range of 144 decibels versus 96 decibels. So, Mahler. At 16 bits. All right, so how does this sound?' },
      { t: '37:48', speaker: 's1', text: 'Yep.' },
      { t: '37:49', speaker: 's2', text: 'I think it sounds pretty similar, but during some of the louder parts, I guess I hear more noise that shouldn\'t be there.' },
      { t: '37:57', speaker: 's1', text: 'Yep. Anyone else hear any big differences? Yep. Oh, like the low end was a little bit muddier on that? A little muddier? Yep. Awesome. How many people didn\'t really, honestly could not tell much of a difference? Yeah, and if you did not tell much of a difference, also don\'t feel bad, because it\'s, at this step, it\'s, there are differences you can pick out, but if you can\'t pick them out, that doesn\'t mean you\'re, like, have a bad ear.' },
      { t: '38:25', speaker: 's1', text: 'It\'s just, it\'s pretty subtle at this point, right? So, for a while, 16 bit was considered totally fine for digital audio, until we got to 24 bit, and that\'s been a standard for a long time. But in any case, 16 bit\'s kind of like a minimum to sound decent, more or less.' },
      { t: '38:39', speaker: 's1', text: 'So, now we\'re going to go down to 8 bit. So, how many steps of quantization is 8 bit? So, what\'s 2 to the power of 8? So, 2 times 2 is 4, times 2 is, times 2 is, times 2 is, times 2 is, times 2 is, times 2 is, times 2 is, 256. So, 256 steps, right?' },
      { t: '39:08', speaker: 's1', text: 'So, 256, notable for being much less than 65,000, right? So, let\'s see what Mahler at 8 bit sounds like. Alright, so, sounds fine, right? No. No, so there\'s a, there\'s a problem here. What\'s the problem? Yep.' },
      { t: '39:55', speaker: 's2', text: 'It\'s a lot of static.' },
      { t: '39:56', speaker: 's1', text: 'Yeah.' },
      { t: '39:57', speaker: 's2', text: 'Especially the lower notes from here.' },
      { t: '39:59', speaker: 's1', text: 'Yeah, exactly. We get all this quantization noise. So, it\'s like, it\'s a staticky sound, but it\'s even, like... Every time there\'s a, like, an attack transient, we kind of hear it going... It\'s like this, again, nasty, squishy type of digital sound, like a squishy computer.' },
      { t: '40:14', speaker: 's1', text: 'Yeah, that doesn\'t sound fun, right? But, again, value judgments, right? Maybe there\'s a time and place for 8 bit quantized Mahler, but that\'s the result, right? We get something that\'s not really usable because we get all this extra squishy, staticky type of noise.' },
      { t: '40:29', speaker: 's1', text: 'Now, from here, we\'re going to go from Mahler at 24 bit AIF. So, this was all lossless here up until now. And we\'re going to go to the MP3. So, let\'s start by listening again to AIF. Listen to MP3 at 320 kilobytes per second.' },
    ],
  },
}

/** 按文件名查转录；未命中返回 null。 */
export function lookupTranscript(fileName: string): AudioTranscript | null {
  return TRANSCRIPTS[fileName.toLowerCase()] ?? null
}

/** m:ss / h:mm:ss → 秒，用于点击分段跳转播放器。 */
export function parseTimestamp(ts: string): number {
  const parts = ts.split(':').map((n) => parseInt(n, 10))
  if (parts.some((n) => Number.isNaN(n))) return 0
  return parts.reduce((acc, n) => acc * 60 + n, 0)
}
