// Pure function, **does not import `vue-i18n`** (same division as `channelsFormat.ts`/
// `mcpConnect.ts`: extracting as pure functions decouples from vue-i18n unit testing, copy is generated by caller's t()).
//
// The backend output coordinates that these three functions align with are all in `NimoOS-AI/service/skills.go`:
//   - `triggerLabel` aligns with `manifestToSkill` trigger→trigger_human mapping
//     (skills.go:191-199, `"auto"→"Automatic"` / `"slash"→"/"+name` / `"manual"→"Manual"`).
//   - `authorLabel` aligns with `manifestToSkill` author fallback (skills.go:184-190,
//     when user skill has no explicit author, backend fills literal `"You"`).
//   - `fileSizeLabel` aligns with `humanSize`/`listBundleFiles` (skills.go:138-148,
//     folders in the file list display as `"(N files)"`, count of internal items not byte count).
//
// **The interface never echoes raw backend text** — same pattern as `channelsFormat.addBotErrorKey`: the
// English literals from the backend are used only as "keys" to match against; when matched, always return
// the localized i18n key to the caller's t(); when unrecognized, return `null` to let the caller display
// the raw string as fallback (the backend may still output new trigger/author values the UI cannot recognize,
// in which case null lets the caller show the raw text as fallback, rather than throwing or dropping it).

export interface LabelRef {
  key: string
  params?: Record<string, unknown>
}

/** Align with Vue2 `trigger_human` semantics, but input is the raw `trigger` enum + skill `name`
 *  (common constraint §3 deviation 4: this repo deprecated the backend-computed `trigger_human` string,
 *  maps by enum ourselves). `'manual'` reuses `aiSkTagManual` (left sidebar "Manual" short tag) — in Vue2
 *  slash/manual have only one "Manual" copy, no duplicate key created. Unknown trigger returns `null`,
 *  caller displays raw string as fallback. */
export function triggerLabel(trigger: string, name: string): LabelRef | null {
  switch (trigger) {
    case 'auto':
      return { key: 'aiSkTriggerAutomatic' }
    case 'slash':
      return { key: 'aiSkTriggerSlash', params: { name } }
    case 'manual':
      return { key: 'aiSkTagManual' }
    default:
      return null
  }
}

/** The backend hardcodes the default value for "user creates new skill without explicit author"
 *  as literal `"You"` (skills.go:188). Only this one value needs localization — other values are
 *  real names / system author data, display as-is, return `null`. */
export function authorLabel(author: string): LabelRef | null {
  if (author === 'You') return { key: 'aiSkAuthorYou' }
  return null
}

/** Backend file entry size field is strings like `"(N files)"` / `"(1 file)"` (skills.go:175
 *  `"(" + itoaSkill(len(subs)) + " files)"`, plural/singular is concatenated by backend, this
 *  concatenation never produces singular form "file" but regex is fault-tolerant compatible).
 *  **Regular file `"12 B"` / `"1.0 KB"` / `"1.0 MB"` byte units pass through as-is**, return `null`. */
export function fileSizeLabel(size: string): LabelRef | null {
  const m = /^\((\d+) files?\)$/.exec(size)
  if (!m) return null
  return { key: 'aiSkNFiles', params: { n: Number(m[1]) } }
}
