/**
 * Timezone table copied verbatim from Vue2 SettingsPanel.vue L871-933 (same order,
 * same label text, same values).
 * Labels are English source text and **not put through i18n** -- Vue2 has no $t()
 * there either; keeping both UIs visually identical takes priority.
 * Do not "optimize" the order into GMT sorting: Vue2 uses exactly this order, 1:1 UI.
 */
export interface TimezoneOption { label: string; value: string }
export const TIMEZONES: readonly TimezoneOption[] = [
  { label: '(GMT-12:00) International Date Line West', value: 'Etc/GMT+12' },
  { label: '(GMT-11:00) Coordinated Universal Time-11', value: 'Pacific/Pago_Pago' },
  { label: '(GMT-10:00) Hawaii', value: 'Pacific/Honolulu' },
  { label: '(GMT-09:00) Alaska', value: 'America/Anchorage' },
  { label: '(GMT-08:00) Pacific Time (US & Canada)', value: 'America/Los_Angeles' },
  { label: '(GMT-07:00) Mountain Time (US & Canada)', value: 'America/Denver' },
  { label: '(GMT-07:00) Arizona', value: 'America/Phoenix' },
  { label: '(GMT-06:00) Central Time (US & Canada)', value: 'America/Chicago' },
  { label: '(GMT-06:00) Mexico City', value: 'America/Mexico_City' },
  { label: '(GMT-05:00) Eastern Time (US & Canada)', value: 'America/New_York' },
  { label: '(GMT-05:00) Bogota, Lima, Quito', value: 'America/Bogota' },
  { label: '(GMT-04:00) Atlantic Time (Canada)', value: 'America/Halifax' },
  { label: '(GMT-04:00) Caracas, La Paz', value: 'America/Caracas' },
  { label: '(GMT-03:30) Newfoundland', value: 'America/St_Johns' },
  { label: '(GMT-03:00) Brasilia', value: 'America/Sao_Paulo' },
  { label: '(GMT-03:00) Buenos Aires, Georgetown', value: 'America/Argentina/Buenos_Aires' },
  { label: '(GMT-02:00) Coordinated Universal Time-02', value: 'Etc/GMT+2' },
  { label: '(GMT-01:00) Azores', value: 'Atlantic/Azores' },
  { label: '(GMT-01:00) Cape Verde Is.', value: 'Atlantic/Cape_Verde' },
  { label: '(GMT+00:00) UTC', value: 'UTC' },
  { label: '(GMT+00:00) London, Dublin, Lisbon', value: 'Europe/London' },
  { label: '(GMT+01:00) Amsterdam, Berlin, Paris, Rome', value: 'Europe/Paris' },
  { label: '(GMT+01:00) Warsaw, Prague, Budapest', value: 'Europe/Warsaw' },
  { label: '(GMT+01:00) West Central Africa', value: 'Africa/Lagos' },
  { label: '(GMT+02:00) Athens, Bucharest, Istanbul', value: 'Europe/Athens' },
  { label: '(GMT+02:00) Cairo', value: 'Africa/Cairo' },
  { label: '(GMT+02:00) Jerusalem', value: 'Asia/Jerusalem' },
  { label: '(GMT+02:00) Harare, Pretoria', value: 'Africa/Johannesburg' },
  { label: '(GMT+03:00) Moscow, St. Petersburg', value: 'Europe/Moscow' },
  { label: '(GMT+03:00) Kuwait, Riyadh', value: 'Asia/Riyadh' },
  { label: '(GMT+03:00) Nairobi', value: 'Africa/Nairobi' },
  { label: '(GMT+03:30) Tehran', value: 'Asia/Tehran' },
  { label: '(GMT+04:00) Abu Dhabi, Muscat', value: 'Asia/Dubai' },
  { label: '(GMT+04:00) Baku, Tbilisi, Yerevan', value: 'Asia/Baku' },
  { label: '(GMT+04:30) Kabul', value: 'Asia/Kabul' },
  { label: '(GMT+05:00) Ekaterinburg', value: 'Asia/Yekaterinburg' },
  { label: '(GMT+05:00) Islamabad, Karachi, Tashkent', value: 'Asia/Karachi' },
  { label: '(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi', value: 'Asia/Kolkata' },
  { label: '(GMT+05:45) Kathmandu', value: 'Asia/Kathmandu' },
  { label: '(GMT+06:00) Almaty, Novosibirsk', value: 'Asia/Almaty' },
  { label: '(GMT+06:00) Astana, Dhaka', value: 'Asia/Dhaka' },
  { label: '(GMT+06:30) Yangon (Rangoon)', value: 'Asia/Rangoon' },
  { label: '(GMT+07:00) Bangkok, Hanoi, Jakarta', value: 'Asia/Bangkok' },
  { label: '(GMT+07:00) Krasnoyarsk', value: 'Asia/Krasnoyarsk' },
  { label: '(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi', value: 'Asia/Shanghai' },
  { label: '(GMT+08:00) Kuala Lumpur, Singapore', value: 'Asia/Singapore' },
  { label: '(GMT+08:00) Taipei', value: 'Asia/Taipei' },
  { label: '(GMT+08:00) Perth', value: 'Australia/Perth' },
  { label: '(GMT+09:00) Tokyo, Osaka, Sapporo', value: 'Asia/Tokyo' },
  { label: '(GMT+09:00) Seoul', value: 'Asia/Seoul' },
  { label: '(GMT+09:00) Yakutsk', value: 'Asia/Yakutsk' },
  { label: '(GMT+09:30) Darwin', value: 'Australia/Darwin' },
  { label: '(GMT+09:30) Adelaide', value: 'Australia/Adelaide' },
  { label: '(GMT+10:00) Sydney, Melbourne, Brisbane', value: 'Australia/Sydney' },
  { label: '(GMT+10:00) Vladivostok', value: 'Asia/Vladivostok' },
  { label: '(GMT+10:00) Guam, Port Moresby', value: 'Pacific/Guam' },
  { label: '(GMT+11:00) Magadan, Solomon Is., New Caledonia', value: 'Asia/Magadan' },
  { label: '(GMT+12:00) Auckland, Wellington', value: 'Pacific/Auckland' },
  { label: '(GMT+12:00) Fiji, Kamchatka, Marshall Is.', value: 'Pacific/Fiji' },
  { label: "(GMT+13:00) Nuku'alofa", value: 'Pacific/Tongatapu' },
  { label: '(GMT+14:00) Kiritimati', value: 'Pacific/Kiritimati' },
] as const
