// 文件扩展名分类的单一真源(供 icons.ts 图标映射 + panelMap.ts 查看器映射复用)
export const IMAGE_X_GENERIC = ['png', 'jpg', 'jpeg', 'bmp', 'gif', 'webp', 'svg', 'tiff']
export const VIDEO_X_GENERIC = ['mkv', 'mp4', '3gp', 'avi', 'm2ts', 'webm', 'flv', 'vob', 'ts', 'mts', 'mov', 'wmv', 'rm', 'rmvb', 'asf', 'mpg', 'm4v', 'mpeg', 'f4v']
export const AUDIO_X_GENERIC = ['aac', 'aiff', 'alac', 'amr', 'ape', 'flac', 'm4a', 'mp3', 'ogg', 'opus', 'wma', 'wav']
export const TEXT_X_GENERIC = ['txt', 'log', 'pages', 'conf', 'config', 'list', 'ini', 'toml', 'cfg', 'rc', 'env', 'service', 'conf.d', 'htaccess', 'gitconfig', 'vim', 'curlrc', 'wgetrc', 'gitignore']
export const TEXT_MARKDOWN = ['md']
export const TEXT_CSS = ['php', 'css', 'less', 'scss', 'sass', 'aspx', 'lua', 'vue', 'js', 'go', 'asp', 'bat', 'c', 'cpp', 'cs', 'json', 'py', 'perl', 'sh', 'xml', 'yaml', 'vb', 'vbs', 'sql', 'swift', 'rust', 'rs', 'jsp', 'yml', 'r', 'pl', 'rb', 'src', 'h', 'tex', 'rtf', 'jsonld', 'ttl', 'n3', 'rss', 'atom', 'srt', 'ass', 'tsv', 'vcard', 'asc', 'url', 'diff', 'plaintext']
export const TEXT_HTML = ['html', 'htm', 'shtml', 'shtm']
export const APPLICATION_VND_MS_WORD = ['doc', 'docx', 'wps']
export const APPLICATION_VND_MS_EXCEL = ['xls', 'xlsx', 'csv']
export const APPLICATION_VND_MS_POWERPOINT = ['ppt', 'pptx']
export const APPLICATION_PDF = ['pdf']
export const APPLICATION_PHOTOSHOP = ['psd', 'psb']
export const APPLICATION_ILLUSTRATOR = ['ai', 'eps']
export const APPLICATION_X_WINE_EXTENSION_CPL = ['exe']
export const APPLICATION_APK = ['apk']
export const APPLICATION_X_ZIP = ['zip', 'rar', '7z', 'gz', 'ace', 'xz']
export const APPLICATION_X_CD_IMAGE = ['iso', 'img', 'vmdk', 'raw', 'vhd']
export const APPLICATION_X_APPLE = ['dmg', 'ipa', 'pkg']
export const APPLICATION_X_PEM_KEY = ['pem', 'crt', 'ca-bundle', 'p7b', 'p7s', 'der', 'cer', 'pfx', 'p12']
export const TEXT_X_CMAKE = ['makefile', 'cmake', 'dockerfile']
export const TEXT_DOCKERFILE = ['dockerfile']
// 播放白名单(Vue2 mixin.js:33-40)——视频图标覆盖更广(见 VIDEO_X_GENERIC),但播放器只认这 5 个
export const BROWSER_PLAYABLE_VIDEO = ['mp4', 'm4v', 'webm', 'mov', '3gp']
