// SP8-P5c Task 6 — component test for `ParserStatus.vue`.
// Blueprint: `NimoOS-UI` (main@7a6ee6b7) `src/views/AI/Parser/ParserStatus.vue` (164 lines).
//
// ═══ mock strategy (governance §4.1 requires explicit documentation) ═══
// 🔴 **mock shared package `service.ai.parser*`, use real `parserStore` (T5 output)**, do not mock store.
//   Reason: all page data must pass through `parserStore`'s K1 downlayering (blueprint `store.state.xxx` →
//   this repo `store.xxx`) and N7 fallback. Mocking store avoids testing the most-easy-to-break "does downlayering
//   and field names actually match" part; using real store makes every render assertion naturally an integration test —
//   template missing one `.state.` layer or field name off by one letter immediately shows as empty/undefined.
//   Cost is each test needs `flushPromises()` waiting for all four `Promise.all` completions, acceptable.
// 🔴 All six `service.ai.parser*` methods in package only do `return res.data` (`NimoOS-Service/src/ai.ts:591-620`, zero transformation)
//   → mock them here as **raw HTTP snake_case**, matching fixture literally. **Must have identical shapes across
//   `parserStore.test.ts` / `knowledgeStore.parser.test.ts`** (governance §4.1 red flag self-check: same method
//   mocked differently in two test files = time bomb, §8.3 has precedent). `parserControl` also mocked to `{}`, consistent
//   with those two files.
//
// ═══ fixtures are copies, not runtime reads (governance §4.4) ═══
// Data copied verbatim into `FIXTURE-COPY-BEGIN/END` blocks below with citations,
// **do not read `.superpowers/` with `node:fs`** — that directory is gitignored (SP7 lost it entirely),
// this branch will merge to master; tests in `src/` with cross-boundary dependencies silently fail with
// "file not found". 🔴 Copy generated by one-time script from fixtures (zero hand transcription),
// equivalence verified by **automated byte-for-byte validation** (output in T6 report §4) — not visual comparison.
// Reading `.vue` source files (guard gaps③ those two) still uses `node:fs`, **never Vite's `?raw`**
//   (vitest's CSSEnablerPlugin replaces style source with empty string → assertions "pass" on empty string;
//    precedent: `knowledgeStyles.test.ts` comment③).
//
// ═══ boolean attribute assertion calibration (governance §9) ═══
// `:checked` / `:disabled` are **boolean attributes**: Vue renders `disabled=""` (empty string) when true,
// omits attribute when false → `attributes('disabled')` false side can only be `undefined`, but governance §9
// **forbids `toBeUndefined()`**. So assert **DOM properties** always (`el.disabled` / `el.checked`),
// which are naturally true/false comparable values, **both sides**. Other text/href: compare as strings directly.
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import { nextTick } from 'vue'
import { setActivePinia, createPinia } from 'pinia'
import { createRouter, createWebHashHistory } from 'vue-router'
import { i18n } from '../../../i18n'
import zhCn from '../../../i18n/zh_cn'
import ParserStatus from './ParserStatus.vue'
import type {
  ParserStatsBody,
  ParserControlStateBody,
  ParserFoldersBody,
  ParserFailedJob,
} from '../stores/parserStore'
import { readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

// ── vi.hoisted mock skeleton (governance §9: avoid ESM hoisting TDZ) ──
const ai = vi.hoisted(() => ({
  parserStats: vi.fn(),
  parserState: vi.fn(),
  parserFolders: vi.fn(),
  parserJobs: vi.fn(),
  parserControl: vi.fn(),
}))
vi.mock('@nimotech/nimoos-service', () => ({ service: { ai } }))

// ═══════════════════════════════════════════════════════════════════════════
// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-stats.json  (complete, GET /v1/parser/stats)
// From `.superpowers/sdd/p5c-fixtures/parser-stats.json` (real device capture 2026-08-03 13:22).
// Real device measured values per governance §4.3: pending 339 / running 1 / failed 0 / done 9 ·
// total_vectors_text 5592 · last_cursor_ms 1784775953391.
const STATS: ParserStatsBody = {
  "queue_depth": {
    "pending": 339,
    "running": 1,
    "failed": 0,
    "done": 9
  },
  "indexed_files": 7,
  "total_vectors_text": 5592,
  "total_vectors_visual": 0,
  "last_cursor_ms": 1784775953391,
  "models": [
    {
      "name": "bge-m3",
      "version": "v1",
      "modality": "text",
      "dim": 1024
    },
    {
      "name": "bge-reranker-v2-m3",
      "version": "v1",
      "modality": "rerank",
      "dim": null
    }
  ]
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-control-state.json  (complete, GET /v1/parser/state)
// From `.superpowers/sdd/p5c-fixtures/parser-control-state.json` (2026-08-03 13:22).
// 🔴 Device is currently in **paused state** (governance §4.3) → light is `.paused`, button is "▶ Resume".
// "Running / green light / ⏸ Paused" state not visible on this device, covered by fixture variants below.
const STATE: ParserControlStateBody = {
  "paused": true,
  "concurrency": 2,
  "device": "auto",
  "ocr_enabled": false,
  "resolved_device": "cpu"
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-folders-pending-20.json  (complete 20 items + total_groups)
// From `.superpowers/sdd/p5c-fixtures/parser-folders-pending-20.json` (2026-08-03 13:22,
// `GET /v1/parser/folders?limit=20`). 🔴 **all 20 items copied**, fields (`root_id`/`folder`/`count`)
// no simplification, order unchanged. First item count 18 = max value (barWidth 100% baseline), last item 4.
const FOLDERS: ParserFoldersBody = {
  "folders": [
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/.github/workflows","count":18},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/projects/-home-nimo-NimoTech/9c3e7a5c-f2fc-409c-9ca3-7f46a47e1d81/subagents","count":16},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/.docker/containers/26be4bc607290dbbc955a0f5f1f1317d7a5b55df87ccdd86e9987ca8440c7ea1","count":15},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/opt/qdrant/storage/collections/text_chunks","count":12},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/tmp","count":11},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude","count":11},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/external_plugins/discord","count":10},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/external_plugins/imessage","count":10},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/external_plugins/fakechat","count":8},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/opt/qdrant/storage/collections/visual_chunks","count":8},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/plugins/claude-security/agents","count":7},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins","count":6},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/.github/scripts","count":6},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/external_plugins/telegram","count":5},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/plugins/claude-code-setup/skills/claude-automation-recommender/references","count":5},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/opt/qdrant/storage/collections/text_chunks/0","count":5},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/opt/qdrant/storage/collections/visual_chunks/0","count":5},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/.docker/containers/2e55949f61fe879896fedd0334339c31d1cd962691358c56bf3ca0b03781e983","count":4},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/external_plugins/greptile","count":4},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/.docker/containers/aade3000de2889facb1f7ba7789d6f2c2fe6acdaf1a9adc7433242648d5c47e7","count":4}
  ],
  "total_groups": 119
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-jobs-failed-5.json  (complete, GET /v1/parser/jobs?status=failed&limit=5)
// From `.superpowers/sdd/p5c-fixtures/parser-jobs-failed-5.json` (2026-08-03 13:22).
// 🔴 Device failed bucket **is empty** (governance §4.3 / §13) → N19's "after opening list entirely not rendered" is **correct behavior**.
const FAILED_EMPTY: { jobs: ParserFailedJob[] } = {
  "jobs": []
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5b-fixtures/jobs-pending.json  jobs[0]  (real row, copied verbatim)
// From `jobs[0]` (id 348) of `.superpowers/sdd/p5b-fixtures/jobs-pending.json`.
// 🔴 Why borrow a row from pending bucket: device failed bucket measured empty, but `/v1/parser/jobs` is same table,
// same serializer, row shape independent of status → borrow it as real row for N19 "non-empty bucket" two states.
// **Precedent: `parserStore.test.ts` `FAILED_ROW` and `knowledgeStore.staleGuard.test.ts` `POISON_FAILED_ROW`
// same approach** (T3 fix round 1 M-2 approved). Fields unchanged.
const FAILED_ROW: ParserFailedJob = {
  "id": 348,
  "root_id": "dfcd1840f5dab439cd9d7050aa5bafd0",
  "path": "/DATA/.system_data/tmp/nimoos_panic.log",
  "op": "index",
  "sub_modality": null,
  "priority": 100,
  "attempts": 0,
  "last_error": null,
  "locked_until": null,
  "created_at": 1784776422853,
  "picked_at": null,
  "done_at": null
}
// FIXTURE-COPY-END
// ═══════════════════════════════════════════════════════════════════════════

/** All four calls succeed, all fed with fixture raw text. */
function mockAllOk(): void {
  ai.parserStats.mockResolvedValue(STATS)
  ai.parserState.mockResolvedValue(STATE)
  ai.parserFolders.mockResolvedValue(FOLDERS)
  ai.parserJobs.mockResolvedValue(FAILED_EMPTY)
  // `parserControl` response body not consumed by this page (blueprint just `await`s all five actions);
  // shape consistent with `parserStore.test.ts:207` / `knowledgeStore.parser.test.ts:136`.
  ai.parserControl.mockResolvedValue({})
}

function deferred<T>() {
  let resolve!: (v: T) => void
  let reject!: (e: unknown) => void
  const promise = new Promise<T>((res, rej) => {
    resolve = res
    reject = rej
  })
  return { promise, resolve, reject }
}

// Each test's mounted wrapper unified unmount in afterEach — this page's `onMounted` starts a real
// `setInterval(…, 5000)` (N20), not unmounting leaks timers and store refs to other tests
// (precedent `QueueView.test.ts:162-167` same scaffolding, that one polls every 10 seconds).
const mountedWrappers: Array<ReturnType<typeof mount>> = []

function makeRouter() {
  const router = createRouter({
    history: createWebHashHistory('/app/'),
    routes: [
      { path: '/ai/parser', name: 'AIParser', component: ParserStatus },
      // 蓝本 `:6` 的 `router-link to="/ai/parser/test"` 需要目标路由存在才能解析出 href。
      // 【订正,SP8-P5d Task 9,治理 §15.2 / 计划书 §T9 第 6 条】上一条注释双重过期:
      // ① 说「生产环境这条路由此刻仍指占位页」——生产里这条路由早已反转成真正的
      // ParserTest(P5c-T10 的产出,knowledgeRoutes.ts 头注释有完整记录);
      // ② 它引的行号也早漂了。这里的 stub 组件只是本测试文件自己路由表里的占位,
      // 与生产路由是否占位无关——保留 stub 是因为本文件只关心 href 能否解析出来,
      // 不关心 `/ai/parser/test` 页面本身渲染什么。
      { path: '/ai/parser/test', name: 'AIParserTest', component: { template: '<div />' } },
    ],
  })
  router.push('/ai/parser')
  return router
}

/** 挂载但**不 flush** —— 用于观察「四发在飞时」的 `loading` 档。 */
async function mountRaw() {
  const router = makeRouter()
  await router.isReady()
  const w = mount(ParserStatus, { global: { plugins: [router, i18n] } } as never)
  mountedWrappers.push(w)
  return w
}

/** 挂载并等四发落地。 */
async function mountPage() {
  const w = await mountRaw()
  await flushPromises()
  await nextTick()
  return w
}

beforeEach(() => {
  setActivePinia(createPinia())
  vi.clearAllMocks()
  mockAllOk()
})

afterEach(() => {
  while (mountedWrappers.length) mountedWrappers.pop()!.unmount()
  document.body.innerHTML = ''
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus — K31 two-layer root element (scroll container + 900px centered column)', () => {
  // 🔴 Governance §3 K31: `.parser-app` is **outer wrapper**, page root class `.parser-status-page` is **inner**.
  // Squashing into one element puts the `overflow-y:auto` scrollbar at the right edge of the 900px centered column
  // (roughly screen center on wide screens), whereas Vue2 scrolls the whole page with scrollbar at viewport's right edge
  // = user-visible interface not 1:1. Test criterion: rewrite two classes back into one element → both tests must fail.
  it('root element only has .parser-app (not .parser-status-page)', async () => {
    const w = await mountPage()
    const root = w.element as HTMLElement
    expect(root.tagName).toBe('DIV')
    expect(root.className).toBe('parser-app')
    expect(root.classList.contains('parser-status-page')).toBe(false)
  })

  it('.parser-status-page is direct child of .parser-app, and exactly one of each', async () => {
    const w = await mountPage()
    expect(w.findAll('.parser-app')).toHaveLength(1)
    expect(w.findAll('.parser-status-page')).toHaveLength(1)
    expect(w.find('.parser-app > .parser-status-page').exists()).toBe(true)
    // Page content is actually in inner layer (not empty shell)
    expect(w.find('.parser-status-page > .page-header').exists()).toBe(true)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus —— 页头(蓝本 :3-9)', () => {
  it('标题 / 🧪 测试沙盒链接(含 href)/ 刷新按钮的文案逐字', async () => {
    const w = await mountPage()
    expect(w.find('.page-header h2').text()).toBe('Parser 详情')
    const link = w.find('a.test-link')
    // N16:🧪 在 t() 外面 —— 渲染成「🧪 测试沙盒」(emoji + 空格 + 译文)
    expect(link.text()).toBe('🧪 测试沙盒')
    // hash 路由:jsdom 里 location 是 `http://localhost:3000/`,`createWebHashHistory('/app/')`
    // 解析出的 href 就是纯 hash(生产环境浏览器地址栏里是 `…/app/#/ai/parser/test`)
    expect(link.attributes('href')).toBe('#/ai/parser/test')
    expect(w.find('.refresh-btn').text()).toBe('刷新')
  })

  it('挂载即拉一次(四发各一次,参数照蓝本)', async () => {
    await mountPage()
    expect(ai.parserStats).toHaveBeenCalledTimes(1)
    expect(ai.parserState).toHaveBeenCalledTimes(1)
    expect(ai.parserFolders).toHaveBeenCalledWith({ limit: 20 })
    expect(ai.parserJobs).toHaveBeenCalledWith({ status: 'failed', limit: 5 })
  })

  it('点刷新按钮 → 再拉一次(蓝本 reload() :137)', async () => {
    const w = await mountPage()
    await w.find('.refresh-btn').trigger('click')
    await flushPromises()
    expect(ai.parserStats).toHaveBeenCalledTimes(2)
    expect(ai.parserFolders).toHaveBeenCalledTimes(2)
  })

  it('🔴 :disabled="loading" 两侧 —— 四发在飞时刷新按钮 + 三档单选 + OCR 勾选框全禁用,落地后全解禁', async () => {
    const d = deferred<ParserStatsBody>()
    ai.parserStats.mockReturnValue(d.promise)
    const w = await mountRaw()
    await nextTick()

    const btn = () => w.find('.refresh-btn').element as HTMLButtonElement
    const inputs = () => w.findAll('.control-card input').map((n) => n.element as HTMLInputElement)
    // 在飞:loading 已同步置真(`parserStore.ts:161` 在 await 之前)
    expect(btn().disabled).toBe(true)
    expect(inputs()).toHaveLength(7) // 3 并发 + 3 设备 + 1 OCR
    expect(inputs().every((el) => el.disabled === true)).toBe(true)

    d.resolve(STATS)
    await flushPromises()
    await nextTick()
    expect(btn().disabled).toBe(false)
    expect(inputs().every((el) => el.disabled === false)).toBe(true)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus —— unreachable 两态(蓝本 :11-14)', () => {
  it('四发全成功 → 不出警示卡,四张卡都在', async () => {
    const w = await mountPage()
    expect(w.find('.card.unreachable').exists()).toBe(false)
    expect(w.find('.control-card').exists()).toBe(true)
    expect(w.find('.queue-card').exists()).toBe(true)
    expect(w.find('.folders-card').exists()).toBe(true)
    expect(w.find('.failures-card').exists()).toBe(true)
  })

  it('任一发失败 → 出警示卡并把 store.error 回显在 <small> 里,四张卡整块不渲染(v-else)', async () => {
    // 蓝本 `:13` 的 `<small>{{ store.state.error }}</small>` 回显的是网络层
    // `e.message || String(e)`(`parserStore.ts:184`)—— 蓝本行为,照抄(K5/K30 不适用,
    // 它们管的是「不把后端响应 body 的 detail 拼进 toast」,不是同一件事)。
    ai.parserFolders.mockRejectedValue(new Error('parser down'))
    const w = await mountPage()
    const card = w.find('.card.unreachable')
    expect(card.exists()).toBe(true)
    expect(card.text()).toContain('Parser 服务未运行或不可达。')
    expect(card.find('small').text()).toBe('parser down')
    expect(w.find('.control-card').exists()).toBe(false)
    expect(w.find('.queue-card').exists()).toBe(false)
    expect(w.find('.folders-card').exists()).toBe(false)
    expect(w.find('.failures-card').exists()).toBe(false)
    // 页头永远在 v-if/v-else 之外
    expect(w.find('.page-header h2').text()).toBe('Parser 详情')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus —— 控制卡:状态灯 + 暂停按钮(蓝本 :19-29)', () => {
  it('本机实测 paused:true → .dot 带 paused 类、文案「已暂停」、按钮「▶ 恢复」', async () => {
    const w = await mountPage()
    const dot = w.find('.status-text .dot')
    expect(dot.classes()).toContain('paused')
    expect(w.find('.status-text').text()).toBe('已暂停')
    // N16:`▶ ` 由 script 拼接,i18n 键值是纯「恢复」
    expect(w.find('.pause-btn').text()).toBe('▶ 恢复')
  })

  it('fixture 变体 paused:false → .dot 不带 paused 类、文案「运行中」、按钮「⏸ 暂停」', async () => {
    // 只改 `paused` 这一个字段(治理 §4.3:本机是暂停态,运行档只能靠变体覆盖)
    ai.parserState.mockResolvedValue({ ...STATE, paused: false })
    const w = await mountPage()
    expect(w.find('.status-text .dot').classes()).not.toContain('paused')
    expect(w.find('.status-text').text()).toBe('运行中')
    expect(w.find('.pause-btn').text()).toBe('⏸ 暂停')
  })

  it('paused 时点按钮 → 走 resume(蓝本三元 :139-141)', async () => {
    const w = await mountPage()
    await w.find('.pause-btn').trigger('click')
    await flushPromises()
    expect(ai.parserControl).toHaveBeenCalledTimes(1)
    expect(ai.parserControl).toHaveBeenCalledWith({ action: 'resume' })
  })

  it('未暂停时点按钮 → 走 pause', async () => {
    ai.parserState.mockResolvedValue({ ...STATE, paused: false })
    const w = await mountPage()
    await w.find('.pause-btn').trigger('click')
    await flushPromises()
    expect(ai.parserControl).toHaveBeenCalledTimes(1)
    expect(ai.parserControl).toHaveBeenCalledWith({ action: 'pause' })
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus —— 控制卡:并发档(N17,蓝本 :30-40)', () => {
  it('N17 数组下标取 i18n → 三档文案顺序「省电 (1)」「平衡 (2)」「全力 (4)」', async () => {
    const w = await mountPage()
    expect(w.find('.concurrency-row > label').text()).toBe('并发档位:')
    const radios = w.findAll('.concurrency-row .radio')
    expect(radios).toHaveLength(3)
    expect(radios.map((r) => r.text())).toEqual(['省电 (1)', '平衡 (2)', '全力 (4)'])
  })

  it('🔴 :checked 两侧 —— concurrency:2 时只有第二档为 true', async () => {
    const w = await mountPage()
    const els = w.findAll('.concurrency-row input').map((n) => n.element as HTMLInputElement)
    expect(els.map((el) => el.checked)).toEqual([false, true, false])
    expect(els.map((el) => el.getAttribute('value'))).toEqual(['1', '2', '4'])
  })

  it('🔴 :checked 两侧 —— fixture 变体 concurrency:4 时只有第三档为 true', async () => {
    ai.parserState.mockResolvedValue({ ...STATE, concurrency: 4 })
    const w = await mountPage()
    const els = w.findAll('.concurrency-row input').map((n) => n.element as HTMLInputElement)
    expect(els.map((el) => el.checked)).toEqual([false, false, true])
  })

  it('@change → setConcurrency(n),载荷键是 `n`(与后端 controlReq 一致)', async () => {
    const w = await mountPage()
    await w.findAll('.concurrency-row input')[2]!.trigger('change')
    await flushPromises()
    expect(ai.parserControl).toHaveBeenCalledWith({ action: 'set_concurrency', n: 4 })
  })
})

// ═══════════════════════════════════════════════════════════════════════════
// 🔴 I-1(评审 2026-08-04 猎出的守卫缺口)—— **N21 #3 的键选纪律必须有 en 档守卫**。
//
// 评审探针:把三档并发的键换成治理**明令禁止复用**的 `aiKbCcPowerSaver` /
// `aiKbCcFullSpeed` → 上面那批用例 **47/47 全绿**。原因:那些断言只比 **zh** 文本,
// 而这两组键的 **zh 逐字撞车、只有 en 不同**:
//     aiKbPrCcPowerSaving  en `Power-saving`  zh 省电   ← 本页必须用的(T1 新建)
//     aiKbCcPowerSaver     en `Power saver`   zh 省电   ← 被禁复用的(既有)
//     aiKbPrCcFullPower    en `Full power`    zh 全力   ← 本页必须用的(T1 新建)
//     aiKbCcFullSpeed      en `Full speed`    zh 全力   ← 被禁复用的(既有)
// → 复用会让**英文界面**渲染成 `Power saver` / `Full speed`,与 Vue2 不同 = 界面不 1:1,
//   而中文界面**看不出任何差别**、三门全绿放行。这条纪律此前零守卫。
//
// **做法选型**:切 locale 到 `en_us` 真挂一次组件、断言渲染文本 —— 而不是直接读语言包
// 比键值。理由:要守的不变量是「**这一页渲染出来的英文**是 Vue2 那三串」,读键值只能证明
// 「某个键的值是什么」,证不到「模板用的是哪个键」;走渲染路径把「键选对了」与「值对了」
// 一次钉死。**并加反向断言**(不等于被禁那两个键的 en 值),这样即使将来某人把
// `aiKbCcPowerSaver` 的 en 值也改成 `Power-saving`,正向断言会绿但反向断言仍在守着
// 「渲染结果里不许出现 `Power saver`/`Full speed`」这个用户可见事实。
//
// 🔴 locale 是全局单例 → 必须 `try/finally` 还原,否则污染同文件后续用例。
describe('ParserStatus —— 🔴 I-1:N21 #3 键选纪律的 en 档强断言(zh 撞车、只有 en 能判别)', () => {
  /** `i18n.global.locale` 在 composition 模式下是 WritableComputedRef。 */
  const localeRef = i18n.global.locale as unknown as { value: string }

  async function mountInEn() {
    const prev = localeRef.value
    localeRef.value = 'en_us'
    try {
      return { w: await mountPage(), restore: () => { localeRef.value = prev } }
    } catch (e) {
      localeRef.value = prev
      throw e
    }
  }

  it('en 档三档并发标签逐字 = `Power-saving (1)` / `Balanced (2)` / `Full power (4)`', async () => {
    const { w, restore } = await mountInEn()
    try {
      expect(w.findAll('.concurrency-row .radio').map((r) => r.text())).toEqual([
        'Power-saving (1)',
        'Balanced (2)',
        'Full power (4)',
      ])
      expect(w.find('.concurrency-row > label').text()).toBe('Concurrency level:')
    } finally {
      restore()
    }
  })

  it('🔴 反向:en 档渲染结果里不许出现被禁复用键的 en 值(`Power saver` / `Full speed`)', async () => {
    const { w, restore } = await mountInEn()
    try {
      const row = w.find('.concurrency-row').text()
      expect(row).not.toContain('Power saver') // = aiKbCcPowerSaver 的 en 值
      expect(row).not.toContain('Full speed') // = aiKbCcFullSpeed 的 en 值
      // 整页范围也扫一遍(防将来别处误用)
      expect(w.text()).not.toContain('Power saver')
      expect(w.text()).not.toContain('Full speed')
    } finally {
      restore()
    }
  })

  it('切回 zh 后三档仍是「省电 (1)」/「平衡 (2)」/「全力 (4)」(证明 locale 已还原、无污染)', async () => {
    const w = await mountPage()
    expect(w.findAll('.concurrency-row .radio').map((r) => r.text())).toEqual([
      '省电 (1)', '平衡 (2)', '全力 (4)',
    ])
  })

  // 🔴 裁定 A-1(`aiKbDeviceAuto` 不许复用 `aiKbOriginAuto`)的守卫**只能落在源码上**:
  // 两个键 **en 与 zh 双双逐字相同**(`Auto` / `自动`,实测 `en_us.ts:1548` vs `:1625`、
  // `zh_cn.ts:1562` vs `:1652`)→ **任何渲染断言都没有判别力**(这也正是裁定 A-1 的理由
  // 原文:「复用渲染完全一致,但键名语义是『沉淀任务来源』,将来改沉淀文案会静默改掉
  // 设备下拉」)。故这条纪律只能靠「模板用的是哪个键」的源码断言守。
  // ⚠️ 断言必须钉「**`t()` 调用**」而不是裸子串:本文件头注释里就有一句「**不复用**
  // `aiKbOriginAuto`」的说明文字,`not.toContain('aiKbOriginAuto')` 会撞上那句注释而假报红
  // (第一版就栽了一次)—— 与治理 §9 第七/第八条那族「在文件里找某段文本撞注释」同源,
  // 这次发生在**读**侧。判据落在 `t('aiKbOriginAuto')` 这个调用形状上。
  it('🔴 A-1:设备档用 aiKbDeviceAuto,零 `t(\'aiKbOriginAuto\')` 调用(en/zh 双双同值 → 渲染断言无判别力)', () => {
    const src: string = readFileSync(resolve(__dirname, './ParserStatus.vue'), 'utf8')
    expect(src).toContain("{ value: 'auto', label: t('aiKbDeviceAuto') }")
    expect(src).not.toMatch(/\bt\(\s*['"]aiKbOriginAuto['"]/)
    // 反过来实证「为什么必须走源码」:两个键两档都同值,渲染永远分不出来
    const zh = zhCn as Record<string, string>
    expect(zh.aiKbDeviceAuto).toBe(zh.aiKbOriginAuto)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus —— 控制卡:推理设备(蓝本 :41-55)', () => {
  it('三档文案:「自动」走 i18n,「GPU (CUDA)」/「CPU」是硬编码技术标识符(不进 i18n)', async () => {
    const w = await mountPage()
    expect(w.find('.device-row > label').text()).toBe('推理设备:')
    const radios = w.findAll('.device-row .radio')
    expect(radios).toHaveLength(3)
    expect(radios.map((r) => r.text())).toEqual(['自动', 'GPU (CUDA)', 'CPU'])
    // 蓝本 `:123-124` 那两串刻意不进 i18n(N22 同族)→ 源码里是**裸字面量**,不经 t()。
    // ⚠️ 不能反过来断言「语言包里搜不到 'CPU'」—— 本仓语言包里确实另有键的值恰好是 'CPU'
    //    (硬件相关文案),那与本页无关。判据落在**本页源码怎么写的**上。
    const src: string = readFileSync(resolve(__dirname, './ParserStatus.vue'), 'utf8')
    expect(src).toContain("{ value: 'cuda', label: 'GPU (CUDA)' }")
    expect(src).toContain("{ value: 'cpu', label: 'CPU' }")
    expect(Object.values(zhCn as Record<string, unknown>)).not.toContain('GPU (CUDA)')
  })

  it('🔴 :checked 两侧 —— device:"auto" 时只有第一档为 true', async () => {
    const w = await mountPage()
    const els = w.findAll('.device-row input').map((n) => n.element as HTMLInputElement)
    expect(els.map((el) => el.checked)).toEqual([true, false, false])
    expect(els.map((el) => el.getAttribute('value'))).toEqual(['auto', 'cuda', 'cpu'])
  })

  it('🔴 :checked 两侧 —— fixture 变体 device:"cpu" 时只有第三档为 true', async () => {
    ai.parserState.mockResolvedValue({ ...STATE, device: 'cpu' })
    const w = await mountPage()
    const els = w.findAll('.device-row input').map((n) => n.element as HTMLInputElement)
    expect(els.map((el) => el.checked)).toEqual([false, false, true])
  })

  it('device=auto + resolved_device=cpu → .resolved-hint 渲染「→ 实际 CPU」(toUpperCase)', async () => {
    const w = await mountPage()
    expect(w.find('.device-row .resolved-hint').text()).toBe('→ 实际 CPU')
  })

  it('device 不是 auto 时 .resolved-hint 整个不渲染(v-if 前半)', async () => {
    ai.parserState.mockResolvedValue({ ...STATE, device: 'cpu' })
    const w = await mountPage()
    expect(w.find('.device-row .resolved-hint').exists()).toBe(false)
  })

  it('device=auto 但 resolved_device 为空串时也不渲染(v-if 后半)', async () => {
    ai.parserState.mockResolvedValue({ ...STATE, resolved_device: '' })
    const w = await mountPage()
    expect(w.find('.device-row .resolved-hint').exists()).toBe(false)
  })

  it('@change → setDevice(opt.value)', async () => {
    const w = await mountPage()
    await w.findAll('.device-row input')[1]!.trigger('change')
    await flushPromises()
    expect(ai.parserControl).toHaveBeenCalledWith({ action: 'set_device', device: 'cuda' })
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus —— 控制卡:OCR 开关(蓝本 :56-65)', () => {
  it('文案 + N21 那条错译提示逐字照抄(「真实索引的扫描件」是语言包自身的错译)', async () => {
    const w = await mountPage()
    expect(w.find('.checkbox').text()).toBe('扫描 PDF 启用 OCR (RapidOCR)')
    // 最后一行 .resolved-hint 是 OCR 提示(第一处在 .device-row 里)
    const hints = w.findAll('.control-card .resolved-hint')
    expect(hints[hints.length - 1]!.text()).toBe('慢 5-10x，只对真实索引的扫描件有用')
  })

  // 🔴 M-3(评审,2026-08-04):原本这两态挤在同一个 `it()` 里、中间换 pinia 挂第二个实例
  // —— 与本文件其余「一态一用例」的写法不一致(并发档 / 设备档都是拆开的)。已拆成两条。
  it('🔴 :checked 两侧(其一)—— 本机 ocr_enabled:false → checked 为 false', async () => {
    const w = await mountPage()
    expect((w.find('.checkbox input').element as HTMLInputElement).checked).toBe(false)
  })

  it('🔴 :checked 两侧(其二)—— fixture 变体 ocr_enabled:true → checked 为 true', async () => {
    ai.parserState.mockResolvedValue({ ...STATE, ocr_enabled: true })
    const w = await mountPage()
    expect((w.find('.checkbox input').element as HTMLInputElement).checked).toBe(true)
  })

  it('@change 从 $event.target.checked 取值 → setOcr(true) / setOcr(false)', async () => {
    const w = await mountPage()
    const box = w.find('.checkbox input')
    ;(box.element as HTMLInputElement).checked = true
    await box.trigger('change')
    await flushPromises()
    expect(ai.parserControl).toHaveBeenLastCalledWith({ action: 'set_ocr', enabled: true })
    ;(box.element as HTMLInputElement).checked = false
    await box.trigger('change')
    await flushPromises()
    expect(ai.parserControl).toHaveBeenLastCalledWith({ action: 'set_ocr', enabled: false })
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus —— 队列卡 6 格(蓝本 :68-76)', () => {
  it('六格文本逐字(N16:emoji 全在 t() 外面),数字取本机实测值', async () => {
    const w = await mountPage()
    const kvs = w.findAll('.queue-card .kv')
    expect(kvs).toHaveLength(6)
    expect(kvs.map((k) => k.text())).toEqual([
      '⏳ 待处理 339',
      '🔄 处理中 1',
      '✅ 完成 9',
      '❌ 已失败 0',
      '📦 已入向量 5592',
      // formatCursor 走 toLocaleString(),随运行环境的 locale/时区变 → 现算而不是钉死
      `📍 上次同步 ${new Date(1784775953391).toLocaleString()}`,
    ])
  })

  it('六格的数字各自落在 <b> 里(蓝本每格 `<b>{{…}}</b>`)', async () => {
    const w = await mountPage()
    const bs = w.findAll('.queue-card .kv b')
    expect(bs).toHaveLength(6)
    expect(bs.map((b) => b.text())).toEqual([
      '339', '1', '9', '0', '5592', new Date(1784775953391).toLocaleString(),
    ])
  })

  it('formatCursor(0) → U+2014 破折号(蓝本 :147 的 `if (!ms) return "—"`)', async () => {
    ai.parserStats.mockResolvedValue({ ...STATS, last_cursor_ms: 0 })
    const w = await mountPage()
    const last = w.findAll('.queue-card .kv')[5]!
    expect(last.find('b').text()).toBe('—')
    expect(last.text()).toBe('📍 上次同步 —')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus —— 文件夹卡(蓝本 :78-89)', () => {
  it('标题两个占位符各有来源:{top}=列表长度 20、{total}=后端 total_groups 119', async () => {
    const w = await mountPage()
    expect(w.find('.folders-card h3').text()).toBe('待处理文件夹（top 20 / 共 119 组）')
  })

  it('走 v-else 列表分支:20 行,每行 path + count + 进度条', async () => {
    const w = await mountPage()
    expect(w.find('.folders-card .empty').exists()).toBe(false)
    const rows = w.findAll('.folder-row')
    expect(rows).toHaveLength(20)
    expect(rows[0]!.find('.folder-path').text()).toBe(
      '/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/.github/workflows',
    )
    expect(rows[0]!.find('.folder-count').text()).toBe('18')
    expect(rows[19]!.find('.folder-count').text()).toBe('4')
  })

  it('barWidth:最大项 100%、末项 round(4/18*100)=22%', async () => {
    const w = await mountPage()
    const bars = w.findAll('.folder-bar')
    expect(bars).toHaveLength(20)
    expect(bars[0]!.attributes('style')).toBe('width: 100%;')
    expect(bars[19]!.attributes('style')).toBe('width: 22%;')
  })

  it('🔴 barWidth 的 `|| 1` 兜底:所有 count 都是 0 时宽度是 0%(不是 NaN%)', async () => {
    // 判据:去掉 `|| 1` → reduce 得 0 → 0/0 = NaN → `width: NaN%` 被 jsdom 判为无效值
    // → style 属性拿不到 'width: 0%;' → 本条报红。
    ai.parserFolders.mockResolvedValue({
      folders: [
        { root_id: 'r', folder: '/DATA/a', count: 0 },
        { root_id: 'r', folder: '/DATA/b', count: 0 },
      ],
      total_groups: 2,
    })
    const w = await mountPage()
    const bars = w.findAll('.folder-bar')
    expect(bars).toHaveLength(2)
    expect(bars[0]!.attributes('style')).toBe('width: 0%;')
    expect(bars[1]!.attributes('style')).toBe('width: 0%;')
  })

  it('v-if 空态:folders 为空 → 「无待处理」,零 .folder-row(治理 §13:本机验不到,靠 mock 覆盖)', async () => {
    ai.parserFolders.mockResolvedValue({ folders: [], total_groups: 0 })
    const w = await mountPage()
    expect(w.find('.folders-card .empty').text()).toBe('无待处理')
    expect(w.findAll('.folder-row')).toHaveLength(0)
    expect(w.find('.folders-card h3').text()).toBe('待处理文件夹（top 0 / 共 0 组）')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus —— 失败卡 + N19 三态(蓝本 :91-102)', () => {
  // 🔴 N19:`<ul v-show="failedOpen" v-if="store.failedJobs.length">` 两个指令同挂。
  // Vue 里 `v-if` 优先级高于 `v-show` → 空桶时整个 `<ul>` 不渲染、`v-show` 是死的。
  // 判据:合并成单一指令(只留 v-show 或只留 v-if)→ 本组三条里至少一条必须报红。
  it('N19 态①:本机空桶 —— 折叠按钮无条件渲染且能点(「▶ 最近失败（0）」),但点开后 <ul> 整个不渲染', async () => {
    const w = await mountPage()
    const btn = w.find('.failures-card .toggle')
    expect(btn.exists()).toBe(true)
    expect(btn.text()).toBe('▶ 最近失败（0）')
    expect(w.find('.failure-list').exists()).toBe(false)

    await btn.trigger('click')
    await nextTick()
    // 箭头翻了(证明 failedOpen 真的置真、按钮真的可点)
    expect(w.find('.failures-card .toggle').text()).toBe('▼ 最近失败（0）')
    // 但列表仍然不存在 —— 这是**正确行为**(v-if 先判掉),不是缺陷(治理 §13)
    expect(w.find('.failure-list').exists()).toBe(false)
  })

  it('N19 态②:非空桶 + 未展开 —— <ul> 渲染出来了,但被 v-show 隐藏(display: none)', async () => {
    ai.parserJobs.mockResolvedValue({ jobs: [FAILED_ROW] })
    const w = await mountPage()
    const ul = w.find('.failure-list')
    expect(ul.exists()).toBe(true)
    expect((ul.element as HTMLElement).style.display).toBe('none')
    expect(w.find('.failures-card .toggle').text()).toBe('▶ 最近失败（1）')
  })

  it('N19 态③:非空桶 + 展开 —— <ul> 可见,行里 path + 截断后的 error', async () => {
    ai.parserJobs.mockResolvedValue({ jobs: [{ ...FAILED_ROW, last_error: 'boom' }] })
    const w = await mountPage()
    await w.find('.failures-card .toggle').trigger('click')
    await nextTick()
    const ul = w.find('.failure-list')
    expect((ul.element as HTMLElement).style.display).toBe('')
    const lis = ul.findAll('li')
    expect(lis).toHaveLength(1)
    expect(lis[0]!.find('.path').text()).toBe('/DATA/.system_data/tmp/nimoos_panic.log')
    expect(lis[0]!.find('.error').text()).toBe('boom')
    expect(w.find('.failures-card .toggle').text()).toBe('▼ 最近失败（1）')
  })

  it('truncateErr 边界:120 字符原样、121 字符截成前 120 + U+2026(蓝本 :156 是严格 `> 120`)', async () => {
    const e120 = 'x'.repeat(120)
    const e121 = 'y'.repeat(121)
    ai.parserJobs.mockResolvedValue({
      jobs: [
        { ...FAILED_ROW, id: 1, last_error: e120 },
        { ...FAILED_ROW, id: 2, last_error: e121 },
      ],
    })
    const w = await mountPage()
    await w.find('.failures-card .toggle').trigger('click')
    await nextTick()
    const errs = w.findAll('.failure-list .error')
    expect(errs).toHaveLength(2)
    expect(errs[0]!.text()).toBe(e120) // 恰好 120 → 不截
    expect(errs[0]!.text()).toHaveLength(120)
    expect(errs[1]!.text()).toBe('y'.repeat(120) + '…') // 121 → 截 + 省略号
    expect(errs[1]!.text()).toHaveLength(121)
  })

  it('truncateErr 空值:last_error 为 null(本机真行的实测值)→ 渲染空串,不渲染 "null"', async () => {
    ai.parserJobs.mockResolvedValue({ jobs: [FAILED_ROW] }) // FAILED_ROW.last_error === null
    const w = await mountPage()
    await w.find('.failures-card .toggle').trigger('click')
    await nextTick()
    expect(w.find('.failure-list .error').text()).toBe('')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus —— N20:5 秒轮询 + document.hidden 守卫 + 卸载清理(蓝本 :127-135)', () => {
  // 照 `QueueView.test.ts:859-891` 的既有写法:`onMounted` 里的 `loadAll()` 是同步
  // 发起调用(`Promise.all` 内四个 `service.ai.parser*` 是同步触发,只有各自 resolve
  // 走微任务),不需要 `runOnlyPendingTimersAsync` 去"催"—— 那个 API 会把尚未到期的
  // setInterval 也提前打一次,导致误判成多发一轮。
  it('频率就是 5000ms:推进 4999ms 不发,再推进 1ms 才发一轮', async () => {
    vi.useFakeTimers()
    try {
      const router = makeRouter()
      await router.isReady()
      const w = mount(ParserStatus, { global: { plugins: [router, i18n] } } as never)
      expect(ai.parserStats).toHaveBeenCalledTimes(1) // mounted 立即一发

      ai.parserStats.mockClear()
      vi.advanceTimersByTime(4999)
      expect(ai.parserStats).not.toHaveBeenCalled()
      vi.advanceTimersByTime(1)
      expect(ai.parserStats).toHaveBeenCalledTimes(1)

      // 再一拍(证明是 setInterval 而不是 setTimeout)
      ai.parserStats.mockClear()
      vi.advanceTimersByTime(5000)
      expect(ai.parserStats).toHaveBeenCalledTimes(1)
      w.unmount()
    } finally {
      vi.useRealTimers()
    }
  })

  it('🔴 document.hidden 为 true 时跳过这一拍;转回 false 后恢复', async () => {
    // 判据:拿掉 `if (!document.hidden)` 守卫 → 中间那段会发出请求 → 本条报红。
    vi.useFakeTimers()
    const hidden = vi.spyOn(document, 'hidden', 'get').mockReturnValue(false)
    try {
      const router = makeRouter()
      await router.isReady()
      const w = mount(ParserStatus, { global: { plugins: [router, i18n] } } as never)
      ai.parserStats.mockClear()

      hidden.mockReturnValue(true)
      vi.advanceTimersByTime(15000) // 三拍全跳过
      expect(ai.parserStats).not.toHaveBeenCalled()

      hidden.mockReturnValue(false)
      vi.advanceTimersByTime(5000)
      expect(ai.parserStats).toHaveBeenCalledTimes(1)
      w.unmount()
    } finally {
      hidden.mockRestore()
      vi.useRealTimers()
    }
  })

  it('🔴 onBeforeUnmount 清定时器:卸载后再怎么推进都不再发请求', async () => {
    vi.useFakeTimers()
    try {
      const router = makeRouter()
      await router.isReady()
      const w = mount(ParserStatus, { global: { plugins: [router, i18n] } } as never)
      vi.advanceTimersByTime(5000)
      expect(ai.parserStats).toHaveBeenCalledTimes(2) // mounted + 一拍

      w.unmount()
      ai.parserStats.mockClear()
      vi.advanceTimersByTime(60000) // 12 拍
      expect(ai.parserStats).not.toHaveBeenCalled()
    } finally {
      vi.useRealTimers()
    }
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus —— N16 emoji / 符号位置核对(一个都不许挪进/挪出 t())', () => {
  it('i18n 键值本身零 emoji / 零箭头符号(证明符号在模板或 script 侧,不在语言包里)', () => {
    const t = i18n.global.t as unknown as (k: string) => string
    // 由 script 拼接的两个(蓝本 :27)
    expect(t('aiKbResume')).toBe('恢复')
    expect(t('aiKbPause')).toBe('暂停')
    // 在 t() 外面的七个 emoji 所属的键值(蓝本 :6 / :70-75)
    expect(t('aiKbPrTestLink')).toBe('测试沙盒')
    expect(t('aiKbPending')).toBe('待处理')
    expect(t('aiKbPrQueueRunning')).toBe('处理中')
    expect(t('aiKbPrQueueDone')).toBe('完成')
    expect(t('aiKbFailed')).toBe('已失败')
    expect(t('aiKbPrIndexedVectors')).toBe('已入向量')
    expect(t('aiKbLastSynced')).toBe('上次同步')
    for (const k of [
      'aiKbResume', 'aiKbPause', 'aiKbPrTestLink', 'aiKbPending', 'aiKbPrQueueRunning',
      'aiKbPrQueueDone', 'aiKbFailed', 'aiKbPrIndexedVectors', 'aiKbLastSynced',
      'aiKbPrRecentFailures',
    ]) {
      expect(t(k)).not.toMatch(/[🧪⏳🔄✅❌📦📍▼▶⏸]/u)
    }
    // 🔴 反过来:`→` **在**键值里(蓝本 :53 的 `$t('→ actual {device}')`),不在模板里。
    //    这里读语言包原串(过 `t()` 会把 `{device}` 当缺失参数吃掉)。
    expect((zhCn as Record<string, string>).aiKbPrResolvedHint).toBe('→ 实际 {device}')
  })

  it('模板里 emoji 与译文之间恰好一个空格,顺序是「符号 → 文案」', async () => {
    const w = await mountPage()
    expect(w.find('a.test-link').text()).toBe('🧪 测试沙盒')
    // ⚠️ 不用 `slice(0, 2)` 取首字符:🔄/📦/📍 是非 BMP 码点(各占 2 个 UTF-16 单元),
    //    ⏳/✅/❌ 是 BMP(各占 1 个)—— 按单元切会切出不同长度。用带 `u` 标志的正则。
    expect(w.findAll('.queue-card .kv').map((k) => k.text())).toEqual([
      expect.stringMatching(/^⏳ \S/u),
      expect.stringMatching(/^🔄 \S/u),
      expect.stringMatching(/^✅ \S/u),
      expect.stringMatching(/^❌ \S/u),
      expect.stringMatching(/^📦 \S/u),
      expect.stringMatching(/^📍 \S/u),
    ])
    expect(w.find('.pause-btn').text().startsWith('▶ ')).toBe(true)
    expect(w.find('.failures-card .toggle').text().startsWith('▶ ')).toBe(true)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus —— 守卫缺口③:<template> 块零裸色字面量', () => {
  // 治理 §9 缺口③:`color-guard.test.ts:44-56` 的 `styleLines()` 对 `.vue` 只取
  // `<style>` 块 → 模板 `style=` / `:style=` 属性零扫描;本文件补一条定向断言堵这个盲区。
  // ⚠️ 沿用现状写法(非贪婪 + 隐式靠「`</template>` 在第 0 列」锚定,先例
  // `QueueView.test.ts` / `IndexedFilesView.test.ts` / `FolderBrowser.test.ts`);
  // 治理 §9 缺口③′ 的「统一改成贪婪匹配 + 覆盖度自检」归 **T8**,本刀不动它。
  // 🔴 读源文件用 `node:fs`,不用 Vite 的 `?raw`。
  it('<template> 块内(剥离 var()/color-mix() 之后)不含任何裸 hex / rgb / hsl 字面量', () => {
    const src: string = readFileSync(resolve(__dirname, './ParserStatus.vue'), 'utf8')
    const m = /<template>([\s\S]*?)\n<\/template>/.exec(src)
    expect(m).not.toBeNull()
    const tmpl = m![1]
    // 覆盖度自检:抽出的片段必须同时含模板**首部**与**尾部**的特征串。
    // 本组件唯一的嵌套 `<template v-else>` 带属性(不是裸 `<template>`)、其闭合标签
    // 也是缩进的 → 不会把第 0 列的 `</template>` 提前截断。
    expect(tmpl).toContain('aiKbPrDetailsTitle') // 首部(页头 h2)
    expect(tmpl).toContain('truncateErr(j.last_error)') // 尾部(失败卡最后一行内容)

    // 剥掉 var(...) 与 color-mix(...) 的内部(照 color-guard.test.ts 的 stripVar
    // 同款手法:逐字符扫描配对括号深度,支持嵌套 fallback)
    function stripCalls(s: string, prefixes: string[]): string {
      let out = ''
      let i = 0
      while (i < s.length) {
        const hit = prefixes.find((p) => s.startsWith(p, i))
        if (hit) {
          let depth = 0
          let j = i + hit.length - 1 // 落在开括号上
          for (; j < s.length; j++) {
            if (s[j] === '(') depth++
            else if (s[j] === ')') {
              depth--
              if (depth === 0) {
                j++
                break
              }
            }
          }
          i = j
        } else {
          out += s[i]
          i++
        }
      }
      return out
    }
    const scrubbed = stripCalls(tmpl, ['var(', 'color-mix('])
    expect(scrubbed).not.toMatch(/#[0-9a-fA-F]{3,8}\b/)
    expect(scrubbed).not.toMatch(/\b(rgba?|hsla?)\s*\(/)
  })

  it('本文件零 <style> 块(K24:样式在 parser-styles.scss,走 JS 侧 import)', () => {
    const src: string = readFileSync(resolve(__dirname, './ParserStatus.vue'), 'utf8')
    expect(src).not.toMatch(/^<style/m)
    expect(src).toContain("import '../../styles/parser-styles.scss'")
  })

  it('零 KIcon(治理 §1.2 / N16:两个 Parser 页蓝本一个 KIcon 都不用)', async () => {
    const src: string = readFileSync(resolve(__dirname, './ParserStatus.vue'), 'utf8')
    expect(src).not.toMatch(/^import KIcon/m)
    const w = await mountPage()
    expect(w.findAll('svg')).toHaveLength(0)
  })
})
