// SP8-P5c Task 6 — component test for `ParserStatus.vue`.
// Blueprint: `NimoOS-UI` (main@7a6ee6b7) `src/views/AI/Parser/ParserStatus.vue` (164 lines).
//
// ═══ mock strategy (governance §4.1 requires explicit documentation) ═══
// 🔴 **mock shared package `service.ai.parser*`, use real `parserStore` (T5 output)**, do not mock store.
//   Reason: all page data must pass through `parserStore`'s K1 downlayering (blueprint `store.state.xxx` →
//   this repo `store.xxx`) and N7 fallback. Mocking store avoids testing the most-easy-to-break "does downlayering
//   and field names actually match" part; using real store makes every render assertion naturally an integration test —
//   template missing one `.state.` layer or field name off by one letter immediately shows as empty/undefined.
//   Cost is each test needs `flushPromises()` waiting for all four `Promise.all` completions, acceptable.
// 🔴 All six `service.ai.parser*` methods in package only do `return res.data` (`NimoOS-Service/src/ai.ts:591-620`, zero transformation)
//   → mock them here as **raw HTTP snake_case**, matching fixture literally. **Must have identical shapes across
//   `parserStore.test.ts` / `knowledgeStore.parser.test.ts`** (governance §4.1 red flag self-check: same method
//   mocked differently in two test files = time bomb, §8.3 has precedent). `parserControl` also mocked to `{}`, consistent
//   with those two files.
//
// ═══ fixtures are copies, not runtime reads (governance §4.4) ═══
// Data copied verbatim into `FIXTURE-COPY-BEGIN/END` blocks below with citations,
// **do not read `.superpowers/` with `node:fs`** — that directory is gitignored (SP7 lost it entirely),
// this branch will merge to master; tests in `src/` with cross-boundary dependencies silently fail with
// "file not found". 🔴 Copy generated by one-time script from fixtures (zero hand transcription),
// equivalence verified by **automated byte-for-byte validation** (output in T6 report §4) — not visual comparison.
// Reading `.vue` source files (guard gaps③ those two) still uses `node:fs`, **never Vite's `?raw`**
//   (vitest's CSSEnablerPlugin replaces style source with empty string → assertions "pass" on empty string;
//    precedent: `knowledgeStyles.test.ts` comment③).
//
// ═══ boolean attribute assertion calibration (governance §9) ═══
// `:checked` / `:disabled` are **boolean attributes**: Vue renders `disabled=""` (empty string) when true,
// omits attribute when false → `attributes('disabled')` false side can only be `undefined`, but governance §9
// **forbids `toBeUndefined()`**. So assert **DOM properties** always (`el.disabled` / `el.checked`),
// which are naturally true/false comparable values, **both sides**. Other text/href: compare as strings directly.
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import { nextTick } from 'vue'
import { setActivePinia, createPinia } from 'pinia'
import { createRouter, createWebHashHistory } from 'vue-router'
import { i18n } from '../../../i18n'
import zhCn from '../../../i18n/zh_cn'
import ParserStatus from './ParserStatus.vue'
import type {
  ParserStatsBody,
  ParserControlStateBody,
  ParserFoldersBody,
  ParserFailedJob,
} from '../stores/parserStore'
import { readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

// ── vi.hoisted mock skeleton (governance §9: avoid ESM hoisting TDZ) ──
const ai = vi.hoisted(() => ({
  parserStats: vi.fn(),
  parserState: vi.fn(),
  parserFolders: vi.fn(),
  parserJobs: vi.fn(),
  parserControl: vi.fn(),
}))
vi.mock('@nimotech/nimoos-service', () => ({ service: { ai } }))

// ═══════════════════════════════════════════════════════════════════════════
// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-stats.json  (complete, GET /v1/parser/stats)
// From `.superpowers/sdd/p5c-fixtures/parser-stats.json` (real device capture 2026-08-03 13:22).
// Real device measured values per governance §4.3: pending 339 / running 1 / failed 0 / done 9 ·
// total_vectors_text 5592 · last_cursor_ms 1784775953391.
const STATS: ParserStatsBody = {
  "queue_depth": {
    "pending": 339,
    "running": 1,
    "failed": 0,
    "done": 9
  },
  "indexed_files": 7,
  "total_vectors_text": 5592,
  "total_vectors_visual": 0,
  "last_cursor_ms": 1784775953391,
  "models": [
    {
      "name": "bge-m3",
      "version": "v1",
      "modality": "text",
      "dim": 1024
    },
    {
      "name": "bge-reranker-v2-m3",
      "version": "v1",
      "modality": "rerank",
      "dim": null
    }
  ]
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-control-state.json  (complete, GET /v1/parser/state)
// From `.superpowers/sdd/p5c-fixtures/parser-control-state.json` (2026-08-03 13:22).
// 🔴 Device is currently in **paused state** (governance §4.3) → light is `.paused`, button is "▶ Resume".
// "Running / green light / ⏸ Paused" state not visible on this device, covered by fixture variants below.
const STATE: ParserControlStateBody = {
  "paused": true,
  "concurrency": 2,
  "device": "auto",
  "ocr_enabled": false,
  "resolved_device": "cpu"
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-folders-pending-20.json  (complete 20 items + total_groups)
// From `.superpowers/sdd/p5c-fixtures/parser-folders-pending-20.json` (2026-08-03 13:22,
// `GET /v1/parser/folders?limit=20`). 🔴 **all 20 items copied**, fields (`root_id`/`folder`/`count`)
// no simplification, order unchanged. First item count 18 = max value (barWidth 100% baseline), last item 4.
const FOLDERS: ParserFoldersBody = {
  "folders": [
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/.github/workflows","count":18},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/projects/-home-nimo-NimoTech/9c3e7a5c-f2fc-409c-9ca3-7f46a47e1d81/subagents","count":16},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/.docker/containers/26be4bc607290dbbc955a0f5f1f1317d7a5b55df87ccdd86e9987ca8440c7ea1","count":15},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/opt/qdrant/storage/collections/text_chunks","count":12},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/tmp","count":11},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude","count":11},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/external_plugins/discord","count":10},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/external_plugins/imessage","count":10},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/external_plugins/fakechat","count":8},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/opt/qdrant/storage/collections/visual_chunks","count":8},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/plugins/claude-security/agents","count":7},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins","count":6},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/.github/scripts","count":6},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/external_plugins/telegram","count":5},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/plugins/claude-code-setup/skills/claude-automation-recommender/references","count":5},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/opt/qdrant/storage/collections/text_chunks/0","count":5},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/opt/qdrant/storage/collections/visual_chunks/0","count":5},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/.docker/containers/2e55949f61fe879896fedd0334339c31d1cd962691358c56bf3ca0b03781e983","count":4},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/external_plugins/greptile","count":4},
    {"root_id":"dfcd1840f5dab439cd9d7050aa5bafd0","folder":"/DATA/.system_data/.docker/containers/aade3000de2889facb1f7ba7789d6f2c2fe6acdaf1a9adc7433242648d5c47e7","count":4}
  ],
  "total_groups": 119
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-jobs-failed-5.json  (complete, GET /v1/parser/jobs?status=failed&limit=5)
// From `.superpowers/sdd/p5c-fixtures/parser-jobs-failed-5.json` (2026-08-03 13:22).
// 🔴 Device failed bucket **is empty** (governance §4.3 / §13) → N19's "after opening list entirely not rendered" is **correct behavior**.
const FAILED_EMPTY: { jobs: ParserFailedJob[] } = {
  "jobs": []
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5b-fixtures/jobs-pending.json  jobs[0]  (real row, copied verbatim)
// From `jobs[0]` (id 348) of `.superpowers/sdd/p5b-fixtures/jobs-pending.json`.
// 🔴 Why borrow a row from pending bucket: device failed bucket measured empty, but `/v1/parser/jobs` is same table,
// same serializer, row shape independent of status → borrow it as real row for N19 "non-empty bucket" two states.
// **Precedent: `parserStore.test.ts` `FAILED_ROW` and `knowledgeStore.staleGuard.test.ts` `POISON_FAILED_ROW`
// same approach** (T3 fix round 1 M-2 approved). Fields unchanged.
const FAILED_ROW: ParserFailedJob = {
  "id": 348,
  "root_id": "dfcd1840f5dab439cd9d7050aa5bafd0",
  "path": "/DATA/.system_data/tmp/nimoos_panic.log",
  "op": "index",
  "sub_modality": null,
  "priority": 100,
  "attempts": 0,
  "last_error": null,
  "locked_until": null,
  "created_at": 1784776422853,
  "picked_at": null,
  "done_at": null
}
// FIXTURE-COPY-END
// ═══════════════════════════════════════════════════════════════════════════

/** All four calls succeed, all fed with fixture raw text. */
function mockAllOk(): void {
  ai.parserStats.mockResolvedValue(STATS)
  ai.parserState.mockResolvedValue(STATE)
  ai.parserFolders.mockResolvedValue(FOLDERS)
  ai.parserJobs.mockResolvedValue(FAILED_EMPTY)
  // `parserControl` response body not consumed by this page (blueprint just `await`s all five actions);
  // shape consistent with `parserStore.test.ts:207` / `knowledgeStore.parser.test.ts:136`.
  ai.parserControl.mockResolvedValue({})
}

function deferred<T>() {
  let resolve!: (v: T) => void
  let reject!: (e: unknown) => void
  const promise = new Promise<T>((res, rej) => {
    resolve = res
    reject = rej
  })
  return { promise, resolve, reject }
}

// Each test's mounted wrapper unified unmount in afterEach — this page's `onMounted` starts a real
// `setInterval(…, 5000)` (N20), not unmounting leaks timers and store refs to other tests
// (precedent `QueueView.test.ts:162-167` same scaffolding, that one polls every 10 seconds).
const mountedWrappers: Array<ReturnType<typeof mount>> = []

function makeRouter() {
  const router = createRouter({
    history: createWebHashHistory('/app/'),
    routes: [
      { path: '/ai/parser', name: 'AIParser', component: ParserStatus },
      // Blueprint `:6`'s `router-link to="/ai/parser/test"` needs the target route to
      // exist for the href to resolve at all.
      // [Correction, SP8-P5d Task 9, governance §15.2 / plan §T9 item 6] The previous comment
      // was doubly stale: (1) it said "in production this route still points at a placeholder
      // page" — production reversed this ages ago to the real ParserTest (output of P5c-T10,
      // fully documented in knowledgeRoutes.ts's header comment); (2) the line number it cited
      // had also drifted. The stub component here is only a placeholder in this test file's own
      // route table, unrelated to whether production's route is a placeholder — the stub stays
      // because this file only cares whether the href resolves, not what the
      // `/ai/parser/test` page itself renders.
      { path: '/ai/parser/test', name: 'AIParserTest', component: { template: '<div />' } },
    ],
  })
  router.push('/ai/parser')
  return router
}

/** Mount but **don't flush** — for observing the `loading` state while the four calls are in flight. */
async function mountRaw() {
  const router = makeRouter()
  await router.isReady()
  const w = mount(ParserStatus, { global: { plugins: [router, i18n] } } as never)
  mountedWrappers.push(w)
  return w
}

/** Mount and wait for all four calls to land. */
async function mountPage() {
  const w = await mountRaw()
  await flushPromises()
  await nextTick()
  return w
}

beforeEach(() => {
  setActivePinia(createPinia())
  vi.clearAllMocks()
  mockAllOk()
})

afterEach(() => {
  while (mountedWrappers.length) mountedWrappers.pop()!.unmount()
  document.body.innerHTML = ''
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus — K31 two-layer root element (scroll container + 900px centered column)', () => {
  // 🔴 Governance §3 K31: `.parser-app` is **outer wrapper**, page root class `.parser-status-page` is **inner**.
  // Squashing into one element puts the `overflow-y:auto` scrollbar at the right edge of the 900px centered column
  // (roughly screen center on wide screens), whereas Vue2 scrolls the whole page with scrollbar at viewport's right edge
  // = user-visible interface not 1:1. Test criterion: rewrite two classes back into one element → both tests must fail.
  it('root element only has .parser-app (not .parser-status-page)', async () => {
    const w = await mountPage()
    const root = w.element as HTMLElement
    expect(root.tagName).toBe('DIV')
    expect(root.className).toBe('parser-app')
    expect(root.classList.contains('parser-status-page')).toBe(false)
  })

  it('.parser-status-page is direct child of .parser-app, and exactly one of each', async () => {
    const w = await mountPage()
    expect(w.findAll('.parser-app')).toHaveLength(1)
    expect(w.findAll('.parser-status-page')).toHaveLength(1)
    expect(w.find('.parser-app > .parser-status-page').exists()).toBe(true)
    // Page content is actually in inner layer (not empty shell)
    expect(w.find('.parser-status-page > .page-header').exists()).toBe(true)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus — page header (blueprint :3-9)', () => {
  it('title / 🧪 test-sandbox link (incl. href) / refresh button copy, verbatim', async () => {
    const w = await mountPage()
    expect(w.find('.page-header h2').text()).toBe('Parser 详情')
    const link = w.find('a.test-link')
    // N16: 🧪 sits outside t() — renders as "🧪 测试沙盒" (emoji + space + translation)
    expect(link.text()).toBe('🧪 测试沙盒')
    // Hash routing: in jsdom, location is `http://localhost:3000/`, and the href resolved
    // via `createWebHashHistory('/app/')` is a bare hash (in production the browser address
    // bar shows `…/app/#/ai/parser/test`)
    expect(link.attributes('href')).toBe('#/ai/parser/test')
    expect(w.find('.refresh-btn').text()).toBe('刷新')
  })

  it('fires once on mount (each of the four calls once, args matching the blueprint)', async () => {
    await mountPage()
    expect(ai.parserStats).toHaveBeenCalledTimes(1)
    expect(ai.parserState).toHaveBeenCalledTimes(1)
    expect(ai.parserFolders).toHaveBeenCalledWith({ limit: 20 })
    expect(ai.parserJobs).toHaveBeenCalledWith({ status: 'failed', limit: 5 })
  })

  it('clicking refresh → fires again (blueprint reload() :137)', async () => {
    const w = await mountPage()
    await w.find('.refresh-btn').trigger('click')
    await flushPromises()
    expect(ai.parserStats).toHaveBeenCalledTimes(2)
    expect(ai.parserFolders).toHaveBeenCalledTimes(2)
  })

  it('🔴 both sides of :disabled="loading" — while the four calls are in flight, refresh button + three radio groups + OCR checkbox are all disabled; all re-enabled once landed', async () => {
    const d = deferred<ParserStatsBody>()
    ai.parserStats.mockReturnValue(d.promise)
    const w = await mountRaw()
    await nextTick()

    const btn = () => w.find('.refresh-btn').element as HTMLButtonElement
    const inputs = () => w.findAll('.control-card input').map((n) => n.element as HTMLInputElement)
    // In flight: loading is set to true synchronously (`parserStore.ts:161`, before the await)
    expect(btn().disabled).toBe(true)
    expect(inputs()).toHaveLength(7) // 3 concurrency + 3 device + 1 OCR
    expect(inputs().every((el) => el.disabled === true)).toBe(true)

    d.resolve(STATS)
    await flushPromises()
    await nextTick()
    expect(btn().disabled).toBe(false)
    expect(inputs().every((el) => el.disabled === false)).toBe(true)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus — unreachable, two states (blueprint :11-14)', () => {
  it('all four calls succeed → no warning card, all four cards present', async () => {
    const w = await mountPage()
    expect(w.find('.card.unreachable').exists()).toBe(false)
    expect(w.find('.control-card').exists()).toBe(true)
    expect(w.find('.queue-card').exists()).toBe(true)
    expect(w.find('.folders-card').exists()).toBe(true)
    expect(w.find('.failures-card').exists()).toBe(true)
  })

  it('any one call fails → warning card appears with store.error echoed in <small>, all four cards go away entirely (v-else)', async () => {
    // Blueprint `:13`'s `<small>{{ store.state.error }}</small>` echoes the network layer's
    // `e.message || String(e)` (`parserStore.ts:184`) — blueprint behavior, copied as-is
    // (K5/K30 don't apply here; those guard against splicing a backend response body's
    // `detail` into a toast, which is a different concern).
    ai.parserFolders.mockRejectedValue(new Error('parser down'))
    const w = await mountPage()
    const card = w.find('.card.unreachable')
    expect(card.exists()).toBe(true)
    expect(card.text()).toContain('Parser 服务未运行或不可达。')
    expect(card.find('small').text()).toBe('parser down')
    expect(w.find('.control-card').exists()).toBe(false)
    expect(w.find('.queue-card').exists()).toBe(false)
    expect(w.find('.folders-card').exists()).toBe(false)
    expect(w.find('.failures-card').exists()).toBe(false)
    // The page header always sits outside the v-if/v-else
    expect(w.find('.page-header h2').text()).toBe('Parser 详情')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus — control card: status light + pause button (blueprint :19-29)', () => {
  it('real device measurement paused:true → .dot carries the paused class, copy "已暂停", button "▶ 恢复"', async () => {
    const w = await mountPage()
    const dot = w.find('.status-text .dot')
    expect(dot.classes()).toContain('paused')
    expect(w.find('.status-text').text()).toBe('已暂停')
    // N16: `▶ ` is concatenated by script; the i18n key value is plain "恢复"
    expect(w.find('.pause-btn').text()).toBe('▶ 恢复')
  })

  it('fixture variant paused:false → .dot has no paused class, copy "运行中", button "⏸ 暂停"', async () => {
    // Only change the `paused` field (governance §4.3: the real device is in the paused
    // state, so the running state can only be covered via a fixture variant)
    ai.parserState.mockResolvedValue({ ...STATE, paused: false })
    const w = await mountPage()
    expect(w.find('.status-text .dot').classes()).not.toContain('paused')
    expect(w.find('.status-text').text()).toBe('运行中')
    expect(w.find('.pause-btn').text()).toBe('⏸ 暂停')
  })

  it('clicking the button while paused → calls resume (blueprint ternary :139-141)', async () => {
    const w = await mountPage()
    await w.find('.pause-btn').trigger('click')
    await flushPromises()
    expect(ai.parserControl).toHaveBeenCalledTimes(1)
    expect(ai.parserControl).toHaveBeenCalledWith({ action: 'resume' })
  })

  it('clicking the button while not paused → calls pause', async () => {
    ai.parserState.mockResolvedValue({ ...STATE, paused: false })
    const w = await mountPage()
    await w.find('.pause-btn').trigger('click')
    await flushPromises()
    expect(ai.parserControl).toHaveBeenCalledTimes(1)
    expect(ai.parserControl).toHaveBeenCalledWith({ action: 'pause' })
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus — control card: concurrency level (N17, blueprint :30-40)', () => {
  it('N17 takes i18n by array index → three-way copy order "省电 (1)" "平衡 (2)" "全力 (4)"', async () => {
    const w = await mountPage()
    expect(w.find('.concurrency-row > label').text()).toBe('并发档位:')
    const radios = w.findAll('.concurrency-row .radio')
    expect(radios).toHaveLength(3)
    expect(radios.map((r) => r.text())).toEqual(['省电 (1)', '平衡 (2)', '全力 (4)'])
  })

  it('🔴 both sides of :checked — with concurrency:2, only the second option is true', async () => {
    const w = await mountPage()
    const els = w.findAll('.concurrency-row input').map((n) => n.element as HTMLInputElement)
    expect(els.map((el) => el.checked)).toEqual([false, true, false])
    expect(els.map((el) => el.getAttribute('value'))).toEqual(['1', '2', '4'])
  })

  it('🔴 both sides of :checked — fixture variant concurrency:4, only the third option is true', async () => {
    ai.parserState.mockResolvedValue({ ...STATE, concurrency: 4 })
    const w = await mountPage()
    const els = w.findAll('.concurrency-row input').map((n) => n.element as HTMLInputElement)
    expect(els.map((el) => el.checked)).toEqual([false, false, true])
  })

  it('@change → setConcurrency(n), payload key is `n` (matches the backend controlReq)', async () => {
    const w = await mountPage()
    await w.findAll('.concurrency-row input')[2]!.trigger('change')
    await flushPromises()
    expect(ai.parserControl).toHaveBeenCalledWith({ action: 'set_concurrency', n: 4 })
  })
})

// ═══════════════════════════════════════════════════════════════════════════
// 🔴 I-1 (guard gap caught by review 2026-08-04) — **N21 #3's key-selection discipline
// needs an en-locale guard.**
//
// Review probe: swap the three concurrency keys for the ones governance **explicitly bans
// from reuse** — `aiKbCcPowerSaver` / `aiKbCcFullSpeed` — and the whole batch of tests above
// still goes **47/47 green**. Reason: those assertions only compare **zh** text, and these
// two key pairs **collide verbatim in zh, differing only in en**:
//     aiKbPrCcPowerSaving  en `Power-saving`  zh 省电   ← the one this page must use (T1, new)
//     aiKbCcPowerSaver     en `Power saver`   zh 省电   ← the one banned from reuse (pre-existing)
//     aiKbPrCcFullPower    en `Full power`    zh 全力   ← the one this page must use (T1, new)
//     aiKbCcFullSpeed      en `Full speed`    zh 全力   ← the one banned from reuse (pre-existing)
// → reusing them would make the **English UI** render `Power saver` / `Full speed`, diverging
//   from Vue2 — i.e. not a pixel-for-pixel port — while the **Chinese UI shows no difference
//   at all**, so all three gates pass green. This discipline had zero guard before now.
//
// **Approach chosen**: switch locale to `en_us`, actually mount the component once, and
// assert the rendered text — rather than reading the locale file's key values directly.
// Reason: the invariant to guard is "**the English rendered on this page** is those three
// Vue2 strings"; reading key values only proves "what some key's value is", not "which key
// the template actually uses". Going through the render path pins both "the right key was
// chosen" and "the value is correct" at once. **A reverse assertion is added too** (not
// equal to the en values of the two banned keys), so that even if someone later changes
// `aiKbCcPowerSaver`'s en value to also be `Power-saving`, the forward assertion would go
// green but the reverse assertion still guards the user-visible fact that "the rendered
// output must never contain `Power saver`/`Full speed`".
//
// 🔴 locale is a global singleton → must be restored with `try/finally`, otherwise it
// pollutes later tests in this file.
describe('ParserStatus — 🔴 I-1: strong en-locale assertions for N21 #3 key-selection discipline (zh collides, only en can tell them apart)', () => {
  /** `i18n.global.locale` is a WritableComputedRef in composition mode. */
  const localeRef = i18n.global.locale as unknown as { value: string }

  async function mountInEn() {
    const prev = localeRef.value
    localeRef.value = 'en_us'
    try {
      return { w: await mountPage(), restore: () => { localeRef.value = prev } }
    } catch (e) {
      localeRef.value = prev
      throw e
    }
  }

  it('en-locale three-way concurrency labels verbatim = `Power-saving (1)` / `Balanced (2)` / `Full power (4)`', async () => {
    const { w, restore } = await mountInEn()
    try {
      expect(w.findAll('.concurrency-row .radio').map((r) => r.text())).toEqual([
        'Power-saving (1)',
        'Balanced (2)',
        'Full power (4)',
      ])
      expect(w.find('.concurrency-row > label').text()).toBe('Concurrency level:')
    } finally {
      restore()
    }
  })

  it('🔴 reverse: en-locale rendered output must never contain the en values of the banned keys (`Power saver` / `Full speed`)', async () => {
    const { w, restore } = await mountInEn()
    try {
      const row = w.find('.concurrency-row').text()
      expect(row).not.toContain('Power saver') // = aiKbCcPowerSaver's en value
      expect(row).not.toContain('Full speed') // = aiKbCcFullSpeed's en value
      // Also sweep the whole page (in case of future misuse elsewhere)
      expect(w.text()).not.toContain('Power saver')
      expect(w.text()).not.toContain('Full speed')
    } finally {
      restore()
    }
  })

  it('switching back to zh, the three options are still "省电 (1)"/"平衡 (2)"/"全力 (4)" (proves locale was restored, no pollution)', async () => {
    const w = await mountPage()
    expect(w.findAll('.concurrency-row .radio').map((r) => r.text())).toEqual([
      '省电 (1)', '平衡 (2)', '全力 (4)',
    ])
  })

  // 🔴 the guard for ruling A-1 (`aiKbDeviceAuto` must not reuse `aiKbOriginAuto`) **can only
  // live at the source-code level**:
  // — the two keys are **verbatim identical in en and zh** (`Auto` / `自动`, confirmed at
  // `en_us.ts:1548` vs `:1625`, `zh_cn.ts:1562` vs `:1652`) → **no rendering assertion has
  // any discriminating power** here (which is exactly ruling A-1's stated rationale: "reuse
  // renders identically, but the key names carry the semantics of 'where the value settled
  // from', and future changes to the settle-from copy would silently change the device
  // dropdown too"). So this discipline can only be guarded by a source-code assertion on
  // "which key the template actually uses".
  // Warning: the assertion must pin the **`t()` call shape**, not a bare substring: this
  // file's header comment itself contains a sentence saying "**does not reuse**
  // `aiKbOriginAuto`" — `not.toContain('aiKbOriginAuto')` would collide with that comment
  // and false-fail (the first version tripped on exactly this) — same family as governance
  // §9 items 7/8 ("a string search in the file colliding with a comment"), just happening
  // on the **read** side this time. The discriminator is pinned on the call shape
  // `t('aiKbOriginAuto')`.
  it('🔴 A-1: the device option uses aiKbDeviceAuto, zero calls to `t(\'aiKbOriginAuto\')` (en/zh both equal → rendering assertions have no discriminating power)', () => {
    const src: string = readFileSync(resolve(__dirname, './ParserStatus.vue'), 'utf8')
    expect(src).toContain("{ value: 'auto', label: t('aiKbDeviceAuto') }")
    expect(src).not.toMatch(/\bt\(\s*['"]aiKbOriginAuto['"]/)
    // Proof, in reverse, of why this must go through source code: both keys have the same
    // value in both locales, so rendering can never tell them apart
    const zh = zhCn as Record<string, string>
    expect(zh.aiKbDeviceAuto).toBe(zh.aiKbOriginAuto)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus — control card: inference device (blueprint :41-55)', () => {
  it('three-way copy: "自动" goes through i18n, "GPU (CUDA)"/"CPU" are hardcoded technical identifiers (not in i18n)', async () => {
    const w = await mountPage()
    expect(w.find('.device-row > label').text()).toBe('推理设备:')
    const radios = w.findAll('.device-row .radio')
    expect(radios).toHaveLength(3)
    expect(radios.map((r) => r.text())).toEqual(['自动', 'GPU (CUDA)', 'CPU'])
    // Blueprint `:123-124`'s two strings deliberately stay out of i18n (same family as N22)
    // → in source they are **bare literals**, not passed through t().
    // Warning: don't flip this into asserting "the locale file has no key whose value is
    // 'CPU'" — this repo's locale file genuinely has another key whose value happens to be
    // 'CPU' (hardware-related copy), unrelated to this page. The discriminator is **how this
    // page's own source is written**.
    const src: string = readFileSync(resolve(__dirname, './ParserStatus.vue'), 'utf8')
    expect(src).toContain("{ value: 'cuda', label: 'GPU (CUDA)' }")
    expect(src).toContain("{ value: 'cpu', label: 'CPU' }")
    expect(Object.values(zhCn as Record<string, unknown>)).not.toContain('GPU (CUDA)')
  })

  it('🔴 both sides of :checked — with device:"auto", only the first option is true', async () => {
    const w = await mountPage()
    const els = w.findAll('.device-row input').map((n) => n.element as HTMLInputElement)
    expect(els.map((el) => el.checked)).toEqual([true, false, false])
    expect(els.map((el) => el.getAttribute('value'))).toEqual(['auto', 'cuda', 'cpu'])
  })

  it('🔴 both sides of :checked — fixture variant device:"cpu", only the third option is true', async () => {
    ai.parserState.mockResolvedValue({ ...STATE, device: 'cpu' })
    const w = await mountPage()
    const els = w.findAll('.device-row input').map((n) => n.element as HTMLInputElement)
    expect(els.map((el) => el.checked)).toEqual([false, false, true])
  })

  it('device=auto + resolved_device=cpu → .resolved-hint renders "→ 实际 CPU" (toUpperCase)', async () => {
    const w = await mountPage()
    expect(w.find('.device-row .resolved-hint').text()).toBe('→ 实际 CPU')
  })

  it('when device is not auto, .resolved-hint does not render at all (v-if, first half)', async () => {
    ai.parserState.mockResolvedValue({ ...STATE, device: 'cpu' })
    const w = await mountPage()
    expect(w.find('.device-row .resolved-hint').exists()).toBe(false)
  })

  it('device=auto but resolved_device is an empty string → also does not render (v-if, second half)', async () => {
    ai.parserState.mockResolvedValue({ ...STATE, resolved_device: '' })
    const w = await mountPage()
    expect(w.find('.device-row .resolved-hint').exists()).toBe(false)
  })

  it('@change → setDevice(opt.value)', async () => {
    const w = await mountPage()
    await w.findAll('.device-row input')[1]!.trigger('change')
    await flushPromises()
    expect(ai.parserControl).toHaveBeenCalledWith({ action: 'set_device', device: 'cuda' })
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus — control card: OCR toggle (blueprint :56-65)', () => {
  it('copy + N21\'s mistranslated hint, copied verbatim ("真实索引的扫描件" is a mistranslation baked into the locale file itself)', async () => {
    const w = await mountPage()
    expect(w.find('.checkbox').text()).toBe('扫描 PDF 启用 OCR (RapidOCR)')
    // The last line's .resolved-hint is the OCR hint (the first one is in .device-row)
    const hints = w.findAll('.control-card .resolved-hint')
    expect(hints[hints.length - 1]!.text()).toBe('慢 5-10x，只对真实索引的扫描件有用')
  })

  // 🔴 M-3 (review, 2026-08-04): these two states used to be crammed into one `it()`, swapping
  // in a second pinia instance halfway through — inconsistent with the rest of this file's
  // "one state per test" convention (concurrency / device are both split out). Split into two.
  it('🔴 both sides of :checked (one) — real device ocr_enabled:false → checked is false', async () => {
    const w = await mountPage()
    expect((w.find('.checkbox input').element as HTMLInputElement).checked).toBe(false)
  })

  it('🔴 both sides of :checked (two) — fixture variant ocr_enabled:true → checked is true', async () => {
    ai.parserState.mockResolvedValue({ ...STATE, ocr_enabled: true })
    const w = await mountPage()
    expect((w.find('.checkbox input').element as HTMLInputElement).checked).toBe(true)
  })

  it('@change reads from $event.target.checked → setOcr(true) / setOcr(false)', async () => {
    const w = await mountPage()
    const box = w.find('.checkbox input')
    ;(box.element as HTMLInputElement).checked = true
    await box.trigger('change')
    await flushPromises()
    expect(ai.parserControl).toHaveBeenLastCalledWith({ action: 'set_ocr', enabled: true })
    ;(box.element as HTMLInputElement).checked = false
    await box.trigger('change')
    await flushPromises()
    expect(ai.parserControl).toHaveBeenLastCalledWith({ action: 'set_ocr', enabled: false })
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus — queue card, 6 cells (blueprint :68-76)', () => {
  it('all six cells\' text verbatim (N16: every emoji sits outside t()), numbers taken from real device measurements', async () => {
    const w = await mountPage()
    const kvs = w.findAll('.queue-card .kv')
    expect(kvs).toHaveLength(6)
    expect(kvs.map((k) => k.text())).toEqual([
      '⏳ 待处理 339',
      '🔄 处理中 1',
      '✅ 完成 9',
      '❌ 已失败 0',
      '📦 已入向量 5592',
      // formatCursor goes through toLocaleString(), which varies with the running
      // environment's locale/timezone → compute it live rather than pinning it
      `📍 上次同步 ${new Date(1784775953391).toLocaleString()}`,
    ])
  })

  it('each of the six cells\' numbers sits inside a <b> (blueprint has `<b>{{…}}</b>` per cell)', async () => {
    const w = await mountPage()
    const bs = w.findAll('.queue-card .kv b')
    expect(bs).toHaveLength(6)
    expect(bs.map((b) => b.text())).toEqual([
      '339', '1', '9', '0', '5592', new Date(1784775953391).toLocaleString(),
    ])
  })

  it('formatCursor(0) → U+2014 em dash (blueprint :147\'s `if (!ms) return "—"`)', async () => {
    ai.parserStats.mockResolvedValue({ ...STATS, last_cursor_ms: 0 })
    const w = await mountPage()
    const last = w.findAll('.queue-card .kv')[5]!
    expect(last.find('b').text()).toBe('—')
    expect(last.text()).toBe('📍 上次同步 —')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus — folders card (blueprint :78-89)', () => {
  it('the title\'s two placeholders each have a distinct source: {top} = list length 20, {total} = backend total_groups 119', async () => {
    const w = await mountPage()
    expect(w.find('.folders-card h3').text()).toBe('待处理文件夹（top 20 / 共 119 组）')
  })

  it('takes the v-else list branch: 20 rows, each with path + count + progress bar', async () => {
    const w = await mountPage()
    expect(w.find('.folders-card .empty').exists()).toBe(false)
    const rows = w.findAll('.folder-row')
    expect(rows).toHaveLength(20)
    expect(rows[0]!.find('.folder-path').text()).toBe(
      '/DATA/.system_data/home/nimo/.claude/plugins/marketplaces/claude-plugins-official/.github/workflows',
    )
    expect(rows[0]!.find('.folder-count').text()).toBe('18')
    expect(rows[19]!.find('.folder-count').text()).toBe('4')
  })

  it('barWidth: max item is 100%, last item is round(4/18*100)=22%', async () => {
    const w = await mountPage()
    const bars = w.findAll('.folder-bar')
    expect(bars).toHaveLength(20)
    expect(bars[0]!.attributes('style')).toBe('width: 100%;')
    expect(bars[19]!.attributes('style')).toBe('width: 22%;')
  })

  it('🔴 barWidth\'s `|| 1` fallback: when every count is 0, width is 0% (not NaN%)', async () => {
    // Discriminator: drop `|| 1` → reduce yields 0 → 0/0 = NaN → `width: NaN%` gets judged
    // invalid by jsdom → the style attribute never reads 'width: 0%;' → this test fails.
    ai.parserFolders.mockResolvedValue({
      folders: [
        { root_id: 'r', folder: '/DATA/a', count: 0 },
        { root_id: 'r', folder: '/DATA/b', count: 0 },
      ],
      total_groups: 2,
    })
    const w = await mountPage()
    const bars = w.findAll('.folder-bar')
    expect(bars).toHaveLength(2)
    expect(bars[0]!.attributes('style')).toBe('width: 0%;')
    expect(bars[1]!.attributes('style')).toBe('width: 0%;')
  })

  it('v-if empty state: folders empty → "无待处理", zero .folder-row (governance §13: unreachable on the real device, covered via mock)', async () => {
    ai.parserFolders.mockResolvedValue({ folders: [], total_groups: 0 })
    const w = await mountPage()
    expect(w.find('.folders-card .empty').text()).toBe('无待处理')
    expect(w.findAll('.folder-row')).toHaveLength(0)
    expect(w.find('.folders-card h3').text()).toBe('待处理文件夹（top 0 / 共 0 组）')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus — failures card + N19 three states (blueprint :91-102)', () => {
  // 🔴 N19: `<ul v-show="failedOpen" v-if="store.failedJobs.length">` has both directives
  // attached at once. In Vue, `v-if` takes priority over `v-show` → with an empty bucket the
  // whole `<ul>` doesn't render at all, so `v-show` is dead code.
  // Discriminator: merge into a single directive (keep only v-show, or only v-if) → at least
  // one of the three tests in this group must then fail.
  it('N19 state ①: real device has an empty bucket — collapse button renders unconditionally and is clickable ("▶ 最近失败（0）"), but the <ul> still doesn\'t render at all after opening it', async () => {
    const w = await mountPage()
    const btn = w.find('.failures-card .toggle')
    expect(btn.exists()).toBe(true)
    expect(btn.text()).toBe('▶ 最近失败（0）')
    expect(w.find('.failure-list').exists()).toBe(false)

    await btn.trigger('click')
    await nextTick()
    // The arrow flipped (proving failedOpen really did get set true and the button is
    // genuinely clickable)
    expect(w.find('.failures-card .toggle').text()).toBe('▼ 最近失败（0）')
    // But the list still doesn't exist — this is **correct behavior** (v-if short-circuits
    // first), not a defect (governance §13)
    expect(w.find('.failure-list').exists()).toBe(false)
  })

  it('N19 state ②: non-empty bucket + not expanded — <ul> does render, but hidden by v-show (display: none)', async () => {
    ai.parserJobs.mockResolvedValue({ jobs: [FAILED_ROW] })
    const w = await mountPage()
    const ul = w.find('.failure-list')
    expect(ul.exists()).toBe(true)
    expect((ul.element as HTMLElement).style.display).toBe('none')
    expect(w.find('.failures-card .toggle').text()).toBe('▶ 最近失败（1）')
  })

  it('N19 state ③: non-empty bucket + expanded — <ul> visible, row has path + truncated error', async () => {
    ai.parserJobs.mockResolvedValue({ jobs: [{ ...FAILED_ROW, last_error: 'boom' }] })
    const w = await mountPage()
    await w.find('.failures-card .toggle').trigger('click')
    await nextTick()
    const ul = w.find('.failure-list')
    expect((ul.element as HTMLElement).style.display).toBe('')
    const lis = ul.findAll('li')
    expect(lis).toHaveLength(1)
    expect(lis[0]!.find('.path').text()).toBe('/DATA/.system_data/tmp/nimoos_panic.log')
    expect(lis[0]!.find('.error').text()).toBe('boom')
    expect(w.find('.failures-card .toggle').text()).toBe('▼ 最近失败（1）')
  })

  it('truncateErr boundary: 120 chars passes through unchanged, 121 chars truncates to the first 120 + U+2026 (blueprint :156 is strictly `> 120`)', async () => {
    const e120 = 'x'.repeat(120)
    const e121 = 'y'.repeat(121)
    ai.parserJobs.mockResolvedValue({
      jobs: [
        { ...FAILED_ROW, id: 1, last_error: e120 },
        { ...FAILED_ROW, id: 2, last_error: e121 },
      ],
    })
    const w = await mountPage()
    await w.find('.failures-card .toggle').trigger('click')
    await nextTick()
    const errs = w.findAll('.failure-list .error')
    expect(errs).toHaveLength(2)
    expect(errs[0]!.text()).toBe(e120) // exactly 120 → not truncated
    expect(errs[0]!.text()).toHaveLength(120)
    expect(errs[1]!.text()).toBe('y'.repeat(120) + '…') // 121 → truncated + ellipsis
    expect(errs[1]!.text()).toHaveLength(121)
  })

  it('truncateErr null value: last_error is null (a real measured row on the device) → renders an empty string, not "null"', async () => {
    ai.parserJobs.mockResolvedValue({ jobs: [FAILED_ROW] }) // FAILED_ROW.last_error === null
    const w = await mountPage()
    await w.find('.failures-card .toggle').trigger('click')
    await nextTick()
    expect(w.find('.failure-list .error').text()).toBe('')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus — N20: 5-second polling + document.hidden guard + unmount cleanup (blueprint :127-135)', () => {
  // Following the existing convention from `QueueView.test.ts:859-891`: `onMounted`'s
  // `loadAll()` fires its calls synchronously (the four `service.ai.parser*` calls inside
  // `Promise.all` trigger synchronously; only their individual resolutions go through a
  // microtask), so there's no need to "nudge" things with `runOnlyPendingTimersAsync` — that
  // API would also fire a not-yet-due setInterval early, which would be misread as an extra
  // round of calls.
  it('the interval really is 5000ms: advancing 4999ms fires nothing, one more ms fires one round', async () => {
    vi.useFakeTimers()
    try {
      const router = makeRouter()
      await router.isReady()
      const w = mount(ParserStatus, { global: { plugins: [router, i18n] } } as never)
      expect(ai.parserStats).toHaveBeenCalledTimes(1) // fires once immediately on mount

      ai.parserStats.mockClear()
      vi.advanceTimersByTime(4999)
      expect(ai.parserStats).not.toHaveBeenCalled()
      vi.advanceTimersByTime(1)
      expect(ai.parserStats).toHaveBeenCalledTimes(1)

      // One more tick (proves it's a setInterval, not a setTimeout)
      ai.parserStats.mockClear()
      vi.advanceTimersByTime(5000)
      expect(ai.parserStats).toHaveBeenCalledTimes(1)
      w.unmount()
    } finally {
      vi.useRealTimers()
    }
  })

  it('🔴 skips a tick while document.hidden is true; resumes once it goes back to false', async () => {
    // Discriminator: remove the `if (!document.hidden)` guard → the middle stretch would
    // fire a request → this test fails.
    vi.useFakeTimers()
    const hidden = vi.spyOn(document, 'hidden', 'get').mockReturnValue(false)
    try {
      const router = makeRouter()
      await router.isReady()
      const w = mount(ParserStatus, { global: { plugins: [router, i18n] } } as never)
      ai.parserStats.mockClear()

      hidden.mockReturnValue(true)
      vi.advanceTimersByTime(15000) // all three ticks skipped
      expect(ai.parserStats).not.toHaveBeenCalled()

      hidden.mockReturnValue(false)
      vi.advanceTimersByTime(5000)
      expect(ai.parserStats).toHaveBeenCalledTimes(1)
      w.unmount()
    } finally {
      hidden.mockRestore()
      vi.useRealTimers()
    }
  })

  it('🔴 onBeforeUnmount clears the timer: no more requests fire after unmount no matter how far time advances', async () => {
    vi.useFakeTimers()
    try {
      const router = makeRouter()
      await router.isReady()
      const w = mount(ParserStatus, { global: { plugins: [router, i18n] } } as never)
      vi.advanceTimersByTime(5000)
      expect(ai.parserStats).toHaveBeenCalledTimes(2) // mounted + one tick

      w.unmount()
      ai.parserStats.mockClear()
      vi.advanceTimersByTime(60000) // 12 ticks
      expect(ai.parserStats).not.toHaveBeenCalled()
    } finally {
      vi.useRealTimers()
    }
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus — N16 emoji / symbol placement audit (none may move into or out of t())', () => {
  it('the i18n key values themselves contain zero emoji / zero arrow symbols (proving the symbols live in the template or script, not in the locale file)', () => {
    const t = i18n.global.t as unknown as (k: string) => string
    // The two that are concatenated by script (blueprint :27)
    expect(t('aiKbResume')).toBe('恢复')
    expect(t('aiKbPause')).toBe('暂停')
    // The key values belonging to the seven emoji that sit outside t() (blueprint :6 / :70-75)
    expect(t('aiKbPrTestLink')).toBe('测试沙盒')
    expect(t('aiKbPending')).toBe('待处理')
    expect(t('aiKbPrQueueRunning')).toBe('处理中')
    expect(t('aiKbPrQueueDone')).toBe('完成')
    expect(t('aiKbFailed')).toBe('已失败')
    expect(t('aiKbPrIndexedVectors')).toBe('已入向量')
    expect(t('aiKbLastSynced')).toBe('上次同步')
    for (const k of [
      'aiKbResume', 'aiKbPause', 'aiKbPrTestLink', 'aiKbPending', 'aiKbPrQueueRunning',
      'aiKbPrQueueDone', 'aiKbFailed', 'aiKbPrIndexedVectors', 'aiKbLastSynced',
      'aiKbPrRecentFailures',
    ]) {
      expect(t(k)).not.toMatch(/[🧪⏳🔄✅❌📦📍▼▶⏸]/u)
    }
    // 🔴 Conversely: `→` **is** in the key value (blueprint :53's `$t('→ actual {device}')`),
    //    not in the template. Read the raw locale string here (going through `t()` would eat
    //    `{device}` as a missing param).
    expect((zhCn as Record<string, string>).aiKbPrResolvedHint).toBe('→ 实际 {device}')
  })

  it('in the template, exactly one space sits between the emoji and the translation, in the order "symbol → copy"', async () => {
    const w = await mountPage()
    expect(w.find('a.test-link').text()).toBe('🧪 测试沙盒')
    // Warning: don't use `slice(0, 2)` to grab the leading character: 🔄/📦/📍 are non-BMP
    //    code points (2 UTF-16 units each), while ⏳/✅/❌ are BMP (1 unit each) — slicing by
    //    unit would cut out different lengths. Use a regex with the `u` flag.
    expect(w.findAll('.queue-card .kv').map((k) => k.text())).toEqual([
      expect.stringMatching(/^⏳ \S/u),
      expect.stringMatching(/^🔄 \S/u),
      expect.stringMatching(/^✅ \S/u),
      expect.stringMatching(/^❌ \S/u),
      expect.stringMatching(/^📦 \S/u),
      expect.stringMatching(/^📍 \S/u),
    ])
    expect(w.find('.pause-btn').text().startsWith('▶ ')).toBe(true)
    expect(w.find('.failures-card .toggle').text().startsWith('▶ ')).toBe(true)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserStatus — guard gap ③: zero bare color literals in the <template> block', () => {
  // Governance §9 gap ③: `color-guard.test.ts:44-56`'s `styleLines()` only extracts `.vue`
  // `<style>` blocks → template `style=` / `:style=` attributes get zero scanning; this file
  // adds a targeted assertion to plug that blind spot.
  // Warning: sticks with the existing approach (non-greedy + implicitly anchored on
  // "`</template>` sits in column 0", precedent set by `QueueView.test.ts` /
  // `IndexedFilesView.test.ts` / `FolderBrowser.test.ts`); governance §9 gap ③′'s
  // "switch uniformly to greedy matching + a coverage self-check" belongs to **T8** — this
  // pass leaves it alone.
  // 🔴 Reads the source file with `node:fs`, not Vite's `?raw`.
  it('the <template> block (after stripping var()/color-mix()) contains no bare hex / rgb / hsl literals', () => {
    const src: string = readFileSync(resolve(__dirname, './ParserStatus.vue'), 'utf8')
    const m = /<template>([\s\S]*?)\n<\/template>/.exec(src)
    expect(m).not.toBeNull()
    const tmpl = m![1]
    // Coverage self-check: the extracted slice must contain characteristic strings from both
    // the template's **head** and **tail**.
    // This component's only nested `<template v-else>` carries an attribute (so it's not a
    // bare `<template>`), and its closing tag is also indented → it won't cause the column-0
    // `</template>` to truncate the match early.
    expect(tmpl).toContain('aiKbPrDetailsTitle') // head (page header h2)
    expect(tmpl).toContain('truncateErr(j.last_error)') // tail (last line of the failures card)

    // Strip the insides of var(...) and color-mix(...) (same technique as
    // color-guard.test.ts's stripVar: scan character by character tracking paired-bracket
    // depth, supporting nested fallbacks)
    function stripCalls(s: string, prefixes: string[]): string {
      let out = ''
      let i = 0
      while (i < s.length) {
        const hit = prefixes.find((p) => s.startsWith(p, i))
        if (hit) {
          let depth = 0
          let j = i + hit.length - 1 // lands on the opening bracket
          for (; j < s.length; j++) {
            if (s[j] === '(') depth++
            else if (s[j] === ')') {
              depth--
              if (depth === 0) {
                j++
                break
              }
            }
          }
          i = j
        } else {
          out += s[i]
          i++
        }
      }
      return out
    }
    const scrubbed = stripCalls(tmpl, ['var(', 'color-mix('])
    expect(scrubbed).not.toMatch(/#[0-9a-fA-F]{3,8}\b/)
    expect(scrubbed).not.toMatch(/\b(rgba?|hsla?)\s*\(/)
  })

  it('this file has zero <style> blocks (K24: styling lives in parser-styles.scss, imported on the JS side)', () => {
    const src: string = readFileSync(resolve(__dirname, './ParserStatus.vue'), 'utf8')
    expect(src).not.toMatch(/^<style/m)
    expect(src).toContain("import '../../styles/parser-styles.scss'")
  })

  it('zero KIcon (governance §1.2 / N16: neither Parser page blueprint uses a KIcon)', async () => {
    const src: string = readFileSync(resolve(__dirname, './ParserStatus.vue'), 'utf8')
    expect(src).not.toMatch(/^import KIcon/m)
    const w = await mountPage()
    expect(w.findAll('svg')).toHaveLength(0)
  })
})
