// SP8-P5c Task 7 — component test for `ParserTest.vue` (Parser test sandbox).
// Blueprint: `NimoOS-UI` (main@7a6ee6b7) `src/views/AI/Parser/ParserTest.vue` (369 lines;
// this cut covers template `:1-152` + script `:154-243`; `<style>` `:245-369` goes to T2b).
//
// ═══ mock strategy (governance §4.1 requires explicit documentation) ═══
// This page **uses no store** (all 10 items from blueprint data() are page-level transient state) →
// the only thing to mock is the shared package's `service.ai.parserTestAnalyze`.
// 🔴 It only does `return res.data` in the package (`NimoOS-Service/src/ai.ts:673-680`, zero transformation)
// → mock it here as **raw HTTP snake_case**, matching the fixture literally. **Must have identical
// shapes across `ParserStatus.test.ts` / `parserStore.test.ts` / `knowledgeStore.parser.test.ts`
// `service.ai.parser*` methods** (governance §4.1 red flag self-check: same method mocked as different
// shapes across test files = time bomb). For failure cases, use `mockRejectedValue` to create
// errors with `response.data.detail` shaped after **actual response bodies** from four `.http` fixtures.
//
// ═══ fixtures are copies, not runtime reads (governance §4.4) ═══
// Six data sets copied verbatim into the `FIXTURE-COPY-BEGIN/END` blocks below with citations,
// **do not read `.superpowers/` with `node:fs`** — that directory is gitignored (SP7 lost it entirely),
// and this branch will merge to master; tests in `src/` with cross-boundary dependencies silently
// fail with "file not found". 🔴 Copy generated by one-time script from fixtures (zero hand transcription),
// equivalence verified by **automated byte-for-byte validation** (script and output in T7 report §5)
// — not visual comparison. Reading `.vue` source files (guard gaps③ and N22 cases) still uses `node:fs`,
// **never Vite's `?raw`** (vitest's CSSEnablerPlugin replaces style source with empty string → assertions
// "pass" on empty string; precedent: `knowledgeStyles.test.ts` comment③).
//
// 🔴 **The 6th fixture (422) is only copied in comments, no constant, no test case** — see the
//    "why 422 is not tested" note before the final `describe`. Copy (verbatim, from
//    `p5c-fixtures/parser-test-analyze-422-no-file.http` response body):
//        {"detail":[{"type":"missing","loc":["body","file"],"msg":"Field required","input":null}]}
//    🔴 `detail` is **an array** (FastAPI validation error), differing from the two 400s' string `detail`
//    contract (governance §8.2 has backend ticket). **But UI cannot reach this branch**: submit button
//    `:disabled="!file || loading"` (blueprint :76) blocks "submit without choosing file"; `submit()` start
//    `if (!this.file) return` (:202) blocks again → governance §4.2 / §5.1 mandate:
//    **copy the value chain as-is, add no array branch, write no unit test for it** (testing a path UI
//    cannot reach = wasted effort).
//
// ═══ assertion calibration (governance §9) ═══
// `:disabled` is **a boolean attribute**: Vue renders `disabled=""` when true, omits the attribute when false →
// `attributes('disabled')` false side can only be `undefined`, but governance §9 **forbids `toBeUndefined()`**.
// So assert **DOM properties** always (`el.disabled`), which are naturally true/false comparable values on both sides.
// Other text/href/class: compare as strings directly. Multi-line template `text()` normalized with `sq()` then compared character-for-character.
// 🔴 Negation assertions (`not.toContain` / `not.toMatch`) always call `blankComments()` first to strip comments
// (governance §9 clause 9: negation assertion hitting comment = **false positive**, misleads into "fixing" working code —
//  this file's head comment itself has `service.ai.parserTestAnalyze(fd)` / `rerank top-20` etc.),
// and pin **call shape** not bare identifiers. Use **line-preserving strip** (replace comment content with equal spaces,
// keep newlines), governance §9 clause 8.
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import { nextTick } from 'vue'
import { createRouter, createWebHashHistory } from 'vue-router'
import { i18n } from '../../../i18n'
import zhCn from '../../../i18n/zh_cn'
import enUs from '../../../i18n/en_us'
import ParserTest from './ParserTest.vue'
import { readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

// ── vi.hoisted mock skeleton (governance §9: avoid ESM hoisting TDZ) ──
const ai = vi.hoisted(() => ({
  parserTestAnalyze: vi.fn(),
}))
vi.mock('@nimotech/nimoos-service', () => ({ service: { ai } }))

// ═══════════════════════════════════════════════════════════════════════════
// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-test-analyze-md-ok.json  (complete)
// From `.superpowers/sdd/p5c-fixtures/parser-test-analyze-md-ok.json` (real device capture 2026-08-03,
// `POST /v1/parser/test/analyze`, `.md` + query=probe + rerank=false).
// 🔴 All four observed facts from governance §4.2 are in this one fixture:
//   ① **no `docling_markdown`** (.md does not go through docling) → entire docling card does not render
//   ② `scored[0]` has only `{chunk_no, cos_sim}`, **no `rerank_score`** → `rr {…}` does not render
//   ④ sent `overlap_tokens=80`, backend returns **0** per `chunker:"markdown"` → ok-hint echoes 0
const MD_OK = {
  "mime": "text/markdown",
  "filename": "p5c-probe.md",
  "size": 50,
  "text_length": 50,
  "chunk_count": 1,
  "chunks": [
    {"chunk_no":0,"text":"Sandbox probe A.\n\nSecond paragraph for chunk two.","token_count":12,"offset_start":0,"offset_end":50,"dense_preview":[-0.0309,0.0237,0.003,-0.0038,-0.0316,-0.0135,0.0212,0.0347],"sparse_top_terms":[{"token_id":151268,"weight":0.2153},{"token_id":11728,"weight":0.2056},{"token_id":6626,"weight":0.1726},{"token_id":7839,"weight":0.1494},{"token_id":77648,"weight":0.1463}]}
  ],
  "params_used": {"target_tokens":600,"overlap_tokens":0,"min_tokens":2,"chunker":"markdown"},
  "query": "probe",
  "scored": [
    {"chunk_no":0,"cos_sim":0.5082847161344183}
  ]
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-test-analyze-txt-rerank.json  (complete)
// From `.superpowers/sdd/p5c-fixtures/parser-test-analyze-txt-rerank.json` (2026-08-03,
// `.txt` + query=vector search + **rerank=true**).
// 🔴 Fact③: local reranker is broken → `rerank_error` always present, `scored[0]` **still has no `rerank_score`**
//   (backend defect, governance §8.2 has ticket, this period copy frontend as-is, no fix, no workaround).
// 🔴 Other half of fact④: `chunker:"plain"` → `overlap_tokens` **returns unchanged at 10**.
const TXT_RERANK = {
  "mime": "text/plain",
  "filename": "p5c-probe.txt",
  "size": 196,
  "text_length": 196,
  "chunk_count": 1,
  "chunks": [
    {"chunk_no":0,"text":"Alpha beta gamma delta epsilon. Zeta eta theta iota kappa lambda mu nu xi omicron pi rho sigma tau upsilon phi chi psi omega.\nSecond line about vector search and embeddings for the sandbox probe.","token_count":48,"offset_start":0,"offset_end":196,"dense_preview":[-0.0584,-0.0225,-0.0411,0.0148,0.0028,-0.0604,0.0148,0.0051],"sparse_top_terms":[{"token_id":87506,"weight":0.2414},{"token_id":11728,"weight":0.2239},{"token_id":4759,"weight":0.2124},{"token_id":40703,"weight":0.2122},{"token_id":99245,"weight":0.2056}]}
  ],
  "params_used": {"target_tokens":50,"overlap_tokens":10,"min_tokens":2,"chunker":"plain"},
  "rerank_error": "XLMRobertaTokenizer has no attribute prepare_for_model",
  "query": "vector search",
  "scored": [
    {"chunk_no":0,"cos_sim":0.5408997321381046}
  ]
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-test-analyze-200-empty-file.http  (response body)
// From `.superpowers/sdd/p5c-fixtures/parser-test-analyze-200-empty-file.http` (2026-08-03,
// sending a 0-byte `.md` file). 🔴 **HTTP 200** (not an error) + `chunk_count:0` / `chunks:[]` /
// **no `query`, no `scored`** → follows blueprint :129's `.empty` empty state. Governance §13: **real device verifiable** ✅
const EMPTY_200 = {
  "mime": "text/markdown",
  "filename": "p5c-empty.md",
  "size": 0,
  "text_length": 0,
  "chunk_count": 0,
  "chunks": [],
  "params_used": {"target_tokens":600,"overlap_tokens":0,"min_tokens":2,"chunker":"markdown"}
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-test-analyze-400-target-tokens.http  (response body)
// From `…-400-target-tokens.http` (2026-08-03, `target_tokens=1` out of bounds). HTTP **400**,
// `detail` is **a string** → blueprint :222's value chain picks it up, goes into `.error-box`.
const ERR_400_TARGET = {
  "detail": "target_tokens must be in [50, 4000]"
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-test-analyze-400-bad-ext.http  (response body)
// From `…-400-bad-ext.http` (2026-08-03, sending `.bin`). HTTP **400**, `detail` is a string.
const ERR_400_EXT = {
  "detail": "extension '.bin' not supported in test sandbox; use .md / source code / .txt / .html / .json / .csv / .log / .pdf / .docx / .pptx / .xlsx"
}
// FIXTURE-COPY-END
// ═══════════════════════════════════════════════════════════════════════════

/** Normalize whitespace in multi-line templates (Vue's condense already collapses newlines to single space, but `text()` may still leave indentation). */
function sq(s: string): string {
  return s.replace(/\s+/g, ' ').trim()
}

/**
 * "Line-preserving" comment stripping (governance §9 clause 8): replace comment content with equal spaces,
 * **preserve all newlines** — deletion-based stripping eats newlines too, causing line numbers in reports
 * to shift by tens of lines. Covers `<!-- -->` (template) and `/* */` (script); this file's `.vue` has no `//` line comments,
 * so `//` is not handled (would need to distinguish `//` inside strings, not worth it).
 */
function blankComments(src: string): string {
  return src.replace(/<!--[\s\S]*?-->|\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, ' '))
}

function readSrc(): string {
  return readFileSync(resolve(__dirname, './ParserTest.vue'), 'utf8')
}

/** Create a File with specified size (jsdom's `File.size` is read-only → use defineProperty to override). */
function makeFile(name: string, size: number, type = 'text/markdown'): File {
  const f = new File(['x'], name, { type })
  Object.defineProperty(f, 'size', { value: size, configurable: true })
  return f
}

function makeRouter() {
  const router = createRouter({
    history: createWebHashHistory('/app/'),
    routes: [
      { path: '/ai/parser/test', name: 'AIParserTest', component: ParserTest },
      // Blueprint :5's `router-link to="/ai/parser"` needs target route to exist to resolve href.
      // [Correction, SP8-P5d Task 9, governance §15.2 / plan §T9 clause 6] Previous comment is obsolete:
      // in production these two top-level parser routes reversed long ago to actual ParserStatus/ParserTest
      // (output of P5c-T10, knowledgeRoutes.ts head comment has full record), no longer point to placeholder.
      // This test file's stub component is just a placeholder in this file's own route table, unrelated
      // to whether production routes are placeholders — keep stub because this file only cares that href resolves.
      { path: '/ai/parser', name: 'AIParser', component: { template: '<div />' } },
    ],
  })
  router.push('/ai/parser/test')
  return router
}

const mountedWrappers: Array<ReturnType<typeof mount>> = []

async function mountPage() {
  const router = makeRouter()
  await router.isReady()
  const w = mount(ParserTest, { global: { plugins: [router, i18n] } } as never)
  mountedWrappers.push(w)
  return w
}

type W = Awaited<ReturnType<typeof mountPage>>

/** Follow the real `<input type="file">` change path (not by calling component methods directly). */
async function pickFile(w: W, f: File): Promise<void> {
  const input = w.find('input[type="file"]')
  Object.defineProperty(input.element, 'files', { value: [f], configurable: true })
  await input.trigger('change')
  await nextTick()
}

/** Pick file → click submit → wait for promise. */
async function runWith(w: W, f = makeFile('p5c-probe.md', 50)): Promise<void> {
  await pickFile(w, f)
  await w.find('.submit-btn').trigger('click')
  await flushPromises()
  await nextTick()
}

/** Get FormData from this call and replace File values with comparable strings. */
function lastFormEntries(): Array<[string, string]> {
  const calls = ai.parserTestAnalyze.mock.calls
  const fd = calls[calls.length - 1]![0] as FormData
  return Array.from(fd.entries()).map(([k, v]) => [
    k,
    typeof v === 'string' ? v : `File(${(v as File).name},${(v as File).size})`,
  ]) as Array<[string, string]>
}

/** Create an "axios-style" HTTP error (with `response.data`), shaped after `.http` fixture. */
function httpError(status: number, data: unknown, message = `Request failed with status code ${status}`) {
  return Object.assign(new Error(message), { response: { status, data } })
}

function deferred<T>() {
  let resolve!: (v: T) => void
  const promise = new Promise<T>((res) => {
    resolve = res
  })
  return { promise, resolve }
}

beforeEach(() => {
  vi.clearAllMocks()
  ai.parserTestAnalyze.mockResolvedValue(MD_OK)
})

afterEach(() => {
  while (mountedWrappers.length) mountedWrappers.pop()!.unmount()
  document.body.innerHTML = ''
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — K31 two-layer root element (scroll container + 900px centered column)', () => {
  // 🔴 Governance §3 K31: `.parser-app` is **outer wrapper**, page root class `.parser-test-page` is **inner**.
  // Squashing into one element puts the `overflow-y:auto` scrollbar at the right edge of the 900px centered column
  // (roughly screen center on wide screens), whereas Vue2 scrolls the whole page with scrollbar at viewport's right edge
  // = user-visible interface not 1:1. ⚠️ Plan §T7 still shows pre-K31 single-element style (governance §12.3 E-14 same family),
  // already superseded by K31. Test criterion: rewrite two classes back into one element → both tests in this group must fail.
  it('root element only has .parser-app (not .parser-test-page)', async () => {
    const w = await mountPage()
    const root = w.element as HTMLElement
    expect(root.tagName).toBe('DIV')
    expect(root.className).toBe('parser-app')
    expect(root.classList.contains('parser-test-page')).toBe(false)
  })

  it('.parser-test-page is direct child of .parser-app, and exactly one of each', async () => {
    const w = await mountPage()
    expect(w.findAll('.parser-app')).toHaveLength(1)
    expect(w.findAll('.parser-test-page')).toHaveLength(1)
    expect(w.find('.parser-app > .parser-test-page').exists()).toBe(true)
    // Page content is actually in inner layer (not empty shell)
    expect(w.find('.parser-test-page > .page-header').exists()).toBe(true)
    expect(w.find('.parser-test-page > .upload-card').exists()).toBe(true)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — page header + help card (blueprint :3-18)', () => {
  it('title exact match, back link `← Back to details` with href (N16: `←` outside t(); page title no emoji)', async () => {
    const w = await mountPage()
    expect(w.find('.page-header h2').text()).toBe('Parser test sandbox')
    const link = w.find('a.back-link')
    expect(link.text()).toBe('← Back to details')
    // hash router: href resolved in jsdom is pure hash (production is `…/app/#/ai/parser`)
    expect(link.attributes('href')).toBe('#/ai/parser')
    // 🔴 brief §4.3 says page title has `🧪` — source verification shows wrong (E-15): `🧪` is at
    //    `ParserStatus.vue:6` and `SettingsView.vue:162`, this page's h2 is pure translation.
    expect(w.find('.page-header').text()).not.toContain('🧪')
  })

  it('help card first paragraph: three keys + bare comma after `<strong>` + bare period at end', async () => {
    const w = await mountPage()
    const ps = w.findAll('.help-card p')
    expect(ps).toHaveLength(2)
    expect(sq(ps[0]!.text())).toBe(
      'Upload a file to see how Parser processes it (chunking + embedding + scoring). Does not write to index, preview only.',
    )
    expect(ps[0]!.find('strong').text()).toBe('Does not write to index')
  })

  it('help card second paragraph: two `<code>` extension lists are technical identifiers (N22), not in i18n', async () => {
    const w = await mountPage()
    const p = w.findAll('.help-card p')[1]!
    expect(p.classes()).toContain('small')
    const codes = p.findAll('code')
    expect(codes).toHaveLength(2)
    expect(codes[0]!.text()).toBe('.md .txt .html .json .csv .py .go .ts .java')
    expect(codes[1]!.text()).toBe('.pdf .docx .pptx .xlsx')
    expect(sq(p.text())).toBe(
      'Supports .md .txt .html .json .csv .py .go .ts .java, and .pdf .docx .pptx .xlsx (converted to markdown via docling). ' +
        'Maximum 30 MB. PDF will trigger model weight download on first use (~200 MB, one-time).',
    )
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — drop zone three states + dragActive class toggle (blueprint :22-26)', () => {
  it('dragover adds .active, dragleave removes it (`:class="{ active: dragActive }"`)', async () => {
    const w = await mountPage()
    const dz = w.find('.dropzone')
    expect(dz.classes()).not.toContain('active')
    await dz.trigger('dragover')
    expect(w.find('.dropzone').classes()).toContain('active')
    await dz.trigger('dragleave')
    expect(w.find('.dropzone').classes()).not.toContain('active')
  })

  it('drop: turn off highlight first, then get dataTransfer.files[0] and pass to onFile (blueprint onDrop :178-182)', async () => {
    const w = await mountPage()
    const dz = w.find('.dropzone')
    await dz.trigger('dragover')
    expect(w.find('.dropzone').classes()).toContain('active')

    await dz.trigger('drop', { dataTransfer: { files: [makeFile('dropped.md', 1234)] } })
    await nextTick()
    expect(w.find('.dropzone').classes()).not.toContain('active')
    // File actually entered → takes v-else branch .file-meta
    expect(w.find('.file-meta strong').text()).toBe('dropped.md')
  })

  it('drop but files empty → `if (f) onFile(f)` does not trigger, still no file selected state', async () => {
    const w = await mountPage()
    await w.find('.dropzone').trigger('drop', { dataTransfer: { files: [] } })
    await nextTick()
    expect(w.find('.file-meta').exists()).toBe(false)
    expect(w.find('.pick-btn').exists()).toBe(true)
  })

  it('`has` class follows `!!file` (absent when unselected, present when selected)', async () => {
    const w = await mountPage()
    expect(w.find('.dropzone').classes()).not.toContain('has')
    await pickFile(w, makeFile('a.md', 10))
    expect(w.find('.dropzone').classes()).toContain('has')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — pick file / clear (blueprint :27-37 / :183-197)', () => {
  it('no file selected: pick-btn + hint; click pick-btn forwards to hidden input click()', async () => {
    const w = await mountPage()
    expect(w.find('.pick-btn').text()).toBe('Choose file')
    expect(w.find('.dropzone .hint').text()).toBe('or drag and drop here')
    const input = w.find('input[type="file"]').element as HTMLInputElement
    const click = vi.spyOn(input, 'click').mockImplementation(() => {})
    await w.find('.pick-btn').trigger('click')
    expect(click).toHaveBeenCalledTimes(1)
    click.mockRestore()
  })

  it('file selected: file-meta shows name + fmtBytes(size) + × clear button (N16: `×` outside t())', async () => {
    const w = await mountPage()
    await pickFile(w, makeFile('p5c-probe.md', 50))
    expect(w.find('.pick-btn').exists()).toBe(false)
    expect(w.find('.file-meta strong').text()).toBe('p5c-probe.md')
    expect(w.find('.file-meta .hint').text()).toBe('50 B')
    expect(w.find('.clear-btn').text()).toBe('×')
  })

  it('clearFile triple-clears: file / result / error all cleared (blueprint :193-197)', async () => {
    const w = await mountPage()
    await runWith(w) // first get a result
    expect(w.find('.chunks-card').exists()).toBe(true)
    // then create an error (second submit fails)
    ai.parserTestAnalyze.mockRejectedValueOnce(httpError(400, ERR_400_TARGET))
    await w.find('.submit-btn').trigger('click')
    await flushPromises()
    await nextTick()
    expect(w.find('.error-box').exists()).toBe(true)

    await w.find('.clear-btn').trigger('click')
    await nextTick()
    expect(w.find('.file-meta').exists()).toBe(false) // file cleared
    expect(w.find('.chunks-card').exists()).toBe(false) // result cleared
    expect(w.find('.error-box').exists()).toBe(false) // error cleared
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — 🔴 30 MB frontend check: only set error, do not clear file, do not send request (blueprint :185-188)', () => {
  // Test criterion: change code before `return` to "conveniently clear file" → first test in this group must fail.
  it('exactly 30 MB (=30*1024*1024) is not rejected — boundary is strictly `>`', async () => {
    const w = await mountPage()
    await pickFile(w, makeFile('exactly30.md', 30 * 1024 * 1024))
    expect(w.find('.file-meta strong').text()).toBe('exactly30.md')
    expect(w.find('.error-box').exists()).toBe(false)
  })

  it('🔴 one byte over is rejected: show error box, **selected file and existing result remain unchanged**, zero requests', async () => {
    const w = await mountPage()
    // first select normal file and get a result
    await runWith(w, makeFile('good.md', 50))
    expect(w.find('.chunks-card').exists()).toBe(true)
    expect(ai.parserTestAnalyze).toHaveBeenCalledTimes(1)

    await pickFile(w, makeFile('huge.bin', 30 * 1024 * 1024 + 1))
    expect(w.find('.error-box').text()).toBe('File exceeds 30 MB, sandbox does not support')
    // 🔴 blueprint only does `return`: file was not cleared, result was not cleared
    expect(w.find('.file-meta strong').text()).toBe('good.md')
    expect(w.find('.chunks-card').exists()).toBe(true)
    // 🔴 no second request was sent
    expect(ai.parserTestAnalyze).toHaveBeenCalledTimes(1)
  })

  it('dropping an oversized file is also rejected (onDrop → onFile same code path)', async () => {
    const w = await mountPage()
    await w
      .find('.dropzone')
      .trigger('drop', { dataTransfer: { files: [makeFile('huge.md', 40 * 1024 * 1024)] } })
    await nextTick()
    expect(w.find('.error-box').text()).toBe('File exceeds 30 MB, sandbox does not support')
    expect(w.find('.file-meta').exists()).toBe(false)
    expect(ai.parserTestAnalyze).not.toHaveBeenCalled()
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — three parameter inputs + resetParams (blueprint :39-53 / :198-200)', () => {
  it('three <label> parameter names are technical identifiers (N22), input min/max/step copied verbatim', async () => {
    const w = await mountPage()
    const labels = w.findAll('.params-row .param')
    expect(labels).toHaveLength(3)
    expect(labels.map((l) => sq(l.text()))).toEqual(['target_tokens', 'overlap_tokens', 'min_tokens'])
    const attrs = labels.map((l) => {
      const el = l.find('input').element as HTMLInputElement
      return [el.type, el.getAttribute('min'), el.getAttribute('max'), el.getAttribute('step')]
    })
    expect(attrs).toEqual([
      ['number', '50', '4000', '50'],
      ['number', '0', '400', '10'],
      ['number', '1', '200', null], // min_tokens blueprint has no step
    ])
  })

  it('default values 600 / 80 / 2', async () => {
    const w = await mountPage()
    expect(w.findAll('.params-row .param input').map((i) => (i.element as HTMLInputElement).value)).toEqual([
      '600',
      '80',
      '2',
    ])
  })

  it('🔴 `v-model.number` all three truly convert to number (payload is `String(700)` not raw string path `"700"`)', async () => {
    const w = await mountPage()
    const ins = w.findAll('.params-row .param input')
    await ins[0]!.setValue('700')
    await ins[1]!.setValue('120')
    await ins[2]!.setValue('5')
    await runWith(w)
    const e = Object.fromEntries(lastFormEntries())
    expect(e.target_tokens).toBe('700')
    expect(e.overlap_tokens).toBe('120')
    expect(e.min_tokens).toBe('5')
    // 🔴 where does discriminating power come from: with integer input, `.number` and bare `v-model` have **identical**
    // payloads (`String(700)` and `String('700')` both give `'700'`) → that assertion has zero discriminating power.
    // Only **decimals with trailing zeros** differentiate: `.number` goes through `looseToNumber('600.50')` → number 600.5
    // → `String(600.5)` = `'600.5'`; bare `v-model` keeps string `'600.50'` as-is.
    // Test criterion: remove `.number` from all three → this test must fail.
    await ins[0]!.setValue('600.50')
    await w.find('.submit-btn').trigger('click')
    await flushPromises()
    expect(Object.fromEntries(lastFormEntries()).target_tokens).toBe('600.5')
    // pin source shape too (governance §9 clause 9: pin call shape)
    const src = blankComments(readSrc())
    expect(src).toContain('v-model.number="params.target_tokens"')
    expect(src).toContain('v-model.number="params.overlap_tokens"')
    expect(src).toContain('v-model.number="params.min_tokens"')
  })

  it('resetParams returns to 600 / 80 / 2 (blueprint reassigns whole new object)', async () => {
    const w = await mountPage()
    const ins = w.findAll('.params-row .param input')
    await ins[0]!.setValue('123')
    await ins[1]!.setValue('45')
    await ins[2]!.setValue('6')
    expect(w.findAll('.params-row .param input').map((i) => (i.element as HTMLInputElement).value)).toEqual([
      '123',
      '45',
      '6',
    ])
    expect(w.find('.reset-btn').text()).toBe('Reset')
    expect((w.find('.reset-btn').element as HTMLButtonElement).type).toBe('button')
    await w.find('.reset-btn').trigger('click')
    await nextTick()
    expect(w.findAll('.params-row .param input').map((i) => (i.element as HTMLInputElement).value)).toEqual([
      '600',
      '80',
      '2',
    ])
  })

  it('hint-line two sentences: default value explanation + overlap tip in `<em>` (N21 uses `5–20` with U+2013)', async () => {
    const w = await mountPage()
    const line = w.find('.hint-line')
    expect(sq(line.text())).toBe(
      'Defaults: target=600, overlap=80, min=2 (sandbox loose values; production uses 600/80/5–20). ' +
        'overlap only applies to plain text; markdown/source splits by paragraph or function boundary.',
    )
    expect(line.find('em').text()).toBe(
      'overlap only applies to plain text; markdown/source splits by paragraph or function boundary.',
    )
    // U+2013 (EN DASH) is not ASCII `-` — Appendix A §A.2 mandates copying each code point verbatim
    expect((enUs as Record<string, string>).aiKbPtDefaults).toContain('5–20')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — query / rerank / OCR three inputs (blueprint :59-71)', () => {
  it('query input placeholder goes through i18n; rerank label is hardcoded `rerank top-20` (N22)', async () => {
    const w = await mountPage()
    expect(w.find('.query-input').attributes('placeholder')).toBe(
      '(Optional) Enter a query to compute cosine similarity per chunk',
    )
    const boxes = w.findAll('.row .checkbox')
    expect(boxes).toHaveLength(2)
    expect(sq(boxes[0]!.text())).toBe('rerank top-20')
    expect(sq(boxes[1]!.text())).toBe('OCR (scanned PDF)')
  })

  it('both checkboxes default to false', async () => {
    const w = await mountPage()
    const els = w.findAll('.row .checkbox input').map((n) => n.element as HTMLInputElement)
    expect(els.map((e) => e.checked)).toEqual([false, false])
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — 🔴 K27 / K1 / FormData nine fields (blueprint :201-227)', () => {
  it('🔴 K27: `parserTestAnalyze(fd)` **single parameter** call — caller no longer passes headers/timeout', async () => {
    const w = await mountPage()
    await runWith(w)
    expect(ai.parserTestAnalyze).toHaveBeenCalledTimes(1)
    // Exactly 1 argument: package already includes multipart header + separate 120s timeout (`ai.ts:673-680`)
    expect(ai.parserTestAnalyze.mock.calls[0]).toHaveLength(1)
    expect(ai.parserTestAnalyze.mock.calls[0]![0]).toBeInstanceOf(FormData)
    // Pin "call shape" at source level (governance §9 clause 9: pin shape not bare identifiers), strip comments first
    const src = blankComments(readSrc())
    expect(src).toContain('result.value = (await service.ai.parserTestAnalyze(fd)) as AnalyzeResult')
    // 🔴 K1: no `.data` layer (package already does `return res.data`)
    expect(src).not.toMatch(/parserTestAnalyze\([^)]*\)\s*\)?\s*\.data/)
    // 🔴 no second argument (headers / timeout both in package)
    expect(src).not.toMatch(/parserTestAnalyze\(\s*fd\s*,/)
    expect(src).not.toContain("'Content-Type': 'multipart/form-data'")
    expect(src).not.toContain('timeout: 120000')
  })

  it('🔴 K1 rendering-side evidence: when mock returns fixture directly (no envelope), whole page renders normally', async () => {
    // Test criterion: if code stripped an extra `.data` layer, `result` would be undefined → every field would be empty.
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.ok-hint').exists()).toBe(true)
    expect(w.find('.chunks-card h3').text()).toBe('Chunking result (1 chunk)')
  })

  it('🔴 FormData nine fields **order and values** copied verbatim (when query not empty)', async () => {
    const w = await mountPage()
    await w.find('.query-input').setValue('probe')
    await runWith(w, makeFile('p5c-probe.md', 50))
    expect(lastFormEntries()).toEqual([
      ['file', 'File(p5c-probe.md,50)'],
      ['query', 'probe'],
      ['embed', 'true'], // 🔴 always 'true' (blueprint :210 is literal, no switch affects it)
      ['rerank', 'false'],
      ['ocr', 'false'],
      ['target_tokens', '600'],
      ['overlap_tokens', '80'],
      ['min_tokens', '2'],
    ])
  })

  it('🔴 when query is empty **field `query` is truly absent** (blueprint :209 conditionally appends)', async () => {
    // Test criterion: change `if (query) fd.append(...)` to unconditional append → this test must fail.
    const w = await mountPage()
    await runWith(w)
    const entries = lastFormEntries()
    expect(entries.map(([k]) => k)).toEqual([
      'file',
      'embed',
      'rerank',
      'ocr',
      'target_tokens',
      'overlap_tokens',
      'min_tokens',
    ])
    expect(entries.map(([k]) => k)).not.toContain('query')
    const fd = ai.parserTestAnalyze.mock.calls[0]![0] as FormData
    expect(fd.getAll('query')).toEqual([])
    expect(fd.has('query')).toBe(false)
    // Seven of the other eight are still in (order not scrambled)
    expect(entries[0]![0]).toBe('file')
    expect(entries[1]![0]).toBe('embed')
  })

  it('rerank checked → `rerank=\'true\'`, ocr still `\'false\'` (one side of ternary)', async () => {
    const w = await mountPage()
    await w.findAll('.row .checkbox input')[0]!.setValue(true)
    await runWith(w)
    const e = Object.fromEntries(lastFormEntries())
    expect(e.rerank).toBe('true')
    expect(e.ocr).toBe('false')
  })

  it('ocr checked → `ocr=\'true\'`, rerank still `\'false\'` (other side of ternary)', async () => {
    const w = await mountPage()
    await w.findAll('.row .checkbox input')[1]!.setValue(true)
    await runWith(w)
    const e = Object.fromEntries(lastFormEntries())
    expect(e.rerank).toBe('false')
    expect(e.ocr).toBe('true')
  })

  it('both checked → both `\'true\'`; `embed` always `\'true\'`, unaffected by any switch', async () => {
    const w = await mountPage()
    await w.findAll('.row .checkbox input')[0]!.setValue(true)
    await w.findAll('.row .checkbox input')[1]!.setValue(true)
    await runWith(w)
    const e = Object.fromEntries(lastFormEntries())
    expect(e.rerank).toBe('true')
    expect(e.ocr).toBe('true')
    expect(e.embed).toBe('true')
  })

  it('clear error and result before submit (blueprint :204-205)', async () => {
    const w = await mountPage()
    ai.parserTestAnalyze.mockRejectedValueOnce(httpError(400, ERR_400_TARGET))
    await runWith(w)
    expect(w.find('.error-box').exists()).toBe(true)
    // second submit succeeds → error box disappears, result appears
    ai.parserTestAnalyze.mockResolvedValue(MD_OK)
    await w.find('.submit-btn').trigger('click')
    await flushPromises()
    await nextTick()
    expect(w.find('.error-box').exists()).toBe(false)
    expect(w.find('.chunks-card').exists()).toBe(true)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — submit button :disabled both sides + loading text (blueprint :74-78)', () => {
  it('no file selected → button disabled, text "Run" (first half of `:disabled="!file || loading"`)', async () => {
    const w = await mountPage()
    const btn = w.find('.submit-btn')
    expect((btn.element as HTMLButtonElement).disabled).toBe(true)
    expect(btn.text()).toBe('Run')
  })

  it('file selected → button enabled', async () => {
    const w = await mountPage()
    await pickFile(w, makeFile('a.md', 10))
    expect((w.find('.submit-btn').element as HTMLButtonElement).disabled).toBe(false)
  })

  it('🔴 while in flight → disabled + text "Processing…" (second half `|| loading`); after landing re-enable and show "Run"', async () => {
    const w = await mountPage()
    const d = deferred<unknown>()
    ai.parserTestAnalyze.mockReturnValue(d.promise)
    await pickFile(w, makeFile('a.md', 10))
    await w.find('.submit-btn').trigger('click')
    await nextTick()
    expect((w.find('.submit-btn').element as HTMLButtonElement).disabled).toBe(true)
    expect(w.find('.submit-btn').text()).toBe('Processing…')

    d.resolve(MD_OK)
    await flushPromises()
    await nextTick()
    expect((w.find('.submit-btn').element as HTMLButtonElement).disabled).toBe(false)
    expect(w.find('.submit-btn').text()).toBe('Run')
  })

  it('`submit()` start guard `if (!file) return`: direct call does not send request', async () => {
    const w = await mountPage()
    // Button is blocked by disabled, but guard exists (blueprint :202) — force DOM disable off then click
    const btn = w.find('.submit-btn').element as HTMLButtonElement
    btn.disabled = false
    await w.find('.submit-btn').trigger('click')
    await flushPromises()
    expect(ai.parserTestAnalyze).not.toHaveBeenCalled()
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — ok-hint (blueprint :79-89) + 🔴 governance §4.2 fact④', () => {
  it('not run yet → no render; after run → `✓ N chunks · size · mime ·` + params_used echo', async () => {
    const w = await mountPage()
    expect(w.find('.ok-hint').exists()).toBe(false)
    await runWith(w)
    // N16: `✓` (U+2713) and three `·` (U+00B7) outside t(); N22: `chunks` / `chunker=` etc. not in i18n
    expect(sq(w.find('.ok-hint').text())).toBe(
      '✓ 1 chunks · 50 B · text/markdown · chunker=markdown, target=600, overlap=0, min=2',
    )
  })

  it('🔴 fact④: shown is **backend-returned params_used**, not frontend-sent params — `.md` sends 80 returns 0', async () => {
    // Test criterion: if template reads `params` not `result.params_used`, would show overlap=80.
    const w = await mountPage()
    expect(
      (w.findAll('.params-row .param input')[1]!.element as HTMLInputElement).value,
    ).toBe('80') // frontend sent 80
    await runWith(w)
    expect(Object.fromEntries(lastFormEntries()).overlap_tokens).toBe('80') // confirmed sent 80
    expect(sq(w.find('.ok-hint em').text())).toBe(
      'chunker=markdown, target=600, overlap=0, min=2', // 🔴 backend returns 0
    )
  })

  it('🔴 other half of fact④: `.txt` goes through plain chunker → overlap returns unchanged at 10', async () => {
    ai.parserTestAnalyze.mockResolvedValue(TXT_RERANK)
    const w = await mountPage()
    await runWith(w, makeFile('p5c-probe.txt', 196, 'text/plain'))
    expect(sq(w.find('.ok-hint em').text())).toBe('chunker=plain, target=50, overlap=10, min=2')
    expect(sq(w.find('.ok-hint').text())).toBe(
      '✓ 1 chunks · 196 B · text/plain · chunker=plain, target=50, overlap=10, min=2',
    )
  })

  it('when `params_used` absent, whole `<em>` section does not render (blueprint :83 v-if)', async () => {
    // All six fixtures have `params_used`; this case can only be covered by mock (delete field) for v-if false side.
    const { params_used, ...noParams } = MD_OK
    void params_used
    ai.parserTestAnalyze.mockResolvedValue(noParams)
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.ok-hint').exists()).toBe(true)
    expect(w.find('.ok-hint em').exists()).toBe(false)
    expect(sq(w.find('.ok-hint').text())).toBe('✓ 1 chunks · 50 B · text/markdown ·')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — chunks card complete rendering (blueprint :126-149)', () => {
  it('md-ok: title `Chunking result (1 chunk)`, one chunk-item, chunk-head + chunk-text exact match', async () => {
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.chunks-card h3').text()).toBe('Chunking result (1 chunk)')
    const items = w.findAll('.chunk-item')
    expect(items).toHaveLength(1)
    expect(items[0]!.find('.chunk-head strong').text()).toBe('chunk #0') // N22
    // N22: `tokens · offset a-b` entire string hardcoded
    expect(sq(items[0]!.find('.chunk-head .hint').text())).toBe('12 tokens · offset 0-50')
    // `<pre>` preserves original newlines (fixture text contains `\n\n`)
    expect(items[0]!.find('pre.chunk-text').text()).toBe(
      'Sandbox probe A.\n\nSecond paragraph for chunk two.',
    )
  })

  it('dense_preview: `dense [0:8]:` + 8 toFixed(4) comma-joined + `, …]` ending (N16 U+2026)', async () => {
    const w = await mountPage()
    await runWith(w)
    const embs = w.findAll('.chunk-item .emb-preview')
    expect(embs).toHaveLength(2)
    expect(embs[0]!.find('.emb-label').text()).toBe('dense [0:8]:')
    expect(embs[0]!.find('code').text()).toBe(
      '[-0.0309, 0.0237, 0.0030, -0.0038, -0.0316, -0.0135, 0.0212, 0.0347, …]',
    )
  })

  it('sparse_top_terms: `sparse top:` + `token_id:weight` joined with ` · ` (proves template shadowing `t` arrow parameter parses correctly)', async () => {
    // ⚠️ Blueprint :145 arrow parameter is called `t`, shadows i18n `t` in `<script setup>`.
    // This test also proves "Vue compiler scope tracking parses it as parameter, not `$setup.t`" —
    // if parsing failed would render as `undefined:undefined` or throw.
    const w = await mountPage()
    await runWith(w)
    const embs = w.findAll('.chunk-item .emb-preview')
    expect(embs[1]!.find('.emb-label').text()).toBe('sparse top:')
    expect(embs[1]!.find('code').text()).toBe(
      '151268:0.2153 · 11728:0.2056 · 6626:0.1726 · 7839:0.1494 · 77648:0.1463',
    )
  })

  it('dense_preview absent → that row not rendered; sparse_top_terms empty array → also not rendered (false side of both v-if)', async () => {
    const bare = {
      ...MD_OK,
      chunks: [{ chunk_no: 0, text: 'x', token_count: 1, offset_start: 0, offset_end: 1, sparse_top_terms: [] }],
    }
    ai.parserTestAnalyze.mockResolvedValue(bare)
    const w = await mountPage()
    await runWith(w)
    expect(w.findAll('.chunk-item')).toHaveLength(1)
    expect(w.findAll('.chunk-item .emb-preview')).toHaveLength(0)
  })

  it('🔴 `.empty` empty state (200 + chunk_count 0 + chunks []): governance §13 real-device-verifiable case', async () => {
    ai.parserTestAnalyze.mockResolvedValue(EMPTY_200)
    const w = await mountPage()
    await runWith(w, makeFile('p5c-empty.md', 0))
    expect(w.find('.chunks-card h3').text()).toBe('Chunking result (0 chunks)')
    expect(w.find('.chunks-card .empty').text()).toBe(
      'Parsing resulted in 0 chunks. File may be too short or entirely filtered segments.',
    )
    expect(w.findAll('.chunk-list')).toHaveLength(0)
    expect(w.findAll('.chunk-item')).toHaveLength(0)
    // Empty file still 200 → ok-hint still shown, size is 0 B
    expect(sq(w.find('.ok-hint').text())).toBe(
      '✓ 0 chunks · 0 B · text/markdown · chunker=markdown, target=600, overlap=0, min=2',
    )
    // No query/scored → scored card not rendered
    expect(w.find('.scored-card').exists()).toBe(false)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — scored card two states + N18 + 🔴 governance §4.2 facts②③ (blueprint :106-124)', () => {
  it('md-ok: title `Query similarity ranking (top 1)`, cos three decimals, chunk-ref, rank-text has original chunk text', async () => {
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.scored-card h3').text()).toBe('Query similarity ranking (top 1)')
    expect(w.find('.rank-no').text()).toBe('#1') // N18: indexOf(s) + 1
    expect(w.find('.score').text()).toBe('cos 0.508') // N22: `cos ` hardcoded; toFixed(3)
    expect(w.find('.chunk-ref').text()).toBe('chunk #0') // N22
    expect(w.find('.rank-text').text()).toBe('Sandbox probe A.\n\nSecond paragraph for chunk two.')
  })

  it('🔴 fact②: `scored[]` has no `rerank_score` → `rr {…}` whole field not rendered (false side of dual guard)', async () => {
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.rerank-score').exists()).toBe(false)
    expect(w.find('.scored-card').text()).not.toContain('rr ')
  })

  it('rerank_score has value → render `rr` (mocked, never seen on this device)', async () => {
    ai.parserTestAnalyze.mockResolvedValue({
      ...MD_OK,
      scored: [{ chunk_no: 0, cos_sim: 0.5082847161344183, rerank_score: 0.87654 }],
    })
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.rerank-score').text()).toBe('rr 0.877') // N22 + toFixed(3)
  })

  it('`rerank_score: null` still not rendered (blueprint `!== null` half guard)', async () => {
    ai.parserTestAnalyze.mockResolvedValue({
      ...MD_OK,
      scored: [{ chunk_no: 0, cos_sim: 0.5, rerank_score: null }],
    })
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.rerank-score').exists()).toBe(false)
  })

  it('🔴 fact③: txt-rerank (rerank checked) → `⚠ Reranker error:` warning rendered, still no rr', async () => {
    // Device reranker is broken (backend defect, governance §8.2 has ticket) → this is the **only** thing visible after rerank check.
    ai.parserTestAnalyze.mockResolvedValue(TXT_RERANK)
    const w = await mountPage()
    await w.findAll('.row .checkbox input')[0]!.setValue(true)
    await runWith(w, makeFile('p5c-probe.txt', 196, 'text/plain'))
    expect(Object.fromEntries(lastFormEntries()).rerank).toBe('true')
    // N22: `⚠ Reranker error:` entire string hardcoded (N16: `⚠` outside t())
    expect(sq(w.find('.scored-card .warn').text())).toBe(
      '⚠ Reranker error: XLMRobertaTokenizer has no attribute prepare_for_model',
    )
    expect(w.find('.rerank-score').exists()).toBe(false)
  })

  it('`rerank_error` absent → warning not rendered (md-ok fixture)', async () => {
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.scored-card').exists()).toBe(true)
    expect(w.find('.scored-card .warn').exists()).toBe(false)
  })

  it('`scored` absent / empty array → whole card not rendered (blueprint :107 `&& length` dual guard)', async () => {
    ai.parserTestAnalyze.mockResolvedValue({ ...MD_OK, scored: [] })
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.scored-card').exists()).toBe(false)
    // Absent side
    const { scored, ...noScored } = MD_OK
    void scored
    ai.parserTestAnalyze.mockResolvedValue(noScored)
    await w.find('.submit-btn').trigger('click')
    await flushPromises()
    await nextTick()
    expect(w.find('.scored-card').exists()).toBe(false)
  })

  it('🔴 N18: rank number is `scored.indexOf(s) + 1` (**array position**), independent of chunk_no', async () => {
    // Test criterion: change to `v-for="(s, i)"` and take `i + 1` renders identically on this data — so this test only pins
    // the user-visible fact "rank follows array position, not chunk_no", pinning the code form as well.
    ai.parserTestAnalyze.mockResolvedValue({
      ...MD_OK,
      chunk_count: 3,
      chunks: [
        { chunk_no: 0, text: 'zero', token_count: 1, offset_start: 0, offset_end: 4 },
        { chunk_no: 1, text: 'one', token_count: 1, offset_start: 4, offset_end: 7 },
        { chunk_no: 2, text: 'two', token_count: 1, offset_start: 7, offset_end: 10 },
      ],
      // deliberately make chunk_no not match array position (backend returns by descending similarity)
      scored: [
        { chunk_no: 2, cos_sim: 0.9 },
        { chunk_no: 0, cos_sim: 0.5 },
        { chunk_no: 1, cos_sim: 0.1 },
      ],
    })
    const w = await mountPage()
    await runWith(w)
    expect(w.findAll('.rank-no').map((n) => n.text())).toEqual(['#1', '#2', '#3'])
    expect(w.findAll('.chunk-ref').map((n) => n.text())).toEqual(['chunk #2', 'chunk #0', 'chunk #1'])
    // rank-text uses chunkText(s.chunk_no) → looks up by chunk_no
    expect(w.findAll('.rank-text').map((n) => n.text())).toEqual(['two', 'zero', 'one'])
    // Source shape (N18 copied as-is, no v-for index)
    const src = blankComments(readSrc())
    expect(src).toContain('#{{ result.scored.indexOf(s) + 1 }}')
    expect(src).toContain('v-for="s in result.scored"')
  })

  it('rank-text goes through `truncate(chunkText(...), 200)`: 200 chars as-is, 201 chars truncated to 200 + U+2026', async () => {
    const s200 = 'a'.repeat(200)
    const s201 = 'b'.repeat(201)
    ai.parserTestAnalyze.mockResolvedValue({
      ...MD_OK,
      chunk_count: 2,
      chunks: [
        { chunk_no: 0, text: s200, token_count: 1, offset_start: 0, offset_end: 200 },
        { chunk_no: 1, text: s201, token_count: 1, offset_start: 200, offset_end: 401 },
      ],
      scored: [
        { chunk_no: 0, cos_sim: 0.9 },
        { chunk_no: 1, cos_sim: 0.8 },
      ],
    })
    const w = await mountPage()
    await runWith(w)
    const texts = w.findAll('.rank-text').map((n) => n.text())
    expect(texts[0]).toBe(s200) // 恰好 200 → 不截(蓝本是严格 `>`)
    expect(texts[0]).toHaveLength(200)
    expect(texts[1]).toBe('b'.repeat(200) + '…') // 201 → 截 + 省略号
    expect(texts[1]).toHaveLength(201)
  })

  it('🔴 chunkText 找不到对应 chunk_no → 回空串(蓝本 `c ? c.text : \'\'`)', async () => {
    ai.parserTestAnalyze.mockResolvedValue({
      ...MD_OK,
      scored: [{ chunk_no: 99, cos_sim: 0.5 }], // chunks 里只有 chunk_no 0
    })
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.chunk-ref').text()).toBe('chunk #99')
    expect(w.find('.rank-text').text()).toBe('')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest —— docling 卡两态 + 折叠(蓝本 :97-104)+ 🔴 治理 §4.2 事实①', () => {
  it('🔴 事实①:两份成功 fixture(`.md` / `.txt`)都**不产生 `docling_markdown`** → 整卡不渲染', async () => {
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.docling-card').exists()).toBe(false)

    ai.parserTestAnalyze.mockResolvedValue(TXT_RERANK)
    await w.find('.submit-btn').trigger('click')
    await flushPromises()
    await nextTick()
    expect(w.find('.docling-card').exists()).toBe(false)
  })

  it('mock 造一份带 `docling_markdown` 的:折叠按钮文案 `▶ docling 转出的 markdown（N 字符）`,默认折起', async () => {
    // 治理 §13:要看到这张卡得传 `.docx`/`.pptx`/`.xlsx`(🔴 **别传 `.pdf`**,会触发
    // ~200 MB 模型下载)→ 本机验渲染只能靠 mock 造。
    const md = '# Title\n\nbody text'
    ai.parserTestAnalyze.mockResolvedValue({ ...MD_OK, docling_markdown: md })
    const w = await mountPage()
    await runWith(w, makeFile('doc.docx', 4096))
    const card = w.find('.docling-card')
    expect(card.exists()).toBe(true)
    // N16:`▼`/`▶` 在 t() 外面;`{n}` 取的是 `docling_markdown.length`(实测 18)
    expect(md).toHaveLength(18)
    expect(sq(card.find('.toggle').text())).toBe('▶ docling 转出的 markdown（18 字符）')
    // v-show 折起 → 元素在但 display: none
    const pre = card.find('pre.docling-md')
    expect(pre.exists()).toBe(true)
    expect((pre.element as HTMLElement).style.display).toBe('none')
    expect(pre.text()).toBe(md)
  })

  it('点折叠按钮 → 箭头翻成 `▼`、`<pre>` 可见;再点收回', async () => {
    ai.parserTestAnalyze.mockResolvedValue({ ...MD_OK, docling_markdown: 'x' })
    const w = await mountPage()
    await runWith(w, makeFile('doc.docx', 4096))
    await w.find('.docling-card .toggle').trigger('click')
    await nextTick()
    expect(sq(w.find('.docling-card .toggle').text())).toBe('▼ docling 转出的 markdown（1 字符）')
    expect((w.find('pre.docling-md').element as HTMLElement).style.display).toBe('')

    await w.find('.docling-card .toggle').trigger('click')
    await nextTick()
    expect(sq(w.find('.docling-card .toggle').text())).toBe('▶ docling 转出的 markdown（1 字符）')
    expect((w.find('pre.docling-md').element as HTMLElement).style.display).toBe('none')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
// 🔴 422 为什么不测:文件头注释已抄下那份响应体并说明 —— 提交按钮
// `:disabled="!file || loading"` + `submit()` 开头 `if (!file) return` 双重挡住,
// **UI 到不了「不传 file」这条路**;治理 §4.2 / §5.1 明令不为它加数组分支、也不写单测。
// 下面只测两条 400(`detail` 是字符串,真机可复现)与「无 response 的网络错误」。
describe('ParserTest —— 失败侧:两条 400 的 .error-box + 取值链兜底(蓝本 :221-224 / :92)', () => {
  it('400 `target_tokens must be in [50, 4000]` 原文进 .error-box', async () => {
    ai.parserTestAnalyze.mockRejectedValue(httpError(400, ERR_400_TARGET))
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.error-box').text()).toBe('target_tokens must be in [50, 4000]')
    // 失败时 result 保持为 null → 三张结果卡都不渲染
    expect(w.find('.ok-hint').exists()).toBe(false)
    expect(w.find('.chunks-card').exists()).toBe(false)
  })

  it('400 不支持的扩展名 —— 整串原文(含分号后那一长串扩展名清单)进 .error-box', async () => {
    ai.parserTestAnalyze.mockRejectedValue(httpError(400, ERR_400_EXT))
    const w = await mountPage()
    await runWith(w, makeFile('p5c-probe.bin', 12, 'application/octet-stream'))
    expect(w.find('.error-box').text()).toBe(
      "extension '.bin' not supported in test sandbox; use .md / source code / .txt / .html / .json / .csv / .log / .pdf / .docx / .pptx / .xlsx",
    )
  })

  it('取值链第二档:`response.data.error`(没有 `detail` 时)', async () => {
    // 蓝本 :222 是 `data.detail || data.error` —— 两个都读,照抄。
    ai.parserTestAnalyze.mockRejectedValue(httpError(500, { error: 'internal boom' }))
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.error-box').text()).toBe('internal boom')
  })

  it('取值链第三档:无 response(网络层错误)→ 回落 `e.message`', async () => {
    ai.parserTestAnalyze.mockRejectedValue(new Error('Network Error'))
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.error-box').text()).toBe('Network Error')
  })

  it('取值链第四档:message 为空 → 回落 `String(e)`', async () => {
    ai.parserTestAnalyze.mockRejectedValue(new Error(''))
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.error-box').text()).toBe('Error')
  })

  it('失败后 loading 归位(`finally`)→ 按钮解禁、文案回「运行」', async () => {
    ai.parserTestAnalyze.mockRejectedValue(httpError(400, ERR_400_TARGET))
    const w = await mountPage()
    await runWith(w)
    expect((w.find('.submit-btn').element as HTMLButtonElement).disabled).toBe(false)
    expect(w.find('.submit-btn').text()).toBe('运行')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest —— fmtBytes 三档边界两侧(蓝本 :236-240)', () => {
  // 通过 `.file-meta .hint` 观察(蓝本 :34 是它唯一的调用点之一),走真实渲染路径。
  async function bytesLabel(size: number): Promise<string> {
    const w = await mountPage()
    await pickFile(w, makeFile('x.md', size))
    return w.find('.file-meta .hint').text()
  }

  it('B 档:0 / 1 / 1023 —— 整数直接拼 `" B"`,不带小数', async () => {
    expect(await bytesLabel(0)).toBe('0 B')
    expect(await bytesLabel(1)).toBe('1 B')
    expect(await bytesLabel(1023)).toBe('1023 B')
  })

  it('🔴 第一个边界 1024:上侧进 KB 档、toFixed(1)', async () => {
    expect(await bytesLabel(1024)).toBe('1.0 KB')
    expect(await bytesLabel(1536)).toBe('1.5 KB')
  })

  it('🔴 第二个边界 1048575 / 1048576:下侧仍 KB(toFixed(1))、上侧进 MB(toFixed(2))', async () => {
    expect(await bytesLabel(1024 * 1024 - 1)).toBe('1024.0 KB')
    expect(await bytesLabel(1024 * 1024)).toBe('1.00 MB')
  })

  it('MB 档:两位小数', async () => {
    expect(await bytesLabel(30 * 1024 * 1024)).toBe('30.00 MB')
    expect(await bytesLabel(1024 * 1024 * 3 + 512 * 1024)).toBe('3.50 MB')
  })

  it('ok-hint 里的 size 也走同一个 fmtBytes(md-ok 的 50 → `50 B`)', async () => {
    const w = await mountPage()
    await runWith(w, makeFile('p5c-probe.md', 50))
    expect(sq(w.find('.ok-hint').text())).toContain('· 50 B ·')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest —— 🔴 §9.2 en 档强断言(zh 撞车、只有 en 能判别)', () => {
  // 治理 §9.2:凡「必须用键 A、不许用键 B,理由是 **en 不同**」的条目,只比 zh 的断言
  // **零判别力**(T6 评审实测:换成被禁键 47/47 全绿)。
  //
  // 🔴 本刀已把本页 23 个键的 zh 值与**全表 1503 键**做过程序化撞车扫描,结果:
  //   `aiKbPtProcessing`   zh 处理中…  <撞>  `appsWorking`        en `Processing…` vs `Working…`  ← **EN-DIFF**
  //   `aiKbPtReset`        zh 重置      <撞>  `filesViewerReset`   en `Reset` vs `Reset`           ← EN-SAME(无判别力)
  //   `aiKbPtRun`          zh 运行      <撞>  `aiSkTestRun`        en `Run` vs `Run`               ← EN-SAME(无判别力)
  // → **唯一有 en 判别力的同族键是 `aiKbPtProcessing` / `appsWorking`**:两者 zh 逐字相同
  //   (都是「处理中…」),只有英文界面能分辨。若有人图省事复用 `appsWorking`,中文界面
  //   看不出任何差别、三门全绿,只有切英文才看得出按钮写着 `Working…`(Vue2 是 `Processing…`)
  //   = 界面不 1:1。故这一对必须有 en 档正向 + 反向断言。
  // 另两对 EN-SAME 的靠源码键名守(渲染断言对它们零判别力,同 T6 对 A-1 的处置)。
  //
  // 🔴 locale 是全局单例 → 必须 try/finally 还原,否则污染同文件后续用例。
  const localeRef = i18n.global.locale as unknown as { value: string }

  async function inEn<T>(fn: (w: W) => Promise<T> | T): Promise<T> {
    const prev = localeRef.value
    localeRef.value = 'en_us'
    try {
      const w = await mountPage()
      return await fn(w)
    } finally {
      localeRef.value = prev
    }
  }

  it('🔴 en 档:在飞时按钮逐字 `Processing…`,落地后逐字 `Run`', async () => {
    await inEn(async (w) => {
      const d = deferred<unknown>()
      ai.parserTestAnalyze.mockReturnValue(d.promise)
      await pickFile(w, makeFile('a.md', 10))
      expect(w.find('.submit-btn').text()).toBe('Run')
      await w.find('.submit-btn').trigger('click')
      await nextTick()
      expect(w.find('.submit-btn').text()).toBe('Processing…')
      d.resolve(MD_OK)
      await flushPromises()
    })
  })

  it('🔴 反向:en 档渲染结果里不许出现被禁复用键 `appsWorking` 的 en 值(`Working…`)', async () => {
    await inEn(async (w) => {
      const d = deferred<unknown>()
      ai.parserTestAnalyze.mockReturnValue(d.promise)
      await pickFile(w, makeFile('a.md', 10))
      await w.find('.submit-btn').trigger('click')
      await nextTick()
      expect(w.find('.submit-btn').text()).not.toBe('Working…')
      expect(w.text()).not.toContain('Working…')
      d.resolve(MD_OK)
      await flushPromises()
    })
    // 反过来实证这一对**只有 en 能判别**:zh 逐字相同
    const zh = zhCn as Record<string, string>
    const en = enUs as Record<string, string>
    expect(zh.aiKbPtProcessing).toBe(zh.appsWorking)
    expect(en.aiKbPtProcessing).not.toBe(en.appsWorking)
    expect(en.aiKbPtProcessing).toBe('Processing…')
    expect(en.appsWorking).toBe('Working…')
  })

  it('两对 EN-SAME 同族键(`aiKbPtReset`/`filesViewerReset` · `aiKbPtRun`/`aiSkTestRun`)只能靠源码键名守', async () => {
    // 它们 en 与 zh 双双同值 → 任何渲染断言都分不出来(同 T6 对裁定 A-1 的处置)。
    const zh = zhCn as Record<string, string>
    const en = enUs as Record<string, string>
    expect(zh.aiKbPtReset).toBe(zh.filesViewerReset)
    expect(en.aiKbPtReset).toBe(en.filesViewerReset)
    expect(zh.aiKbPtRun).toBe(zh.aiSkTestRun)
    expect(en.aiKbPtRun).toBe(en.aiSkTestRun)
    // → 判据落在「模板用的是哪个键」的调用形状上(治理 §9 第九条:钉形状不钉裸标识符)
    const src = blankComments(readSrc())
    expect(src).toContain("t('aiKbPtReset')")
    expect(src).toContain("t('aiKbPtRun')")
    expect(src).not.toMatch(/\bt\(\s*['"]filesViewerReset['"]/)
    expect(src).not.toMatch(/\bt\(\s*['"]aiSkTestRun['"]/)
  })

  it('en 档整页关键文案逐字(证明 23 个键全部走对了 en 值)', async () => {
    await inEn(async (w) => {
      expect(w.find('.page-header h2').text()).toBe('Parser test sandbox')
      expect(w.find('a.back-link').text()).toBe('← Back to details')
      expect(w.find('.pick-btn').text()).toBe('Choose file')
      expect(w.find('.dropzone .hint').text()).toBe('or drag and drop here')
      expect(w.find('.reset-btn').text()).toBe('Reset')
      expect(w.find('.query-input').attributes('placeholder')).toBe(
        '(Optional) Enter a query to compute cosine similarity per chunk',
      )
      expect(sq(w.findAll('.row .checkbox')[1]!.text())).toBe('OCR (scanned PDF)')
      expect(sq(w.find('.hint-line').text())).toBe(
        'Defaults: target=600, overlap=80, min=2 (sandbox loose values; production uses 600/80/5–20). ' +
          'overlap only applies to plain text; markdown/source splits by paragraph or function boundary.',
      )
    })
  })

  it('切回 zh 后仍是中文(证明 locale 已还原、无污染)', async () => {
    const w = await mountPage()
    expect(w.find('.page-header h2').text()).toBe('Parser 测试沙盒')
    expect(w.find('.submit-btn').text()).toBe('运行')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest —— N16 emoji / 符号位置核对(一个都不许挪进/挪出 t())', () => {
  it('本页 23 个键的键值零 emoji / 零箭头 / 零 `✓⚠×▼▶`(证明符号在模板里,不在语言包里)', () => {
    const zh = zhCn as Record<string, string>
    const en = enUs as Record<string, string>
    const KEYS = [
      'aiKbPtTitle', 'aiKbPtBackLink', 'aiKbPtHelp1', 'aiKbPtHelpNoWrite', 'aiKbPtHelpPreviewOnly',
      'aiKbPtSupports', 'aiKbPtAsWellAs', 'aiKbPtViaDocling', 'aiKbPtMaxSize', 'aiKbPtChooseFile',
      'aiKbPtDragDrop', 'aiKbPtReset', 'aiKbPtDefaults', 'aiKbPtOverlapNote', 'aiKbPtQueryPlaceholder',
      'aiKbPtOcr', 'aiKbPtProcessing', 'aiKbPtRun', 'aiKbPtDoclingToggle', 'aiKbPtScoredTitle',
      'aiKbPtChunksTitle', 'aiKbPtZeroChunks', 'aiKbPtTooBig',
    ]
    expect(KEYS).toHaveLength(23)
    for (const k of KEYS) {
      expect(typeof zh[k]).toBe('string')
      expect(typeof en[k]).toBe('string')
      expect(zh[k]).not.toMatch(/[←✓⚠×▼▶🧪→]/u)
      expect(en[k]).not.toMatch(/[←✓⚠×▼▶🧪→]/u)
    }
    // 🔴 反过来:`…`(U+2026)**在** `aiKbPtProcessing` 的键值里(不是模板拼的)
    expect(zh.aiKbPtProcessing).toBe('处理中…')
    expect(en.aiKbPtProcessing).toBe('Processing…')
  })

  it('模板里符号与译文之间恰好一个空格,顺序是「符号 → 文案」', async () => {
    const w = await mountPage()
    expect(w.find('a.back-link').text()).toBe('← 返回详情')
    expect(w.find('.clear-btn').exists()).toBe(false) // 未选文件时没有 ×
    await runWith(w)
    expect(w.find('.clear-btn').text()).toBe('×')
    expect(sq(w.find('.ok-hint').text()).startsWith('✓ ')).toBe(true)

    ai.parserTestAnalyze.mockResolvedValue({ ...MD_OK, docling_markdown: 'x', rerank_error: 'boom' })
    await w.find('.submit-btn').trigger('click')
    await flushPromises()
    await nextTick()
    expect(sq(w.find('.docling-card .toggle').text()).startsWith('▶ ')).toBe(true)
    expect(sq(w.find('.scored-card .warn').text()).startsWith('⚠ Reranker error: ')).toBe(true)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest —— 🔴 N22:硬编码技术标识符「判定不入语言包」', () => {
  // 🔴 **M-2(评审 2026-08-04)—— 这两条守卫已从「宽子串扫描」收紧成「精确值 + 键集闭合」。**
  // 第一版对 `'cos '` / `'rr '` / `'chunk #'` 这类**通用子串**做 `v.includes(s)` 全包扫描:
  // 当前 0 命中,但将来任何**无关**新键的值里含这些子串(比如某处文案写了「rr 」)就会
  // **假报红** —— 与治理 §9 第九条(否定式断言撞上无关内容 → 冤枉正确代码 → 诱使去"修"
  // 一个没坏的东西)同族。收紧后判别力**没降**:真正要守的事实是
  //   ① 没有任何键的**整值**就是这些技术串(= 没人给它们建键);
  //   ② 本页模板里 `t()` 的键集**恰好**是那 23 个 `aiKbPt*`(= 没人偷偷多接一个键)。
  // ② 才是「有人把技术串补成 i18n 键」这件事的真正判据 —— 补键必然要在模板里多一次
  // `t()` 调用,键集闭合当场炸。RED 探针 H(往 zh_cn.ts 塞 `aiKbPtRerankTop20`)与
  // 探针 I(把模板里的裸 `rerank top-20` 换成 `{{ t('aiKbPtRerankTop20') }}`)分别验这两条。
  it('①15 串技术标识符不是两档语言包里任何键的**整值**(精确相等,不用宽子串)', () => {
    // 🔴 治理 §3.5 N22:这些是技术标识符/参数名,Vue2 刻意没进 i18n。
    // 补键 = 凭空多出 Vue2 没有的键,且 en/zh 两档一填英文 = 纯噪音。
    const TECH = [
      'rerank top-20',
      'dense [0:8]:',
      'sparse top:',
      'chunk #',
      'cos ',
      'rr ',
      'target_tokens',
      'overlap_tokens',
      'min_tokens',
      'chunker=',
      'Reranker error',
      'tokens · offset',
      ' chunks ·',
      '.md .txt .html .json .csv .py .go .ts .java',
      '.pdf .docx .pptx .xlsx',
    ]
    expect(TECH).toHaveLength(15)
    for (const [name, pack] of [['zh_cn', zhCn], ['en_us', enUs]] as Array<[string, Record<string, unknown>]>) {
      const entries = Object.entries(pack).filter((e): e is [string, string] => typeof e[1] === 'string')
      expect(entries.length).toBeGreaterThan(1400) // 扫的是全表,不是空集合
      for (const s of TECH) {
        // 🔴 **精确整值相等**(不是 `includes`):判据是「有没有人给这个技术串建了键」。
        // 报错消息带上 pack 名与命中的键名,便于定位。
        expect(entries.filter(([, v]) => v === s).map(([k]) => `${name}.${k}`)).toEqual([])
      }
    }
  })

  it('②本页模板里 `t()` 的键集**恰好**是那 23 个 `aiKbPt*`(键集闭合 —— 补一个键就炸)', () => {
    // 🔴 这一条才是「有人把技术串补成 i18n 键」的真正判据:补键必然在模板里多一次
    // `t()` 调用 → 键集不再等于这 23 个 → 报红。比宽子串扫描更准、且零假报红面。
    // 剥注释(保行版)后再扫,否则会撞上本文件/组件头注释里提到的键名(治理 §9 第九条)。
    const src = blankComments(readSrc())
    const keys = [...src.matchAll(/(?<![\w$])t\(\s*'([^']+)'/g)].map((m) => m[1]!)
    const EXPECTED_23 = [
      'aiKbPtAsWellAs', 'aiKbPtBackLink', 'aiKbPtChooseFile', 'aiKbPtChunksTitle',
      'aiKbPtDefaults', 'aiKbPtDoclingToggle', 'aiKbPtDragDrop', 'aiKbPtHelp1',
      'aiKbPtHelpNoWrite', 'aiKbPtHelpPreviewOnly', 'aiKbPtMaxSize', 'aiKbPtOcr',
      'aiKbPtOverlapNote', 'aiKbPtProcessing', 'aiKbPtQueryPlaceholder', 'aiKbPtReset',
      'aiKbPtRun', 'aiKbPtScoredTitle', 'aiKbPtSupports', 'aiKbPtTitle',
      'aiKbPtTooBig', 'aiKbPtViaDocling', 'aiKbPtZeroChunks',
    ]
    expect(EXPECTED_23).toHaveLength(23)
    // 调用次数 = 23(每个键恰好用一次,与蓝本 23 个 `$t()` 一一对应)
    expect(keys).toHaveLength(23)
    expect([...keys].sort()).toEqual([...EXPECTED_23].sort())
    // 键集闭合:一个都不多、一个都不少
    expect(new Set(keys).size).toBe(23)
    // 且这 23 个键在两档语言包里都存在(否则渲染出键名本身)
    for (const k of EXPECTED_23) {
      expect(typeof (zhCn as Record<string, unknown>)[k]).toBe('string')
      expect(typeof (enUs as Record<string, unknown>)[k]).toBe('string')
    }
  })

  it('这 15 串在模板里是**裸文本**(不经 t()),逐串在剥注释后的模板里命中', () => {
    const src = blankComments(readSrc())
    const m = /<template>([\s\S]*?)\n<\/template>/.exec(src)
    expect(m).not.toBeNull()
    const tmpl = m![1]!
    for (const s of [
      'rerank top-20',
      'dense [0:8]:',
      'sparse top:',
      'chunk #{{ s.chunk_no }}',
      'chunk #{{ c.chunk_no }}',
      'cos {{ s.cos_sim.toFixed(3) }}',
      'rr {{ s.rerank_score.toFixed(3) }}',
      'target_tokens',
      'overlap_tokens',
      'min_tokens',
      'chunker={{ result.params_used.chunker }}',
      '⚠ Reranker error: {{ result.rerank_error }}',
      'tokens · offset {{ c.offset_start }}-{{ c.offset_end }}',
      'chunks ·',
      '<code>.md .txt .html .json .csv .py .go .ts .java</code>',
      '<code>.pdf .docx .pptx .xlsx</code>',
    ]) {
      expect(tmpl).toContain(s)
    }
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest —— 守卫缺口③:<template> 块零裸色字面量', () => {
  // 治理 §9 缺口③:`color-guard.test.ts:44-56` 的 `styleLines()` 对 `.vue` 只取
  // `<style>` 块 → 模板 `style=` / `:style=` 属性零扫描;本文件补一条定向断言堵这个盲区。
  // ⚠️ **沿用现状写法**(非贪婪 + 隐式靠「`</template>` 在第 0 列」锚定,先例
  // `ParserStatus.test.ts` / `QueueView.test.ts` / `IndexedFilesView.test.ts`);
  // 治理 §9 缺口③′ 的「统一改成贪婪匹配 + 覆盖度自检」归 **T8**,本刀不动它。
  // 🔴 读源文件用 `node:fs`,不用 Vite 的 `?raw`。
  it('<template> 块内(剥离 var()/color-mix() 之后)不含任何裸 hex / rgb / hsl 字面量', () => {
    const src: string = readSrc()
    const m = /<template>([\s\S]*?)\n<\/template>/.exec(src)
    expect(m).not.toBeNull()
    const tmpl = m![1]!
    // 覆盖度自检:抽出的片段必须同时含模板**首部**与**尾部**的特征串。
    // 本组件唯一的嵌套 `<template v-if="result">` 带属性(不是裸 `<template>`)、其闭合
    // 标签也是缩进的 → 不会把第 0 列的 `</template>` 提前截断。
    expect(tmpl).toContain("t('aiKbPtTitle')") // 首部(页头 h2)
    expect(tmpl).toContain("join(' · ') }}</code>") // 尾部(chunks 卡最后一行内容)

    // 剥掉 var(...) 与 color-mix(...) 的内部(照 color-guard.test.ts 的 stripVar
    // 同款手法:逐字符扫描配对括号深度,支持嵌套 fallback)
    function stripCalls(s: string, prefixes: string[]): string {
      let out = ''
      let i = 0
      while (i < s.length) {
        const hit = prefixes.find((p) => s.startsWith(p, i))
        if (hit) {
          let depth = 0
          let j = i + hit.length - 1 // 落在开括号上
          for (; j < s.length; j++) {
            if (s[j] === '(') depth++
            else if (s[j] === ')') {
              depth--
              if (depth === 0) {
                j++
                break
              }
            }
          }
          i = j
        } else {
          out += s[i]
          i++
        }
      }
      return out
    }
    const scrubbed = stripCalls(tmpl, ['var(', 'color-mix('])
    expect(scrubbed).not.toMatch(/#[0-9a-fA-F]{3,8}\b/)
    expect(scrubbed).not.toMatch(/\b(rgba?|hsla?)\s*\(/)
  })

  it('本文件零 <style> 块(K24:样式在 parser-styles.scss,走 JS 侧 import)', () => {
    const src: string = readSrc()
    expect(src).not.toMatch(/^<style/m)
    expect(src).toContain("import '../../styles/parser-styles.scss'")
  })

  it('零 KIcon(治理 §1.2 / E-2 / N16:两个 Parser 页蓝本一个 KIcon 都不用)', async () => {
    const src: string = readSrc()
    expect(src).not.toMatch(/^import KIcon/m)
    const w = await mountPage()
    await runWith(w)
    expect(w.findAll('svg')).toHaveLength(0)
  })
})
