// SP8-P5c Task 7 — component test for `ParserTest.vue` (Parser test sandbox).
// Blueprint: the Vue 2 panel (main@7a6ee6b7) `src/views/AI/Parser/ParserTest.vue` (369 lines;
// this cut covers template `:1-152` + script `:154-243`; `<style>` `:245-369` goes to T2b).
//
// ═══ mock strategy (governance §4.1 requires explicit documentation) ═══
// This page **uses no store** (all 10 items from blueprint data() are page-level transient state) →
// the only thing to mock is the shared package's `service.ai.parserTestAnalyze`.
// 🔴 It only does `return res.data` in the package (`the shared service package's src/ai.ts:673-680`, zero transformation)
// → mock it here as **raw HTTP snake_case**, matching the fixture literally. **Must have identical
// shapes across `ParserStatus.test.ts` / `parserStore.test.ts` / `knowledgeStore.parser.test.ts`
// `service.ai.parser*` methods** (governance §4.1 red flag self-check: same method mocked as different
// shapes across test files = time bomb). For failure cases, use `mockRejectedValue` to create
// errors with `response.data.detail` shaped after **actual response bodies** from four `.http` fixtures.
//
// ═══ fixtures are copies, not runtime reads (governance §4.4) ═══
// Six data sets copied verbatim into the `FIXTURE-COPY-BEGIN/END` blocks below with citations,
// **do not read the capture directory at runtime with `node:fs`** — that directory is gitignored (SP7 lost it entirely),
// and this branch will merge to master; tests in `src/` with cross-boundary dependencies silently
// fail with "file not found". 🔴 Copy generated by one-time script from fixtures (zero hand transcription),
// equivalence verified by **automated byte-for-byte validation** (script and output in T7 report §5)
// — not visual comparison. Reading `.vue` source files (guard gaps③ and N22 cases) still uses `node:fs`,
// **never Vite's `?raw`** (vitest's CSSEnablerPlugin replaces style source with empty string → assertions
// "pass" on empty string; precedent: `knowledgeStyles.test.ts` comment③).
//
// 🔴 **The 6th fixture (422) is only copied in comments, no constant, no test case** — see the
//    "why 422 is not tested" note before the final `describe`. Copy (verbatim, from
//    `p5c-fixtures/parser-test-analyze-422-no-file.http` response body):
//        {"detail":[{"type":"missing","loc":["body","file"],"msg":"Field required","input":null}]}
//    🔴 `detail` is **an array** (FastAPI validation error), differing from the two 400s' string `detail`
//    contract (governance §8.2 has backend ticket). **But UI cannot reach this branch**: submit button
//    `:disabled="!file || loading"` (blueprint :76) blocks "submit without choosing file"; `submit()` start
//    `if (!this.file) return` (:202) blocks again → governance §4.2 / §5.1 mandate:
//    **copy the value chain as-is, add no array branch, write no unit test for it** (testing a path UI
//    cannot reach = wasted effort).
//
// ═══ assertion calibration (governance §9) ═══
// `:disabled` is **a boolean attribute**: Vue renders `disabled=""` when true, omits the attribute when false →
// `attributes('disabled')` false side can only be `undefined`, but governance §9 **forbids `toBeUndefined()`**.
// So assert **DOM properties** always (`el.disabled`), which are naturally true/false comparable values on both sides.
// Other text/href/class: compare as strings directly. Multi-line template `text()` normalized with `sq()` then compared character-for-character.
// 🔴 Negation assertions (`not.toContain` / `not.toMatch`) always call `blankComments()` first to strip comments
// (governance §9 clause 9: negation assertion hitting comment = **false positive**, misleads into "fixing" working code —
//  this file's head comment itself has `service.ai.parserTestAnalyze(fd)` / `rerank top-20` etc.),
// and pin **call shape** not bare identifiers. Use **line-preserving strip** (replace comment content with equal spaces,
// keep newlines), governance §9 clause 8.
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import { nextTick } from 'vue'
import { createRouter, createWebHashHistory } from 'vue-router'
import { i18n } from '../../../i18n'
import zhCn from '../../../i18n/zh_cn'
import enUs from '../../../i18n/en_us'
import ParserTest from './ParserTest.vue'
import { readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

// ── vi.hoisted mock skeleton (governance §9: avoid ESM hoisting TDZ) ──
const ai = vi.hoisted(() => ({
  parserTestAnalyze: vi.fn(),
}))
vi.mock('@nimotech/nimoos-service', () => ({ service: { ai } }))

// ═══════════════════════════════════════════════════════════════════════════
// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-test-analyze-md-ok.json  (complete)
// From a captured device response (real device capture 2026-08-03,
// `POST /v1/parser/test/analyze`, `.md` + query=probe + rerank=false).
// 🔴 All four observed facts from governance §4.2 are in this one fixture:
//   ① **no `docling_markdown`** (.md does not go through docling) → entire docling card does not render
//   ② `scored[0]` has only `{chunk_no, cos_sim}`, **no `rerank_score`** → `rr {…}` does not render
//   ④ sent `overlap_tokens=80`, backend returns **0** per `chunker:"markdown"` → ok-hint echoes 0
const MD_OK = {
  "mime": "text/markdown",
  "filename": "p5c-probe.md",
  "size": 50,
  "text_length": 50,
  "chunk_count": 1,
  "chunks": [
    {"chunk_no":0,"text":"Sandbox probe A.\n\nSecond paragraph for chunk two.","token_count":12,"offset_start":0,"offset_end":50,"dense_preview":[-0.0309,0.0237,0.003,-0.0038,-0.0316,-0.0135,0.0212,0.0347],"sparse_top_terms":[{"token_id":151268,"weight":0.2153},{"token_id":11728,"weight":0.2056},{"token_id":6626,"weight":0.1726},{"token_id":7839,"weight":0.1494},{"token_id":77648,"weight":0.1463}]}
  ],
  "params_used": {"target_tokens":600,"overlap_tokens":0,"min_tokens":2,"chunker":"markdown"},
  "query": "probe",
  "scored": [
    {"chunk_no":0,"cos_sim":0.5082847161344183}
  ]
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-test-analyze-txt-rerank.json  (complete)
// From a captured device response (2026-08-03,
// `.txt` + query=vector search + **rerank=true**).
// 🔴 Fact③: local reranker is broken → `rerank_error` always present, `scored[0]` **still has no `rerank_score`**
//   (backend defect, governance §8.2 has ticket, this period copy frontend as-is, no fix, no workaround).
// 🔴 Other half of fact④: `chunker:"plain"` → `overlap_tokens` **returns unchanged at 10**.
const TXT_RERANK = {
  "mime": "text/plain",
  "filename": "p5c-probe.txt",
  "size": 196,
  "text_length": 196,
  "chunk_count": 1,
  "chunks": [
    {"chunk_no":0,"text":"Alpha beta gamma delta epsilon. Zeta eta theta iota kappa lambda mu nu xi omicron pi rho sigma tau upsilon phi chi psi omega.\nSecond line about vector search and embeddings for the sandbox probe.","token_count":48,"offset_start":0,"offset_end":196,"dense_preview":[-0.0584,-0.0225,-0.0411,0.0148,0.0028,-0.0604,0.0148,0.0051],"sparse_top_terms":[{"token_id":87506,"weight":0.2414},{"token_id":11728,"weight":0.2239},{"token_id":4759,"weight":0.2124},{"token_id":40703,"weight":0.2122},{"token_id":99245,"weight":0.2056}]}
  ],
  "params_used": {"target_tokens":50,"overlap_tokens":10,"min_tokens":2,"chunker":"plain"},
  "rerank_error": "XLMRobertaTokenizer has no attribute prepare_for_model",
  "query": "vector search",
  "scored": [
    {"chunk_no":0,"cos_sim":0.5408997321381046}
  ]
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-test-analyze-200-empty-file.http  (response body)
// From a captured device response (2026-08-03,
// sending a 0-byte `.md` file). 🔴 **HTTP 200** (not an error) + `chunk_count:0` / `chunks:[]` /
// **no `query`, no `scored`** → follows blueprint :129's `.empty` empty state. Governance §13: **real device verifiable** ✅
const EMPTY_200 = {
  "mime": "text/markdown",
  "filename": "p5c-empty.md",
  "size": 0,
  "text_length": 0,
  "chunk_count": 0,
  "chunks": [],
  "params_used": {"target_tokens":600,"overlap_tokens":0,"min_tokens":2,"chunker":"markdown"}
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-test-analyze-400-target-tokens.http  (response body)
// From `…-400-target-tokens.http` (2026-08-03, `target_tokens=1` out of bounds). HTTP **400**,
// `detail` is **a string** → blueprint :222's value chain picks it up, goes into `.error-box`.
const ERR_400_TARGET = {
  "detail": "target_tokens must be in [50, 4000]"
}
// FIXTURE-COPY-END

// FIXTURE-COPY-BEGIN  p5c-fixtures/parser-test-analyze-400-bad-ext.http  (response body)
// From `…-400-bad-ext.http` (2026-08-03, sending `.bin`). HTTP **400**, `detail` is a string.
const ERR_400_EXT = {
  "detail": "extension '.bin' not supported in test sandbox; use .md / source code / .txt / .html / .json / .csv / .log / .pdf / .docx / .pptx / .xlsx"
}
// FIXTURE-COPY-END
// ═══════════════════════════════════════════════════════════════════════════

/** Normalize whitespace in multi-line templates (Vue's condense already collapses newlines to single space, but `text()` may still leave indentation). */
function sq(s: string): string {
  return s.replace(/\s+/g, ' ').trim()
}

/**
 * "Line-preserving" comment stripping (governance §9 clause 8): replace comment content with equal spaces,
 * **preserve all newlines** — deletion-based stripping eats newlines too, causing line numbers in reports
 * to shift by tens of lines. Covers `<!-- -->` (template) and `/* *\/` (script); this file's `.vue` has no `//` line comments,
 * so `//` is not handled (would need to distinguish `//` inside strings, not worth it).
 */
function blankComments(src: string): string {
  return src.replace(/<!--[\s\S]*?-->|\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, ' '))
}

function readSrc(): string {
  return readFileSync(resolve(__dirname, './ParserTest.vue'), 'utf8')
}

/** Create a File with specified size (jsdom's `File.size` is read-only → use defineProperty to override). */
function makeFile(name: string, size: number, type = 'text/markdown'): File {
  const f = new File(['x'], name, { type })
  Object.defineProperty(f, 'size', { value: size, configurable: true })
  return f
}

function makeRouter() {
  const router = createRouter({
    history: createWebHashHistory('/'),
    routes: [
      { path: '/ai/parser/test', name: 'AIParserTest', component: ParserTest },
      // Blueprint :5's `router-link to="/ai/parser"` needs target route to exist to resolve href.
      // [Correction, SP8-P5d Task 9, governance §15.2 / plan §T9 clause 6] Previous comment is obsolete:
      // in production these two top-level parser routes reversed long ago to actual ParserStatus/ParserTest
      // (output of P5c-T10, knowledgeRoutes.ts head comment has full record), no longer point to placeholder.
      // This test file's stub component is just a placeholder in this file's own route table, unrelated
      // to whether production routes are placeholders — keep stub because this file only cares that href resolves.
      { path: '/ai/parser', name: 'AIParser', component: { template: '<div />' } },
    ],
  })
  router.push('/ai/parser/test')
  return router
}

const mountedWrappers: Array<ReturnType<typeof mount>> = []

async function mountPage() {
  const router = makeRouter()
  await router.isReady()
  const w = mount(ParserTest, { global: { plugins: [router, i18n] } } as never)
  mountedWrappers.push(w)
  return w
}

type W = Awaited<ReturnType<typeof mountPage>>

/** Follow the real `<input type="file">` change path (not by calling component methods directly). */
async function pickFile(w: W, f: File): Promise<void> {
  const input = w.find('input[type="file"]')
  Object.defineProperty(input.element, 'files', { value: [f], configurable: true })
  await input.trigger('change')
  await nextTick()
}

/** Pick file → click submit → wait for promise. */
async function runWith(w: W, f = makeFile('p5c-probe.md', 50)): Promise<void> {
  await pickFile(w, f)
  await w.find('.submit-btn').trigger('click')
  await flushPromises()
  await nextTick()
}

/** Get FormData from this call and replace File values with comparable strings. */
function lastFormEntries(): Array<[string, string]> {
  const calls = ai.parserTestAnalyze.mock.calls
  const fd = calls[calls.length - 1]![0] as FormData
  return Array.from(fd.entries()).map(([k, v]) => [
    k,
    typeof v === 'string' ? v : `File(${(v as File).name},${(v as File).size})`,
  ]) as Array<[string, string]>
}

/** Create an "axios-style" HTTP error (with `response.data`), shaped after `.http` fixture. */
function httpError(status: number, data: unknown, message = `Request failed with status code ${status}`) {
  return Object.assign(new Error(message), { response: { status, data } })
}

function deferred<T>() {
  let resolve!: (v: T) => void
  const promise = new Promise<T>((res) => {
    resolve = res
  })
  return { promise, resolve }
}

beforeEach(() => {
  vi.clearAllMocks()
  ai.parserTestAnalyze.mockResolvedValue(MD_OK)
})

afterEach(() => {
  while (mountedWrappers.length) mountedWrappers.pop()!.unmount()
  document.body.innerHTML = ''
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — K31 two-layer root element (scroll container + 900px centered column)', () => {
  // 🔴 Governance §3 K31: `.parser-app` is **outer wrapper**, page root class `.parser-test-page` is **inner**.
  // Squashing into one element puts the `overflow-y:auto` scrollbar at the right edge of the 900px centered column
  // (roughly screen center on wide screens), whereas Vue2 scrolls the whole page with scrollbar at viewport's right edge
  // = user-visible interface not 1:1. ⚠️ Plan §T7 still shows pre-K31 single-element style (governance §12.3 E-14 same family),
  // already superseded by K31. Test criterion: rewrite two classes back into one element → both tests in this group must fail.
  it('root element only has .parser-app (not .parser-test-page)', async () => {
    const w = await mountPage()
    const root = w.element as HTMLElement
    expect(root.tagName).toBe('DIV')
    expect(root.className).toBe('parser-app')
    expect(root.classList.contains('parser-test-page')).toBe(false)
  })

  it('.parser-test-page is direct child of .parser-app, and exactly one of each', async () => {
    const w = await mountPage()
    expect(w.findAll('.parser-app')).toHaveLength(1)
    expect(w.findAll('.parser-test-page')).toHaveLength(1)
    expect(w.find('.parser-app > .parser-test-page').exists()).toBe(true)
    // Page content is actually in inner layer (not empty shell)
    expect(w.find('.parser-test-page > .page-header').exists()).toBe(true)
    expect(w.find('.parser-test-page > .upload-card').exists()).toBe(true)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — page header + help card (blueprint :3-18)', () => {
  it('title exact match, back link `← Back to details` with href (N16: `←` outside t(); page title no emoji)', async () => {
    const w = await mountPage()
    expect(w.find('.page-header h2').text()).toBe('Parser 测试沙盒')
    const link = w.find('a.back-link')
    expect(link.text()).toBe('← 返回详情')
    // hash router: href resolved in jsdom is pure hash (production is `…/#/ai/parser`)
    expect(link.attributes('href')).toBe('#/ai/parser')
    // 🔴 brief §4.3 says page title has `🧪` — source verification shows wrong (E-15): `🧪` is at
    //    `ParserStatus.vue:6` and `SettingsView.vue:162`, this page's h2 is pure translation.
    expect(w.find('.page-header').text()).not.toContain('🧪')
  })

  it('help card first paragraph: three keys + bare comma after `<strong>` + bare period at end', async () => {
    const w = await mountPage()
    const ps = w.findAll('.help-card p')
    expect(ps).toHaveLength(2)
    expect(sq(ps[0]!.text())).toBe(
      '上传一个文件，看 Parser 怎么处理它（切块 + 嵌入 + 评分）。 不会写入索引, 纯预览.',
    )
    expect(ps[0]!.find('strong').text()).toBe('不会写入索引')
  })

  it('help card second paragraph: two `<code>` extension lists are technical identifiers (N22), not in i18n', async () => {
    const w = await mountPage()
    const p = w.findAll('.help-card p')[1]!
    expect(p.classes()).toContain('small')
    const codes = p.findAll('code')
    expect(codes).toHaveLength(2)
    expect(codes[0]!.text()).toBe('.md .txt .html .json .csv .py .go .ts .java')
    expect(codes[1]!.text()).toBe('.pdf .docx .pptx .xlsx')
    expect(sq(p.text())).toBe(
      '支持 .md .txt .html .json .csv .py .go .ts .java, 以及 .pdf .docx .pptx .xlsx （经 docling 转 markdown）. ' +
        '最大 30 MB。PDF 首次会触发模型权重下载（~200 MB，一次性）。',
    )
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — drop zone three states + dragActive class toggle (blueprint :22-26)', () => {
  it('dragover adds .active, dragleave removes it (`:class="{ active: dragActive }"`)', async () => {
    const w = await mountPage()
    const dz = w.find('.dropzone')
    expect(dz.classes()).not.toContain('active')
    await dz.trigger('dragover')
    expect(w.find('.dropzone').classes()).toContain('active')
    await dz.trigger('dragleave')
    expect(w.find('.dropzone').classes()).not.toContain('active')
  })

  it('drop: turn off highlight first, then get dataTransfer.files[0] and pass to onFile (blueprint onDrop :178-182)', async () => {
    const w = await mountPage()
    const dz = w.find('.dropzone')
    await dz.trigger('dragover')
    expect(w.find('.dropzone').classes()).toContain('active')

    await dz.trigger('drop', { dataTransfer: { files: [makeFile('dropped.md', 1234)] } })
    await nextTick()
    expect(w.find('.dropzone').classes()).not.toContain('active')
    // File actually entered → takes v-else branch .file-meta
    expect(w.find('.file-meta strong').text()).toBe('dropped.md')
  })

  it('drop but files empty → `if (f) onFile(f)` does not trigger, still no file selected state', async () => {
    const w = await mountPage()
    await w.find('.dropzone').trigger('drop', { dataTransfer: { files: [] } })
    await nextTick()
    expect(w.find('.file-meta').exists()).toBe(false)
    expect(w.find('.pick-btn').exists()).toBe(true)
  })

  it('`has` class follows `!!file` (absent when unselected, present when selected)', async () => {
    const w = await mountPage()
    expect(w.find('.dropzone').classes()).not.toContain('has')
    await pickFile(w, makeFile('a.md', 10))
    expect(w.find('.dropzone').classes()).toContain('has')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — pick file / clear (blueprint :27-37 / :183-197)', () => {
  it('no file selected: pick-btn + hint; click pick-btn forwards to hidden input click()', async () => {
    const w = await mountPage()
    expect(w.find('.pick-btn').text()).toBe('选择文件')
    expect(w.find('.dropzone .hint').text()).toBe('或拖拽到此处')
    const input = w.find('input[type="file"]').element as HTMLInputElement
    const click = vi.spyOn(input, 'click').mockImplementation(() => {})
    await w.find('.pick-btn').trigger('click')
    expect(click).toHaveBeenCalledTimes(1)
    click.mockRestore()
  })

  it('file selected: file-meta shows name + fmtBytes(size) + × clear button (N16: `×` outside t())', async () => {
    const w = await mountPage()
    await pickFile(w, makeFile('p5c-probe.md', 50))
    expect(w.find('.pick-btn').exists()).toBe(false)
    expect(w.find('.file-meta strong').text()).toBe('p5c-probe.md')
    expect(w.find('.file-meta .hint').text()).toBe('50 B')
    expect(w.find('.clear-btn').text()).toBe('×')
  })

  it('clearFile triple-clears: file / result / error all cleared (blueprint :193-197)', async () => {
    const w = await mountPage()
    await runWith(w) // first get a result
    expect(w.find('.chunks-card').exists()).toBe(true)
    // then create an error (second submit fails)
    ai.parserTestAnalyze.mockRejectedValueOnce(httpError(400, ERR_400_TARGET))
    await w.find('.submit-btn').trigger('click')
    await flushPromises()
    await nextTick()
    expect(w.find('.error-box').exists()).toBe(true)

    await w.find('.clear-btn').trigger('click')
    await nextTick()
    expect(w.find('.file-meta').exists()).toBe(false) // file cleared
    expect(w.find('.chunks-card').exists()).toBe(false) // result cleared
    expect(w.find('.error-box').exists()).toBe(false) // error cleared
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — 🔴 30 MB frontend check: only set error, do not clear file, do not send request (blueprint :185-188)', () => {
  // Test criterion: change code before `return` to "conveniently clear file" → first test in this group must fail.
  it('exactly 30 MB (=30*1024*1024) is not rejected — boundary is strictly `>`', async () => {
    const w = await mountPage()
    await pickFile(w, makeFile('exactly30.md', 30 * 1024 * 1024))
    expect(w.find('.file-meta strong').text()).toBe('exactly30.md')
    expect(w.find('.error-box').exists()).toBe(false)
  })

  it('🔴 one byte over is rejected: show error box, **selected file and existing result remain unchanged**, zero requests', async () => {
    const w = await mountPage()
    // first select normal file and get a result
    await runWith(w, makeFile('good.md', 50))
    expect(w.find('.chunks-card').exists()).toBe(true)
    expect(ai.parserTestAnalyze).toHaveBeenCalledTimes(1)

    await pickFile(w, makeFile('huge.bin', 30 * 1024 * 1024 + 1))
    expect(w.find('.error-box').text()).toBe('文件超过 30 MB，沙盒不支持')
    // 🔴 blueprint only does `return`: file was not cleared, result was not cleared
    expect(w.find('.file-meta strong').text()).toBe('good.md')
    expect(w.find('.chunks-card').exists()).toBe(true)
    // 🔴 no second request was sent
    expect(ai.parserTestAnalyze).toHaveBeenCalledTimes(1)
  })

  it('dropping an oversized file is also rejected (onDrop → onFile same code path)', async () => {
    const w = await mountPage()
    await w
      .find('.dropzone')
      .trigger('drop', { dataTransfer: { files: [makeFile('huge.md', 40 * 1024 * 1024)] } })
    await nextTick()
    expect(w.find('.error-box').text()).toBe('文件超过 30 MB，沙盒不支持')
    expect(w.find('.file-meta').exists()).toBe(false)
    expect(ai.parserTestAnalyze).not.toHaveBeenCalled()
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — three parameter inputs + resetParams (blueprint :39-53 / :198-200)', () => {
  it('three <label> parameter names are technical identifiers (N22), input min/max/step copied verbatim', async () => {
    const w = await mountPage()
    const labels = w.findAll('.params-row .param')
    expect(labels).toHaveLength(3)
    expect(labels.map((l) => sq(l.text()))).toEqual(['target_tokens', 'overlap_tokens', 'min_tokens'])
    const attrs = labels.map((l) => {
      const el = l.find('input').element as HTMLInputElement
      return [el.type, el.getAttribute('min'), el.getAttribute('max'), el.getAttribute('step')]
    })
    expect(attrs).toEqual([
      ['number', '50', '4000', '50'],
      ['number', '0', '400', '10'],
      ['number', '1', '200', null], // min_tokens blueprint has no step
    ])
  })

  it('default values 600 / 80 / 2', async () => {
    const w = await mountPage()
    expect(w.findAll('.params-row .param input').map((i) => (i.element as HTMLInputElement).value)).toEqual([
      '600',
      '80',
      '2',
    ])
  })

  it('🔴 `v-model.number` all three truly convert to number (payload is `String(700)` not raw string path `"700"`)', async () => {
    const w = await mountPage()
    const ins = w.findAll('.params-row .param input')
    await ins[0]!.setValue('700')
    await ins[1]!.setValue('120')
    await ins[2]!.setValue('5')
    await runWith(w)
    const e = Object.fromEntries(lastFormEntries())
    expect(e.target_tokens).toBe('700')
    expect(e.overlap_tokens).toBe('120')
    expect(e.min_tokens).toBe('5')
    // 🔴 where does discriminating power come from: with integer input, `.number` and bare `v-model` have **identical**
    // payloads (`String(700)` and `String('700')` both give `'700'`) → that assertion has zero discriminating power.
    // Only **decimals with trailing zeros** differentiate: `.number` goes through `looseToNumber('600.50')` → number 600.5
    // → `String(600.5)` = `'600.5'`; bare `v-model` keeps string `'600.50'` as-is.
    // Test criterion: remove `.number` from all three → this test must fail.
    await ins[0]!.setValue('600.50')
    await w.find('.submit-btn').trigger('click')
    await flushPromises()
    expect(Object.fromEntries(lastFormEntries()).target_tokens).toBe('600.5')
    // pin source shape too (governance §9 clause 9: pin call shape)
    const src = blankComments(readSrc())
    expect(src).toContain('v-model.number="params.target_tokens"')
    expect(src).toContain('v-model.number="params.overlap_tokens"')
    expect(src).toContain('v-model.number="params.min_tokens"')
  })

  it('resetParams returns to 600 / 80 / 2 (blueprint reassigns whole new object)', async () => {
    const w = await mountPage()
    const ins = w.findAll('.params-row .param input')
    await ins[0]!.setValue('123')
    await ins[1]!.setValue('45')
    await ins[2]!.setValue('6')
    expect(w.findAll('.params-row .param input').map((i) => (i.element as HTMLInputElement).value)).toEqual([
      '123',
      '45',
      '6',
    ])
    expect(w.find('.reset-btn').text()).toBe('重置')
    expect((w.find('.reset-btn').element as HTMLButtonElement).type).toBe('button')
    await w.find('.reset-btn').trigger('click')
    await nextTick()
    expect(w.findAll('.params-row .param input').map((i) => (i.element as HTMLInputElement).value)).toEqual([
      '600',
      '80',
      '2',
    ])
  })

  it('hint-line two sentences: default value explanation + overlap tip in `<em>` (N21 uses `5–20` with U+2013)', async () => {
    const w = await mountPage()
    const line = w.find('.hint-line')
    expect(sq(line.text())).toBe(
      '默认 target=600, overlap=80, min=2（沙盒宽松值；生产用 600/80/5–20）。 ' +
        'overlap 只对 plain 文本生效；markdown/source 按段落或函数边界切。',
    )
    expect(line.find('em').text()).toBe(
      'overlap 只对 plain 文本生效；markdown/source 按段落或函数边界切。',
    )
    // U+2013 (EN DASH) is not ASCII `-` — Appendix A §A.2 mandates copying each code point verbatim
    expect((enUs as Record<string, string>).aiKbPtDefaults).toContain('5–20')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — query / rerank / OCR three inputs (blueprint :59-71)', () => {
  it('query input placeholder goes through i18n; rerank label is hardcoded `rerank top-20` (N22)', async () => {
    const w = await mountPage()
    expect(w.find('.query-input').attributes('placeholder')).toBe(
      '（可选）输入 query，会计算每个 chunk 的余弦相似度',
    )
    const boxes = w.findAll('.row .checkbox')
    expect(boxes).toHaveLength(2)
    expect(sq(boxes[0]!.text())).toBe('rerank top-20')
    expect(sq(boxes[1]!.text())).toBe('OCR（扫描 PDF）')
  })

  it('both checkboxes default to false', async () => {
    const w = await mountPage()
    const els = w.findAll('.row .checkbox input').map((n) => n.element as HTMLInputElement)
    expect(els.map((e) => e.checked)).toEqual([false, false])
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — 🔴 K27 / K1 / FormData nine fields (blueprint :201-227)', () => {
  it('🔴 K27: `parserTestAnalyze(fd)` **single parameter** call — caller no longer passes headers/timeout', async () => {
    const w = await mountPage()
    await runWith(w)
    expect(ai.parserTestAnalyze).toHaveBeenCalledTimes(1)
    // Exactly 1 argument: package already includes multipart header + separate 120s timeout (`ai.ts:673-680`)
    expect(ai.parserTestAnalyze.mock.calls[0]).toHaveLength(1)
    expect(ai.parserTestAnalyze.mock.calls[0]![0]).toBeInstanceOf(FormData)
    // Pin "call shape" at source level (governance §9 clause 9: pin shape not bare identifiers), strip comments first
    const src = blankComments(readSrc())
    expect(src).toContain('result.value = (await service.ai.parserTestAnalyze(fd)) as AnalyzeResult')
    // 🔴 K1: no `.data` layer (package already does `return res.data`)
    expect(src).not.toMatch(/parserTestAnalyze\([^)]*\)\s*\)?\s*\.data/)
    // 🔴 no second argument (headers / timeout both in package)
    expect(src).not.toMatch(/parserTestAnalyze\(\s*fd\s*,/)
    expect(src).not.toContain("'Content-Type': 'multipart/form-data'")
    expect(src).not.toContain('timeout: 120000')
  })

  it('🔴 K1 rendering-side evidence: when mock returns fixture directly (no envelope), whole page renders normally', async () => {
    // Test criterion: if code stripped an extra `.data` layer, `result` would be undefined → every field would be empty.
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.ok-hint').exists()).toBe(true)
    expect(w.find('.chunks-card h3').text()).toBe('切块结果（1 块）')
  })

  it('🔴 FormData nine fields **order and values** copied verbatim (when query not empty)', async () => {
    const w = await mountPage()
    await w.find('.query-input').setValue('probe')
    await runWith(w, makeFile('p5c-probe.md', 50))
    expect(lastFormEntries()).toEqual([
      ['file', 'File(p5c-probe.md,50)'],
      ['query', 'probe'],
      ['embed', 'true'], // 🔴 always 'true' (blueprint :210 is literal, no switch affects it)
      ['rerank', 'false'],
      ['ocr', 'false'],
      ['target_tokens', '600'],
      ['overlap_tokens', '80'],
      ['min_tokens', '2'],
    ])
  })

  it('🔴 when query is empty **field `query` is truly absent** (blueprint :209 conditionally appends)', async () => {
    // Test criterion: change `if (query) fd.append(...)` to unconditional append → this test must fail.
    const w = await mountPage()
    await runWith(w)
    const entries = lastFormEntries()
    expect(entries.map(([k]) => k)).toEqual([
      'file',
      'embed',
      'rerank',
      'ocr',
      'target_tokens',
      'overlap_tokens',
      'min_tokens',
    ])
    expect(entries.map(([k]) => k)).not.toContain('query')
    const fd = ai.parserTestAnalyze.mock.calls[0]![0] as FormData
    expect(fd.getAll('query')).toEqual([])
    expect(fd.has('query')).toBe(false)
    // Seven of the other eight are still in (order not scrambled)
    expect(entries[0]![0]).toBe('file')
    expect(entries[1]![0]).toBe('embed')
  })

  it('rerank checked → `rerank=\'true\'`, ocr still `\'false\'` (one side of ternary)', async () => {
    const w = await mountPage()
    await w.findAll('.row .checkbox input')[0]!.setValue(true)
    await runWith(w)
    const e = Object.fromEntries(lastFormEntries())
    expect(e.rerank).toBe('true')
    expect(e.ocr).toBe('false')
  })

  it('ocr checked → `ocr=\'true\'`, rerank still `\'false\'` (other side of ternary)', async () => {
    const w = await mountPage()
    await w.findAll('.row .checkbox input')[1]!.setValue(true)
    await runWith(w)
    const e = Object.fromEntries(lastFormEntries())
    expect(e.rerank).toBe('false')
    expect(e.ocr).toBe('true')
  })

  it('both checked → both `\'true\'`; `embed` always `\'true\'`, unaffected by any switch', async () => {
    const w = await mountPage()
    await w.findAll('.row .checkbox input')[0]!.setValue(true)
    await w.findAll('.row .checkbox input')[1]!.setValue(true)
    await runWith(w)
    const e = Object.fromEntries(lastFormEntries())
    expect(e.rerank).toBe('true')
    expect(e.ocr).toBe('true')
    expect(e.embed).toBe('true')
  })

  it('clear error and result before submit (blueprint :204-205)', async () => {
    const w = await mountPage()
    ai.parserTestAnalyze.mockRejectedValueOnce(httpError(400, ERR_400_TARGET))
    await runWith(w)
    expect(w.find('.error-box').exists()).toBe(true)
    // second submit succeeds → error box disappears, result appears
    ai.parserTestAnalyze.mockResolvedValue(MD_OK)
    await w.find('.submit-btn').trigger('click')
    await flushPromises()
    await nextTick()
    expect(w.find('.error-box').exists()).toBe(false)
    expect(w.find('.chunks-card').exists()).toBe(true)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — submit button :disabled both sides + loading text (blueprint :74-78)', () => {
  it('no file selected → button disabled, text "Run" (first half of `:disabled="!file || loading"`)', async () => {
    const w = await mountPage()
    const btn = w.find('.submit-btn')
    expect((btn.element as HTMLButtonElement).disabled).toBe(true)
    expect(btn.text()).toBe('运行')
  })

  it('file selected → button enabled', async () => {
    const w = await mountPage()
    await pickFile(w, makeFile('a.md', 10))
    expect((w.find('.submit-btn').element as HTMLButtonElement).disabled).toBe(false)
  })

  it('🔴 while in flight → disabled + text "Processing…" (second half `|| loading`); after landing re-enable and show "Run"', async () => {
    const w = await mountPage()
    const d = deferred<unknown>()
    ai.parserTestAnalyze.mockReturnValue(d.promise)
    await pickFile(w, makeFile('a.md', 10))
    await w.find('.submit-btn').trigger('click')
    await nextTick()
    expect((w.find('.submit-btn').element as HTMLButtonElement).disabled).toBe(true)
    expect(w.find('.submit-btn').text()).toBe('处理中…')

    d.resolve(MD_OK)
    await flushPromises()
    await nextTick()
    expect((w.find('.submit-btn').element as HTMLButtonElement).disabled).toBe(false)
    expect(w.find('.submit-btn').text()).toBe('运行')
  })

  it('`submit()` start guard `if (!file) return`: direct call does not send request', async () => {
    const w = await mountPage()
    // Button is blocked by disabled, but guard exists (blueprint :202) — force DOM disable off then click
    const btn = w.find('.submit-btn').element as HTMLButtonElement
    btn.disabled = false
    await w.find('.submit-btn').trigger('click')
    await flushPromises()
    expect(ai.parserTestAnalyze).not.toHaveBeenCalled()
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — ok-hint (blueprint :79-89) + 🔴 governance §4.2 fact④', () => {
  it('not run yet → no render; after run → `✓ N chunks · size · mime ·` + params_used echo', async () => {
    const w = await mountPage()
    expect(w.find('.ok-hint').exists()).toBe(false)
    await runWith(w)
    // N16: `✓` (U+2713) and three `·` (U+00B7) outside t(); N22: `chunks` / `chunker=` etc. not in i18n
    expect(sq(w.find('.ok-hint').text())).toBe(
      '✓ 1 chunks · 50 B · text/markdown · chunker=markdown, target=600, overlap=0, min=2',
    )
  })

  it('🔴 fact④: shown is **backend-returned params_used**, not frontend-sent params — `.md` sends 80 returns 0', async () => {
    // Test criterion: if template reads `params` not `result.params_used`, would show overlap=80.
    const w = await mountPage()
    expect(
      (w.findAll('.params-row .param input')[1]!.element as HTMLInputElement).value,
    ).toBe('80') // frontend sent 80
    await runWith(w)
    expect(Object.fromEntries(lastFormEntries()).overlap_tokens).toBe('80') // confirmed sent 80
    expect(sq(w.find('.ok-hint em').text())).toBe(
      'chunker=markdown, target=600, overlap=0, min=2', // 🔴 backend returns 0
    )
  })

  it('🔴 other half of fact④: `.txt` goes through plain chunker → overlap returns unchanged at 10', async () => {
    ai.parserTestAnalyze.mockResolvedValue(TXT_RERANK)
    const w = await mountPage()
    await runWith(w, makeFile('p5c-probe.txt', 196, 'text/plain'))
    expect(sq(w.find('.ok-hint em').text())).toBe('chunker=plain, target=50, overlap=10, min=2')
    expect(sq(w.find('.ok-hint').text())).toBe(
      '✓ 1 chunks · 196 B · text/plain · chunker=plain, target=50, overlap=10, min=2',
    )
  })

  it('when `params_used` absent, whole `<em>` section does not render (blueprint :83 v-if)', async () => {
    // All six fixtures have `params_used`; this case can only be covered by mock (delete field) for v-if false side.
    const { params_used, ...noParams } = MD_OK
    void params_used
    ai.parserTestAnalyze.mockResolvedValue(noParams)
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.ok-hint').exists()).toBe(true)
    expect(w.find('.ok-hint em').exists()).toBe(false)
    expect(sq(w.find('.ok-hint').text())).toBe('✓ 1 chunks · 50 B · text/markdown ·')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — chunks card complete rendering (blueprint :126-149)', () => {
  it('md-ok: title `Chunking result (1 chunk)`, one chunk-item, chunk-head + chunk-text exact match', async () => {
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.chunks-card h3').text()).toBe('切块结果（1 块）')
    const items = w.findAll('.chunk-item')
    expect(items).toHaveLength(1)
    expect(items[0]!.find('.chunk-head strong').text()).toBe('chunk #0') // N22
    // N22: `tokens · offset a-b` entire string hardcoded
    expect(sq(items[0]!.find('.chunk-head .hint').text())).toBe('12 tokens · offset 0-50')
    // `<pre>` preserves original newlines (fixture text contains `\n\n`)
    expect(items[0]!.find('pre.chunk-text').text()).toBe(
      'Sandbox probe A.\n\nSecond paragraph for chunk two.',
    )
  })

  it('dense_preview: `dense [0:8]:` + 8 toFixed(4) comma-joined + `, …]` ending (N16 U+2026)', async () => {
    const w = await mountPage()
    await runWith(w)
    const embs = w.findAll('.chunk-item .emb-preview')
    expect(embs).toHaveLength(2)
    expect(embs[0]!.find('.emb-label').text()).toBe('dense [0:8]:')
    expect(embs[0]!.find('code').text()).toBe(
      '[-0.0309, 0.0237, 0.0030, -0.0038, -0.0316, -0.0135, 0.0212, 0.0347, …]',
    )
  })

  it('sparse_top_terms: `sparse top:` + `token_id:weight` joined with ` · ` (proves template shadowing `t` arrow parameter parses correctly)', async () => {
    // ⚠️ Blueprint :145 arrow parameter is called `t`, shadows i18n `t` in `<script setup>`.
    // This test also proves "Vue compiler scope tracking parses it as parameter, not `$setup.t`" —
    // if parsing failed would render as `undefined:undefined` or throw.
    const w = await mountPage()
    await runWith(w)
    const embs = w.findAll('.chunk-item .emb-preview')
    expect(embs[1]!.find('.emb-label').text()).toBe('sparse top:')
    expect(embs[1]!.find('code').text()).toBe(
      '151268:0.2153 · 11728:0.2056 · 6626:0.1726 · 7839:0.1494 · 77648:0.1463',
    )
  })

  it('dense_preview absent → that row not rendered; sparse_top_terms empty array → also not rendered (false side of both v-if)', async () => {
    const bare = {
      ...MD_OK,
      chunks: [{ chunk_no: 0, text: 'x', token_count: 1, offset_start: 0, offset_end: 1, sparse_top_terms: [] }],
    }
    ai.parserTestAnalyze.mockResolvedValue(bare)
    const w = await mountPage()
    await runWith(w)
    expect(w.findAll('.chunk-item')).toHaveLength(1)
    expect(w.findAll('.chunk-item .emb-preview')).toHaveLength(0)
  })

  it('🔴 `.empty` empty state (200 + chunk_count 0 + chunks []): governance §13 real-device-verifiable case', async () => {
    ai.parserTestAnalyze.mockResolvedValue(EMPTY_200)
    const w = await mountPage()
    await runWith(w, makeFile('p5c-empty.md', 0))
    expect(w.find('.chunks-card h3').text()).toBe('切块结果（0 块）')
    expect(w.find('.chunks-card .empty').text()).toBe(
      '解析得到 0 个 chunk。可能是文件太短或全是过滤掉的小段。',
    )
    expect(w.findAll('.chunk-list')).toHaveLength(0)
    expect(w.findAll('.chunk-item')).toHaveLength(0)
    // Empty file still 200 → ok-hint still shown, size is 0 B
    expect(sq(w.find('.ok-hint').text())).toBe(
      '✓ 0 chunks · 0 B · text/markdown · chunker=markdown, target=600, overlap=0, min=2',
    )
    // No query/scored → scored card not rendered
    expect(w.find('.scored-card').exists()).toBe(false)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — scored card two states + N18 + 🔴 governance §4.2 facts②③ (blueprint :106-124)', () => {
  it('md-ok: title `Query similarity ranking (top 1)`, cos three decimals, chunk-ref, rank-text has original chunk text', async () => {
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.scored-card h3').text()).toBe('Query 相似度排名（top 1）')
    expect(w.find('.rank-no').text()).toBe('#1') // N18: indexOf(s) + 1
    expect(w.find('.score').text()).toBe('cos 0.508') // N22: `cos ` hardcoded; toFixed(3)
    expect(w.find('.chunk-ref').text()).toBe('chunk #0') // N22
    expect(w.find('.rank-text').text()).toBe('Sandbox probe A.\n\nSecond paragraph for chunk two.')
  })

  it('🔴 fact②: `scored[]` has no `rerank_score` → `rr {…}` whole field not rendered (false side of dual guard)', async () => {
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.rerank-score').exists()).toBe(false)
    expect(w.find('.scored-card').text()).not.toContain('rr ')
  })

  it('rerank_score has value → render `rr` (mocked, never seen on this device)', async () => {
    ai.parserTestAnalyze.mockResolvedValue({
      ...MD_OK,
      scored: [{ chunk_no: 0, cos_sim: 0.5082847161344183, rerank_score: 0.87654 }],
    })
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.rerank-score').text()).toBe('rr 0.877') // N22 + toFixed(3)
  })

  it('`rerank_score: null` still not rendered (blueprint `!== null` half guard)', async () => {
    ai.parserTestAnalyze.mockResolvedValue({
      ...MD_OK,
      scored: [{ chunk_no: 0, cos_sim: 0.5, rerank_score: null }],
    })
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.rerank-score').exists()).toBe(false)
  })

  it('🔴 fact③: txt-rerank (rerank checked) → `⚠ Reranker error:` warning rendered, still no rr', async () => {
    // Device reranker is broken (backend defect, governance §8.2 has ticket) → this is the **only** thing visible after rerank check.
    ai.parserTestAnalyze.mockResolvedValue(TXT_RERANK)
    const w = await mountPage()
    await w.findAll('.row .checkbox input')[0]!.setValue(true)
    await runWith(w, makeFile('p5c-probe.txt', 196, 'text/plain'))
    expect(Object.fromEntries(lastFormEntries()).rerank).toBe('true')
    // N22: `⚠ Reranker error:` entire string hardcoded (N16: `⚠` outside t())
    expect(sq(w.find('.scored-card .warn').text())).toBe(
      '⚠ Reranker error: XLMRobertaTokenizer has no attribute prepare_for_model',
    )
    expect(w.find('.rerank-score').exists()).toBe(false)
  })

  it('`rerank_error` absent → warning not rendered (md-ok fixture)', async () => {
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.scored-card').exists()).toBe(true)
    expect(w.find('.scored-card .warn').exists()).toBe(false)
  })

  it('`scored` absent / empty array → whole card not rendered (blueprint :107 `&& length` dual guard)', async () => {
    ai.parserTestAnalyze.mockResolvedValue({ ...MD_OK, scored: [] })
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.scored-card').exists()).toBe(false)
    // Absent side
    const { scored, ...noScored } = MD_OK
    void scored
    ai.parserTestAnalyze.mockResolvedValue(noScored)
    await w.find('.submit-btn').trigger('click')
    await flushPromises()
    await nextTick()
    expect(w.find('.scored-card').exists()).toBe(false)
  })

  it('🔴 N18: rank number is `scored.indexOf(s) + 1` (**array position**), independent of chunk_no', async () => {
    // Test criterion: change to `v-for="(s, i)"` and take `i + 1` renders identically on this data — so this test only pins
    // the user-visible fact "rank follows array position, not chunk_no", pinning the code form as well.
    ai.parserTestAnalyze.mockResolvedValue({
      ...MD_OK,
      chunk_count: 3,
      chunks: [
        { chunk_no: 0, text: 'zero', token_count: 1, offset_start: 0, offset_end: 4 },
        { chunk_no: 1, text: 'one', token_count: 1, offset_start: 4, offset_end: 7 },
        { chunk_no: 2, text: 'two', token_count: 1, offset_start: 7, offset_end: 10 },
      ],
      // deliberately make chunk_no not match array position (backend returns by descending similarity)
      scored: [
        { chunk_no: 2, cos_sim: 0.9 },
        { chunk_no: 0, cos_sim: 0.5 },
        { chunk_no: 1, cos_sim: 0.1 },
      ],
    })
    const w = await mountPage()
    await runWith(w)
    expect(w.findAll('.rank-no').map((n) => n.text())).toEqual(['#1', '#2', '#3'])
    expect(w.findAll('.chunk-ref').map((n) => n.text())).toEqual(['chunk #2', 'chunk #0', 'chunk #1'])
    // rank-text uses chunkText(s.chunk_no) → looks up by chunk_no
    expect(w.findAll('.rank-text').map((n) => n.text())).toEqual(['two', 'zero', 'one'])
    // Source shape (N18 copied as-is, no v-for index)
    const src = blankComments(readSrc())
    expect(src).toContain('#{{ result.scored.indexOf(s) + 1 }}')
    expect(src).toContain('v-for="s in result.scored"')
  })

  it('rank-text goes through `truncate(chunkText(...), 200)`: 200 chars as-is, 201 chars truncated to 200 + U+2026', async () => {
    const s200 = 'a'.repeat(200)
    const s201 = 'b'.repeat(201)
    ai.parserTestAnalyze.mockResolvedValue({
      ...MD_OK,
      chunk_count: 2,
      chunks: [
        { chunk_no: 0, text: s200, token_count: 1, offset_start: 0, offset_end: 200 },
        { chunk_no: 1, text: s201, token_count: 1, offset_start: 200, offset_end: 401 },
      ],
      scored: [
        { chunk_no: 0, cos_sim: 0.9 },
        { chunk_no: 1, cos_sim: 0.8 },
      ],
    })
    const w = await mountPage()
    await runWith(w)
    const texts = w.findAll('.rank-text').map((n) => n.text())
    expect(texts[0]).toBe(s200) // exactly 200 → not truncated (blueprint uses strict `>`)
    expect(texts[0]).toHaveLength(200)
    expect(texts[1]).toBe('b'.repeat(200) + '…') // 201 → truncated + ellipsis
    expect(texts[1]).toHaveLength(201)
  })

  it('🔴 chunkText finds no matching chunk_no → falls back to empty string (blueprint `c ? c.text : \'\'`)', async () => {
    ai.parserTestAnalyze.mockResolvedValue({
      ...MD_OK,
      scored: [{ chunk_no: 99, cos_sim: 0.5 }], // chunks only has chunk_no 0
    })
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.chunk-ref').text()).toBe('chunk #99')
    expect(w.find('.rank-text').text()).toBe('')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — docling card two states + collapse (blueprint :97-104) + 🔴 governance §4.2 fact①', () => {
  it('🔴 fact①: both success fixtures (`.md` / `.txt`) produce **no `docling_markdown`** → whole card does not render', async () => {
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.docling-card').exists()).toBe(false)

    ai.parserTestAnalyze.mockResolvedValue(TXT_RERANK)
    await w.find('.submit-btn').trigger('click')
    await flushPromises()
    await nextTick()
    expect(w.find('.docling-card').exists()).toBe(false)
  })

  it('mock creates one with `docling_markdown`: collapse button text `▶ docling 转出的 markdown（N 字符）`, collapsed by default', async () => {
    // governance §13: to see this card you must send `.docx`/`.pptx`/`.xlsx` (🔴 **do not send `.pdf`**,
    // it triggers a ~200 MB model download) → on this device, rendering can only be verified via mock.
    const md = '# Title\n\nbody text'
    ai.parserTestAnalyze.mockResolvedValue({ ...MD_OK, docling_markdown: md })
    const w = await mountPage()
    await runWith(w, makeFile('doc.docx', 4096))
    const card = w.find('.docling-card')
    expect(card.exists()).toBe(true)
    // N16: `▼`/`▶` are outside t(); `{n}` is `docling_markdown.length` (observed 18)
    expect(md).toHaveLength(18)
    expect(sq(card.find('.toggle').text())).toBe('▶ docling 转出的 markdown（18 字符）')
    // v-show collapsed → element present but display: none
    const pre = card.find('pre.docling-md')
    expect(pre.exists()).toBe(true)
    expect((pre.element as HTMLElement).style.display).toBe('none')
    expect(pre.text()).toBe(md)
  })

  it('clicking the collapse button → arrow flips to `▼`, `<pre>` becomes visible; clicking again collapses it back', async () => {
    ai.parserTestAnalyze.mockResolvedValue({ ...MD_OK, docling_markdown: 'x' })
    const w = await mountPage()
    await runWith(w, makeFile('doc.docx', 4096))
    await w.find('.docling-card .toggle').trigger('click')
    await nextTick()
    expect(sq(w.find('.docling-card .toggle').text())).toBe('▼ docling 转出的 markdown（1 字符）')
    expect((w.find('pre.docling-md').element as HTMLElement).style.display).toBe('')

    await w.find('.docling-card .toggle').trigger('click')
    await nextTick()
    expect(sq(w.find('.docling-card .toggle').text())).toBe('▶ docling 转出的 markdown（1 字符）')
    expect((w.find('pre.docling-md').element as HTMLElement).style.display).toBe('none')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
// 🔴 Why 422 is not tested: the file-head comment already copied that response body and explained it —
// the submit button's `:disabled="!file || loading"` + `submit()`'s opening `if (!file) return` block it
// **doubly**; **the UI can never reach "submit without a file"**; governance §4.2 / §5.1 mandate: add no
// array branch for it, write no unit test for it.
// Below only tests the two 400s (`detail` is a string, reproducible on real devices) and "network error with no response".
describe('ParserTest — failure side: two 400s in .error-box + value-chain fallback (blueprint :221-224 / :92)', () => {
  it('400 `target_tokens must be in [50, 4000]` verbatim into .error-box', async () => {
    ai.parserTestAnalyze.mockRejectedValue(httpError(400, ERR_400_TARGET))
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.error-box').text()).toBe('target_tokens must be in [50, 4000]')
    // On failure, result stays null → all three result cards do not render
    expect(w.find('.ok-hint').exists()).toBe(false)
    expect(w.find('.chunks-card').exists()).toBe(false)
  })

  it('400 unsupported extension — whole string verbatim (including the long extension list after the semicolon) into .error-box', async () => {
    ai.parserTestAnalyze.mockRejectedValue(httpError(400, ERR_400_EXT))
    const w = await mountPage()
    await runWith(w, makeFile('p5c-probe.bin', 12, 'application/octet-stream'))
    expect(w.find('.error-box').text()).toBe(
      "extension '.bin' not supported in test sandbox; use .md / source code / .txt / .html / .json / .csv / .log / .pdf / .docx / .pptx / .xlsx",
    )
  })

  it('value-chain second tier: `response.data.error` (when there is no `detail`)', async () => {
    // Blueprint :222 is `data.detail || data.error` — both are read, copied as-is.
    ai.parserTestAnalyze.mockRejectedValue(httpError(500, { error: 'internal boom' }))
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.error-box').text()).toBe('internal boom')
  })

  it('value-chain third tier: no response (network-layer error) → falls back to `e.message`', async () => {
    ai.parserTestAnalyze.mockRejectedValue(new Error('Network Error'))
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.error-box').text()).toBe('Network Error')
  })

  it('value-chain fourth tier: message is empty → falls back to `String(e)`', async () => {
    ai.parserTestAnalyze.mockRejectedValue(new Error(''))
    const w = await mountPage()
    await runWith(w)
    expect(w.find('.error-box').text()).toBe('Error')
  })

  it('after failure, loading resets (`finally`) → button re-enabled, text back to 「运行」', async () => {
    ai.parserTestAnalyze.mockRejectedValue(httpError(400, ERR_400_TARGET))
    const w = await mountPage()
    await runWith(w)
    expect((w.find('.submit-btn').element as HTMLButtonElement).disabled).toBe(false)
    expect(w.find('.submit-btn').text()).toBe('运行')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — fmtBytes: both sides of all three tier boundaries (blueprint :236-240)', () => {
  // Observed via `.file-meta .hint` (blueprint :34 is one of its only call sites), through the real render path.
  async function bytesLabel(size: number): Promise<string> {
    const w = await mountPage()
    await pickFile(w, makeFile('x.md', size))
    return w.find('.file-meta .hint').text()
  }

  it('B tier: 0 / 1 / 1023 — integers concatenated directly with `" B"`, no decimals', async () => {
    expect(await bytesLabel(0)).toBe('0 B')
    expect(await bytesLabel(1)).toBe('1 B')
    expect(await bytesLabel(1023)).toBe('1023 B')
  })

  it('🔴 first boundary 1024: above it enters the KB tier, toFixed(1)', async () => {
    expect(await bytesLabel(1024)).toBe('1.0 KB')
    expect(await bytesLabel(1536)).toBe('1.5 KB')
  })

  it('🔴 second boundary 1048575 / 1048576: below stays KB (toFixed(1)), above enters MB (toFixed(2))', async () => {
    expect(await bytesLabel(1024 * 1024 - 1)).toBe('1024.0 KB')
    expect(await bytesLabel(1024 * 1024)).toBe('1.00 MB')
  })

  it('MB tier: two decimal places', async () => {
    expect(await bytesLabel(30 * 1024 * 1024)).toBe('30.00 MB')
    expect(await bytesLabel(1024 * 1024 * 3 + 512 * 1024)).toBe('3.50 MB')
  })

  it('size inside ok-hint also goes through the same fmtBytes (md-ok\'s 50 → `50 B`)', async () => {
    const w = await mountPage()
    await runWith(w, makeFile('p5c-probe.md', 50))
    expect(sq(w.find('.ok-hint').text())).toContain('· 50 B ·')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — 🔴 §9.2 strong en-locale assertions (zh collides; only en can discriminate)', () => {
  // Governance §9.2: for any item where "must use key A, not key B, because **en differs**", an assertion
  // that only compares zh has **zero discriminating power** (T6 review measured: swapping in the banned key still passes 47/47).
  //
  // 🔴 This pass already ran a programmatic collision scan of this page's 23 keys' zh values against
  //   **the full 1503-key table**, result:
  //   `aiKbPtProcessing`   zh 处理中…  <collides with>  `appsWorking`        en `Processing…` vs `Working…`  ← **EN-DIFF**
  //   `aiKbPtReset`        zh 重置      <collides with>  `filesViewerReset`   en `Reset` vs `Reset`           ← EN-SAME (no discriminating power)
  //   `aiKbPtRun`          zh 运行      <collides with>  `aiSkTestRun`        en `Run` vs `Run`               ← EN-SAME (no discriminating power)
  // → **the only sibling-key pair with en discriminating power is `aiKbPtProcessing` / `appsWorking`**: their zh
  //   values are identical character-for-character (both 「处理中…」), only the English UI can tell them apart.
  //   If someone lazily reuses `appsWorking`, the Chinese UI shows no visible difference and all three gates
  //   pass green — only switching to English reveals the button reads `Working…` (Vue2 has `Processing…`)
  //   = the interface is no longer 1:1. Hence this pair must have both a positive and a negative en-locale assertion.
  // The other two EN-SAME pairs are guarded via source-level key names (rendering assertions have zero
  // discriminating power for them, same treatment T6 applied to A-1).
  //
  // 🔴 locale is a global singleton → must be restored via try/finally, otherwise it pollutes later test cases in this file.
  const localeRef = i18n.global.locale as unknown as { value: string }

  async function inEn<T>(fn: (w: W) => Promise<T> | T): Promise<T> {
    const prev = localeRef.value
    localeRef.value = 'en_us'
    try {
      const w = await mountPage()
      return await fn(w)
    } finally {
      localeRef.value = prev
    }
  }

  it('🔴 en locale: button reads exactly `Processing…` while in flight, exactly `Run` after landing', async () => {
    await inEn(async (w) => {
      const d = deferred<unknown>()
      ai.parserTestAnalyze.mockReturnValue(d.promise)
      await pickFile(w, makeFile('a.md', 10))
      expect(w.find('.submit-btn').text()).toBe('Run')
      await w.find('.submit-btn').trigger('click')
      await nextTick()
      expect(w.find('.submit-btn').text()).toBe('Processing…')
      d.resolve(MD_OK)
      await flushPromises()
    })
  })

  it('🔴 negative: the en-locale render must never contain the en value (`Working…`) of the banned reused key `appsWorking`', async () => {
    await inEn(async (w) => {
      const d = deferred<unknown>()
      ai.parserTestAnalyze.mockReturnValue(d.promise)
      await pickFile(w, makeFile('a.md', 10))
      await w.find('.submit-btn').trigger('click')
      await nextTick()
      expect(w.find('.submit-btn').text()).not.toBe('Working…')
      expect(w.text()).not.toContain('Working…')
      d.resolve(MD_OK)
      await flushPromises()
    })
    // conversely proves this pair **only en can discriminate**: zh values are identical character-for-character
    const zh = zhCn as Record<string, string>
    const en = enUs as Record<string, string>
    expect(zh.aiKbPtProcessing).toBe(zh.appsWorking)
    expect(en.aiKbPtProcessing).not.toBe(en.appsWorking)
    expect(en.aiKbPtProcessing).toBe('Processing…')
    expect(en.appsWorking).toBe('Working…')
  })

  it('the two EN-SAME sibling-key pairs (`aiKbPtReset`/`filesViewerReset` · `aiKbPtRun`/`aiSkTestRun`) can only be guarded via source-level key names', async () => {
    // Their en and zh values are both identical on each side → no rendering assertion can tell them apart (same treatment T6 applied to ruling A-1).
    const zh = zhCn as Record<string, string>
    const en = enUs as Record<string, string>
    expect(zh.aiKbPtReset).toBe(zh.filesViewerReset)
    expect(en.aiKbPtReset).toBe(en.filesViewerReset)
    expect(zh.aiKbPtRun).toBe(zh.aiSkTestRun)
    expect(en.aiKbPtRun).toBe(en.aiSkTestRun)
    // → the criterion falls on the call shape of "which key the template uses" (governance §9 clause 9: pin the shape, not the bare identifier)
    const src = blankComments(readSrc())
    expect(src).toContain("t('aiKbPtReset')")
    expect(src).toContain("t('aiKbPtRun')")
    expect(src).not.toMatch(/\bt\(\s*['"]filesViewerReset['"]/)
    expect(src).not.toMatch(/\bt\(\s*['"]aiSkTestRun['"]/)
  })

  it('en locale: whole-page key copy matches character-for-character (proves all 23 keys resolve to the correct en value)', async () => {
    await inEn(async (w) => {
      expect(w.find('.page-header h2').text()).toBe('Parser test sandbox')
      expect(w.find('a.back-link').text()).toBe('← Back to details')
      expect(w.find('.pick-btn').text()).toBe('Choose file')
      expect(w.find('.dropzone .hint').text()).toBe('or drag and drop here')
      expect(w.find('.reset-btn').text()).toBe('Reset')
      expect(w.find('.query-input').attributes('placeholder')).toBe(
        '(Optional) Enter a query to compute cosine similarity per chunk',
      )
      expect(sq(w.findAll('.row .checkbox')[1]!.text())).toBe('OCR (scanned PDF)')
      expect(sq(w.find('.hint-line').text())).toBe(
        'Defaults: target=600, overlap=80, min=2 (sandbox loose values; production uses 600/80/5–20). ' +
          'overlap only applies to plain text; markdown/source splits by paragraph or function boundary.',
      )
    })
  })

  it('switching back to zh is still Chinese (proves locale was restored, no pollution)', async () => {
    const w = await mountPage()
    expect(w.find('.page-header h2').text()).toBe('Parser 测试沙盒')
    expect(w.find('.submit-btn').text()).toBe('运行')
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — N16 emoji / symbol placement check (none may move into or out of t())', () => {
  it("this page's 23 key values contain zero emoji / zero arrows / zero `✓⚠×▼▶` (proves the symbols live in the template, not the locale pack)", () => {
    const zh = zhCn as Record<string, string>
    const en = enUs as Record<string, string>
    const KEYS = [
      'aiKbPtTitle', 'aiKbPtBackLink', 'aiKbPtHelp1', 'aiKbPtHelpNoWrite', 'aiKbPtHelpPreviewOnly',
      'aiKbPtSupports', 'aiKbPtAsWellAs', 'aiKbPtViaDocling', 'aiKbPtMaxSize', 'aiKbPtChooseFile',
      'aiKbPtDragDrop', 'aiKbPtReset', 'aiKbPtDefaults', 'aiKbPtOverlapNote', 'aiKbPtQueryPlaceholder',
      'aiKbPtOcr', 'aiKbPtProcessing', 'aiKbPtRun', 'aiKbPtDoclingToggle', 'aiKbPtScoredTitle',
      'aiKbPtChunksTitle', 'aiKbPtZeroChunks', 'aiKbPtTooBig',
    ]
    expect(KEYS).toHaveLength(23)
    for (const k of KEYS) {
      expect(typeof zh[k]).toBe('string')
      expect(typeof en[k]).toBe('string')
      expect(zh[k]).not.toMatch(/[←✓⚠×▼▶🧪→]/u)
      expect(en[k]).not.toMatch(/[←✓⚠×▼▶🧪→]/u)
    }
    // 🔴 conversely: `…` (U+2026) **is** inside `aiKbPtProcessing`'s key value (not concatenated by the template)
    expect(zh.aiKbPtProcessing).toBe('处理中…')
    expect(en.aiKbPtProcessing).toBe('Processing…')
  })

  it('exactly one space between symbol and copy in the template, order is 「symbol → copy」', async () => {
    const w = await mountPage()
    expect(w.find('a.back-link').text()).toBe('← 返回详情')
    expect(w.find('.clear-btn').exists()).toBe(false) // no × when no file is selected
    await runWith(w)
    expect(w.find('.clear-btn').text()).toBe('×')
    expect(sq(w.find('.ok-hint').text()).startsWith('✓ ')).toBe(true)

    ai.parserTestAnalyze.mockResolvedValue({ ...MD_OK, docling_markdown: 'x', rerank_error: 'boom' })
    await w.find('.submit-btn').trigger('click')
    await flushPromises()
    await nextTick()
    expect(sq(w.find('.docling-card .toggle').text()).startsWith('▶ ')).toBe(true)
    expect(sq(w.find('.scored-card .warn').text()).startsWith('⚠ Reranker error: ')).toBe(true)
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — 🔴 N22: hardcoded technical identifiers 「ruled out of the locale pack」', () => {
  // 🔴 **M-2 (review 2026-08-04) — these two guards were tightened from "broad substring scan" to "exact value + key-set closure".**
  // The first version ran a `v.includes(s)` blanket scan for **generic substrings** like `'cos '` / `'rr '` / `'chunk #'`:
  // currently 0 hits, but in the future any **unrelated** new key whose value contains these substrings (e.g. some
  // copy elsewhere happens to write 「rr 」) would produce a **false red** — the same family as governance §9 clause 9
  // (a negation assertion hitting unrelated content → wrongly blames correct code → tempts someone to "fix" something
  // that isn't broken). After tightening, discriminating power **did not drop**: the facts actually worth guarding are
  //   ① no key's **whole value** equals any of these technical strings (= nobody built a key for them);
  //   ② this page template's `t()` key set is **exactly** those 23 `aiKbPt*` keys (= nobody sneakily added one more key).
  // ② is the real criterion for "someone turned a technical string into an i18n key" — adding a key necessarily means
  // one more `t()` call in the template, and the key-set closure immediately breaks. RED probe H (stuffing
  // `aiKbPtRerankTop20` into zh_cn.ts) and probe I (swapping the bare `rerank top-20` in the template for
  // `{{ t('aiKbPtRerankTop20') }}`) verify these two facts respectively.
  it('①the 15 technical identifier strings are not the **whole value** of any key in either locale pack (exact equality, no broad substring)', () => {
    // 🔴 governance §3.5 N22: these are technical identifiers / parameter names, deliberately kept out of i18n by Vue2.
    // Adding a key = conjuring up a key Vue2 never had, and filling both en/zh with English = pure noise.
    const TECH = [
      'rerank top-20',
      'dense [0:8]:',
      'sparse top:',
      'chunk #',
      'cos ',
      'rr ',
      'target_tokens',
      'overlap_tokens',
      'min_tokens',
      'chunker=',
      'Reranker error',
      'tokens · offset',
      ' chunks ·',
      '.md .txt .html .json .csv .py .go .ts .java',
      '.pdf .docx .pptx .xlsx',
    ]
    expect(TECH).toHaveLength(15)
    for (const [name, pack] of [['zh_cn', zhCn], ['en_us', enUs]] as Array<[string, Record<string, unknown>]>) {
      const entries = Object.entries(pack).filter((e): e is [string, string] => typeof e[1] === 'string')
      expect(entries.length).toBeGreaterThan(1400) // scanning the full table, not an empty set
      for (const s of TECH) {
        // 🔴 **exact whole-value equality** (not `includes`): the criterion is 「whether someone built a key for this technical string」.
        // The error message carries the pack name and matched key name, for easy localization.
        expect(entries.filter(([, v]) => v === s).map(([k]) => `${name}.${k}`)).toEqual([])
      }
    }
  })

  it('②this page template\'s `t()` key set is **exactly** those 23 `aiKbPt*` keys (key-set closure — add one key and it breaks)', () => {
    // 🔴 this is the real criterion for "someone turned a technical string into an i18n key": adding a key
    // necessarily means one more `t()` call in the template → the key set no longer equals these 23 → red.
    // More precise than a broad substring scan, with zero false-red surface.
    // Strip comments (line-preserving) before scanning, otherwise it would hit key names mentioned in this
    // file's / the component's head comment (governance §9 clause 9).
    const src = blankComments(readSrc())
    const keys = [...src.matchAll(/(?<![\w$])t\(\s*'([^']+)'/g)].map((m) => m[1]!)
    const EXPECTED_23 = [
      'aiKbPtAsWellAs', 'aiKbPtBackLink', 'aiKbPtChooseFile', 'aiKbPtChunksTitle',
      'aiKbPtDefaults', 'aiKbPtDoclingToggle', 'aiKbPtDragDrop', 'aiKbPtHelp1',
      'aiKbPtHelpNoWrite', 'aiKbPtHelpPreviewOnly', 'aiKbPtMaxSize', 'aiKbPtOcr',
      'aiKbPtOverlapNote', 'aiKbPtProcessing', 'aiKbPtQueryPlaceholder', 'aiKbPtReset',
      'aiKbPtRun', 'aiKbPtScoredTitle', 'aiKbPtSupports', 'aiKbPtTitle',
      'aiKbPtTooBig', 'aiKbPtViaDocling', 'aiKbPtZeroChunks',
    ]
    expect(EXPECTED_23).toHaveLength(23)
    // call count = 23 (each key used exactly once, one-to-one with the blueprint's 23 `$t()` calls)
    expect(keys).toHaveLength(23)
    expect([...keys].sort()).toEqual([...EXPECTED_23].sort())
    // key-set closure: not one more, not one fewer
    expect(new Set(keys).size).toBe(23)
    // and these 23 keys all exist in both locale packs (otherwise the key name itself would render)
    for (const k of EXPECTED_23) {
      expect(typeof (zhCn as Record<string, unknown>)[k]).toBe('string')
      expect(typeof (enUs as Record<string, unknown>)[k]).toBe('string')
    }
  })

  it('these 15 strings are **bare text** in the template (not routed through t()), each one hits in the comment-stripped template', () => {
    const src = blankComments(readSrc())
    const m = /<template>([\s\S]*?)\n<\/template>/.exec(src)
    expect(m).not.toBeNull()
    const tmpl = m![1]!
    for (const s of [
      'rerank top-20',
      'dense [0:8]:',
      'sparse top:',
      'chunk #{{ s.chunk_no }}',
      'chunk #{{ c.chunk_no }}',
      'cos {{ s.cos_sim.toFixed(3) }}',
      'rr {{ s.rerank_score.toFixed(3) }}',
      'target_tokens',
      'overlap_tokens',
      'min_tokens',
      'chunker={{ result.params_used.chunker }}',
      '⚠ Reranker error: {{ result.rerank_error }}',
      'tokens · offset {{ c.offset_start }}-{{ c.offset_end }}',
      'chunks ·',
      '<code>.md .txt .html .json .csv .py .go .ts .java</code>',
      '<code>.pdf .docx .pptx .xlsx</code>',
    ]) {
      expect(tmpl).toContain(s)
    }
  })
})

// ═══════════════════════════════════════════════════════════════════════════
describe('ParserTest — guard gap③: zero bare color literals in the <template> block', () => {
  // governance §9 gap③: `color-guard.test.ts:44-56`'s `styleLines()` only takes the `<style>` block for
  // `.vue` files → template `style=` / `:style=` attributes get zero scanning; this file adds one targeted
  // assertion to plug that blind spot.
  // ⚠️ **follows the existing convention** (non-greedy + implicitly anchored on 「`</template>` at column 0」,
  // precedent: `ParserStatus.test.ts` / `QueueView.test.ts` / `IndexedFilesView.test.ts`);
  // governance §9 gap③′'s "unify to greedy matching + coverage self-check" belongs to **T8**, this pass leaves it alone.
  // 🔴 read the source file with `node:fs`, not Vite's `?raw`.
  it('<template> block (after stripping var()/color-mix()) contains no bare hex / rgb / hsl literals', () => {
    const src: string = readSrc()
    const m = /<template>([\s\S]*?)\n<\/template>/.exec(src)
    expect(m).not.toBeNull()
    const tmpl = m![1]!
    // coverage self-check: the extracted fragment must contain both the template's **head** and **tail** marker strings.
    // This component's only nested `<template v-if="result">` carries an attribute (not a bare `<template>`), and
    // its closing tag is also indented → the column-0 `</template>` will not be cut off early.
    expect(tmpl).toContain("t('aiKbPtTitle')") // head (page header h2)
    expect(tmpl).toContain("join(' · ') }}</code>") // tail (chunks card's last line of content)

    // strip the insides of var(...) and color-mix(...) (same technique as color-guard.test.ts's stripVar:
    // scan character by character tracking matched-parenthesis depth, supports nested fallback)
    function stripCalls(s: string, prefixes: string[]): string {
      let out = ''
      let i = 0
      while (i < s.length) {
        const hit = prefixes.find((p) => s.startsWith(p, i))
        if (hit) {
          let depth = 0
          let j = i + hit.length - 1 // lands on the opening parenthesis
          for (; j < s.length; j++) {
            if (s[j] === '(') depth++
            else if (s[j] === ')') {
              depth--
              if (depth === 0) {
                j++
                break
              }
            }
          }
          i = j
        } else {
          out += s[i]
          i++
        }
      }
      return out
    }
    const scrubbed = stripCalls(tmpl, ['var(', 'color-mix('])
    expect(scrubbed).not.toMatch(/#[0-9a-fA-F]{3,8}\b/)
    expect(scrubbed).not.toMatch(/\b(rgba?|hsla?)\s*\(/)
  })

  it('this file has zero <style> blocks (K24: styles live in parser-styles.scss, imported on the JS side)', () => {
    const src: string = readSrc()
    expect(src).not.toMatch(/^<style/m)
    expect(src).toContain("import '../../styles/parser-styles.scss'")
  })

  it('zero KIcon (governance §1.2 / E-2 / N16: neither of the two Parser page blueprints uses KIcon)', async () => {
    const src: string = readSrc()
    expect(src).not.toMatch(/^import KIcon/m)
    const w = await mountPage()
    await runWith(w)
    expect(w.findAll('svg')).toHaveLength(0)
  })
})
